# Tiny cmake-script-mode script. cmake runs this with `cmake -P
# gen.cmake` and the script writes its output to ${OUTPUT}, set
# via -DOUTPUT=... by the add_custom_command. The shape mirrors
# libpng's pnglibconf generation pattern.
file(WRITE "${OUTPUT}" "/* generated by gen.cmake */\n#define SCRIPTMODE_OK 1\n")
