// Package commonflags hoists the compile flags shared by EVERY converted cc
// target into a single cc_toolchain feature, so they aren't duplicated across
// every target's `copts` in the emitted BUILD(s).
//
// The converter records each target's flags per-target (lower's
// splitCompileFragments → ir.Target.Copts); project-wide flags (cmake's
// CMAKE_<LANG>_FLAGS — -O2, arch flags, …) therefore repeat once per target.
// HoistCommonCopts finds the longest copt PREFIX every eligible cc target
// shares (cmake emits the global flags first, so a prefix is the natural
// shape and recombining feature-flags-before-copts preserves cmake's order),
// strips it from each target, and tags those targets
// `features = ["cmake_common_compile_flags"]`. Emit renders the matching
// `feature()` .bzl the operator threads into whatever cc_toolchain the build
// uses (the converter-emitted one, rules_cc's auto-detected default, or their
// own) — the same operator-wired convention as the sanitizer / raw-flag
// features (sanitizerfeatures, lift_feature_flags). Opt-in via
// convert-element-cmake --out-common-compile-flags-feature; off by default so
// the inline per-target emission stays byte-stable.
package commonflags

import (
	"bytes"
	"fmt"
)

// FeatureName is the cc_toolchain feature the hoisted flags ride on and the
// name stripped targets reference via `features = [...]`.
const FeatureName = "cmake_common_compile_flags"

// compileActions are the cc_toolchain action names the hoisted compile flags
// instrument — every compile action, since a target's copts apply to all of
// its compiles regardless of language.
var compileActions = []string{
	"ACTION_NAMES.c_compile",
	"ACTION_NAMES.cpp_compile",
	"ACTION_NAMES.cpp_module_compile",
	"ACTION_NAMES.assemble",
	"ACTION_NAMES.preprocess_assemble",
}

// Emit renders the cc_toolchain feature .bzl carrying copts. Caller writes it
// to disk. An empty copts slice still emits the header + an empty
// COMMON_COMPILE_FLAGS_FEATURES list so the operator's load() doesn't break
// when there was nothing to hoist.
func Emit(featureName string, copts []string) []byte {
	var buf bytes.Buffer
	buf.WriteString(header)
	if len(copts) == 0 {
		buf.WriteString("COMMON_COMPILE_FLAGS_FEATURES = []\n")
		return buf.Bytes()
	}
	buf.WriteString(loads)
	buf.WriteString("\n")
	fmt.Fprintf(&buf, "%s_feature = feature(\n", featureName)
	fmt.Fprintf(&buf, "    name = %q,\n", featureName)
	// enabled = False: applied per-target via features = [...] on exactly the
	// targets the converter stripped, so a target that did NOT share the
	// prefix (and kept its full copts) never gets the flags twice.
	fmt.Fprintf(&buf, "    enabled = False,  # applied per-target via features = [%q]\n", featureName)
	buf.WriteString("    flag_sets = [\n")
	buf.WriteString("        flag_set(\n")
	buf.WriteString("            actions = [\n")
	for _, a := range compileActions {
		fmt.Fprintf(&buf, "                %s,\n", a)
	}
	buf.WriteString("            ],\n")
	buf.WriteString("            flag_groups = [flag_group(flags = [\n")
	for _, f := range copts {
		fmt.Fprintf(&buf, "                %q,\n", f)
	}
	buf.WriteString("            ])],\n")
	buf.WriteString("        ),\n")
	buf.WriteString("    ],\n")
	buf.WriteString(")\n\n")
	fmt.Fprintf(&buf, "COMMON_COMPILE_FLAGS_FEATURES = [%s_feature]\n", featureName)
	return buf.Bytes()
}

const header = `# Generated by convert-element-cmake. DO NOT EDIT.
#
# A cc_toolchain feature carrying the compile flags shared by EVERY converted
# cc target — the longest common copt prefix, typically cmake's project-wide
# CMAKE_<LANG>_FLAGS (-O2, arch flags, ...). The converter STRIPPED these from
# each target's copts and tagged those targets
# features = ["cmake_common_compile_flags"], so wiring this feature restores
# them, applied BEFORE each target's own copts (cmake's "global flags first"
# order).
#
# Thread COMMON_COMPILE_FLAGS_FEATURES into
# cc_common.create_cc_toolchain_config_info(... features = ...) of whatever
# toolchain the build uses (the converter-emitted one, rules_cc's auto-detected
# default, or your own). WITHOUT it, the stripped flags are not applied. Same
# operator-wired convention as the sanitizer / raw-flag features.
#
# Byte-stable across runs; re-generated by
# convert-element-cmake --out-common-compile-flags-feature=<path>.

`

const loads = `load("@bazel_tools//tools/build_defs/cc:action_names.bzl", "ACTION_NAMES")
load(
    "@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl",
    "feature",
    "flag_group",
    "flag_set",
)
`
