package commonflags

import (
	"bytes"
	"fmt"

	"github.com/sstriker/buildstream-bazel/converter/ir"
)

// HoistCommonCopts finds the longest copt prefix shared by every eligible cc
// target, strips it from each, and tags those targets
// `features = [featureName]` so the prefix is reapplied by the cc_toolchain
// feature (before per-target copts — matching cmake's global-flags-first
// order). Returns the hoisted prefix (the flags Emit's feature .bzl should
// carry), or nil when there's nothing to hoist. Mutates pkg in place.
//
// Eligibility: cc_library / cc_binary / cc_test / cc_interface targets with a
// non-empty flat Copts. Targets with empty copts are skipped (nothing to
// strip, and they shouldn't shrink the shared prefix). A target's PerPlatform
// copts select-arms are untouched — only the always-applied flat prefix is
// hoisted, which the always-enabled-per-target feature faithfully restores.
//
// Conservative by construction: the prefix is what ALL candidates share from
// position 0, so every candidate is stripped uniformly and order is preserved
// exactly (feature flags emit before the target's remaining copts). A single
// candidate whose flags diverge at position k caps the prefix at k; no
// reordering risk.
func HoistCommonCopts(pkg *ir.Package, featureName string) []string {
	if pkg == nil {
		return nil
	}
	cands := commonCoptCandidates(pkg)
	if len(cands) < 2 {
		return nil
	}
	prefix := longestCommonCoptPrefix(cands)
	if len(prefix) == 0 {
		return nil
	}
	for _, t := range cands {
		t.Copts = append([]string(nil), t.Copts[len(prefix):]...)
		if len(t.Copts) == 0 {
			t.Copts = nil
		}
		if !contains(t.Features, featureName) {
			t.Features = append(t.Features, featureName)
		}
	}
	return prefix
}

// commonCoptCandidates returns the cc targets eligible for a common-copt hoist:
// cc_library / cc_binary / cc_test / cc_interface with a non-empty flat Copts.
// Empty-copts targets are skipped (nothing to strip, and they'd needlessly
// shrink the shared prefix); non-cc targets are ignored.
func commonCoptCandidates(pkg *ir.Package) []*ir.Target {
	var cands []*ir.Target
	for i := range pkg.Targets {
		t := &pkg.Targets[i]
		switch t.Kind {
		case ir.KindCCLibrary, ir.KindCCBinary, ir.KindCCTest, ir.KindCCInterface:
		default:
			continue
		}
		if len(t.Copts) == 0 {
			continue
		}
		cands = append(cands, t)
	}
	return cands
}

// longestCommonCoptPrefix returns the longest leading run of copts that every
// candidate shares (by exact string equality, position by position).
func longestCommonCoptPrefix(cands []*ir.Target) []string {
	first := cands[0].Copts
	n := len(first)
	for _, t := range cands[1:] {
		if len(t.Copts) < n {
			n = len(t.Copts)
		}
	}
	i := 0
	for i < n {
		flag := first[i]
		match := true
		for _, t := range cands[1:] {
			if t.Copts[i] != flag {
				match = false
				break
			}
		}
		if !match {
			break
		}
		i++
	}
	return append([]string(nil), first[:i]...)
}

func contains(xs []string, v string) bool {
	for _, x := range xs {
		if x == v {
			return true
		}
	}
	return false
}

// HoistCommonCoptsToConstant is the self-contained `defs.bzl` mode: like
// HoistCommonCopts it strips the longest shared copt prefix from every
// eligible cc target, but instead of tagging them with a cc_toolchain feature
// (which needs operator wiring) it sets PrependCommonCopts on each stripped
// target and records loadLabel on the package, so the emitter renders
// `copts = COMMON_COPTS + [delta]` and `load(loadLabel, "COMMON_COPTS")`. The
// flags ride a generated `common_compile_flags.bzl` constant the emitted BUILDs
// load directly — no toolchain wiring, works with the default toolchain.
// Returns the hoisted prefix (for EmitConstant), or nil when nothing hoists.
// Mutates pkg in place.
func HoistCommonCoptsToConstant(pkg *ir.Package, loadLabel string) []string {
	if pkg == nil {
		return nil
	}
	cands := commonCoptCandidates(pkg)
	if len(cands) < 2 {
		return nil
	}
	prefix := longestCommonCoptPrefix(cands)
	if len(prefix) == 0 {
		return nil
	}
	for _, t := range cands {
		t.Copts = append([]string(nil), t.Copts[len(prefix):]...)
		if len(t.Copts) == 0 {
			t.Copts = nil
		}
		t.PrependCommonCopts = true
	}
	pkg.CommonCoptsLabel = loadLabel
	return prefix
}

// EmitConstant renders the self-contained `common_compile_flags.bzl` defining
// COMMON_COPTS. Empty copts still emits an empty list so a BUILD's load()
// doesn't break.
func EmitConstant(copts []string) []byte {
	var buf bytes.Buffer
	buf.WriteString(constHeader)
	if len(copts) == 0 {
		buf.WriteString("COMMON_COPTS = []\n")
		return buf.Bytes()
	}
	buf.WriteString("COMMON_COPTS = [\n")
	for _, f := range copts {
		fmt.Fprintf(&buf, "    %q,\n", f)
	}
	buf.WriteString("]\n")
	return buf.Bytes()
}

const constHeader = `# Generated by convert-element-cmake. DO NOT EDIT.
#
# COMMON_COPTS — the compile flags shared by EVERY converted cc target (the
# longest common copt prefix, typically cmake's project-wide CMAKE_<LANG>_FLAGS:
# -O2, arch flags, ...). The converter STRIPPED these from each target's copts
# and rewrote them as copts = COMMON_COPTS + [<per-target flags>], so the flags
# live in one place instead of repeating per target. Self-contained: no
# cc_toolchain wiring needed (cf. the --out-common-compile-flags-feature mode).
#
# Byte-stable across runs; re-generated by
# convert-element-cmake --emit-common-compile-flags-bzl.

`
