package cmakerun

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// TestProbeGenex_DuplicateSubdir_LiveCMake pins the fix for the
// duplicate-target-name regression under cmake 4: probe-genex.cmake must
// not emit two file(GENERATE) calls with the same OUTPUT when a target
// name is collected twice.
//
// The fixture add_subdirectory()'s the same source dir into two binary
// dirs (a vendoring pattern). cmake lists that source dir twice under the
// parent's SUBDIRECTORIES property, so the probe's recursive
// BUILDSYSTEM_TARGETS walk collected the dir's target name twice. The
// duplicate name produced two file(GENERATE) OUTPUTs at
// cmake-to-bazel.genex/<tgt>/type.txt; cmake 3.x tolerated the
// identical-content duplicate, cmake 4 rejects it as a hard error ("Files
// to be generated by multiple different commands") and aborts the whole
// generate step. The fix list(REMOVE_DUPLICATES)es the collected target
// list before emitting any probe.
//
// Drives cmake directly with the hook injected — the failure mode is in
// cmake's generation step, so we assert on the exit code. Skips cleanly
// without cmake >= 3.24 (the CMAKE_PROJECT_TOP_LEVEL_INCLUDES floor).
func TestProbeGenex_DuplicateSubdir_LiveCMake(t *testing.T) {
	if _, err := exec.LookPath("cmake"); err != nil {
		t.Skip("cmake not on PATH; skipping probe-genex duplicate-subdir live test")
	}
	major, minor, _, err := AssertVersion(context.Background())
	if err != nil {
		t.Skipf("cmake below codemodel-v2 floor: %v", err)
	}
	if major < 3 || (major == 3 && minor < 24) {
		t.Skipf("cmake %d.%d below probe-genex floor (3.24+); skipping", major, minor)
	}

	src, err := filepath.Abs("../../testdata/sample-projects/probe-genex-duplicate-subdir")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(src); err != nil {
		t.Fatalf("fixture missing: %v", err)
	}
	hook, err := filepath.Abs("probe-genex.cmake")
	if err != nil {
		t.Fatal(err)
	}

	// Cover both generator modes: the duplicate OUTPUT is type.txt, which
	// is config-invariant, so the collision exists regardless of config
	// count — but exercise both since the dedup lives in the per-target
	// loop preamble shared by the single- and multi-config emit paths.
	for _, tc := range []struct {
		name      string
		generator string
		extraArgs []string
	}{
		{"single-config", "Ninja", []string{"-DCMAKE_BUILD_TYPE=Release"}},
		{"multi-config", "Ninja Multi-Config", []string{"-DCMAKE_CONFIGURATION_TYPES=Release;Debug"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			buildDir := t.TempDir()
			args := []string{"-S", src, "-B", buildDir, "-G", tc.generator}
			args = append(args, tc.extraArgs...)
			args = append(args, "-DCMAKE_PROJECT_TOP_LEVEL_INCLUDES="+hook)
			cmd := exec.CommandContext(context.Background(), "cmake", args...)
			out, err := cmd.CombinedOutput()
			if err != nil {
				t.Fatalf("cmake configure+generate with probe-genex hook failed on the duplicate-subdir fixture (the fix should de-duplicate the target list, not abort): %v\n%s", err, out)
			}

			// The deduped name is still probed exactly once: the
			// collection keeps the first occurrence (shared_a), so its
			// per-target dir must exist with a single type.txt.
			probed := filepath.Join(buildDir, ProbeGenexDirname, "shared_a")
			if _, err := os.Stat(filepath.Join(probed, "type.txt")); err != nil {
				t.Errorf("expected the deduped target shared_a to be probed once, but its type.txt is missing: %v", err)
			}
		})
	}
}
