package cmakerun

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// The literal-probe hook (Options.LiteralProbes) is the second
// half of the generalized genex resolution story. The per-target
// structural probe (probe-genex.cmake) resolves a FIXED set of
// shapes ($<TARGET_FILE>, $<TARGET_OBJECTS>, INTERFACE_*) that the
// hook can enumerate from BUILDSYSTEM_TARGETS without knowing the
// project's source — so it rides the first configure pass. An
// ARBITRARY genex literal (e.g. $<TARGET_PROPERTY:t,CUSTOM_PROP>,
// $<GENEX_EVAL:…>, $<COMPILE_LANGUAGE:…> in a file(GENERATE)
// CONTENT body or add_custom_command argv) can't be enumerated up
// front: the converter only learns the exact literal strings by
// parsing the post-configure trace. So resolving them needs a
// SECOND configure pass that re-runs cmake's own evaluator over
// the now-known literals via file(GENERATE CONTENT "<literal>").
//
// The second pass reuses the first pass's build dir (warm cache:
// every try_compile / find_package result is already cached), so
// it costs a small fraction of the first configure — measured
// ~3% on a representative project. It injects ONLY this hook and
// changes no cache variable, which keeps the cache warm.
//
// LiteralProbeRequest is one such literal the lifter couldn't
// resolve via the Go-side evaluator + structural probe.
type LiteralProbeRequest struct {
	// Literal is the exact genex string to resolve, e.g.
	// "$<TARGET_PROPERTY:foo,CUSTOM_PROP>". cmake evaluates it as
	// a file(GENERATE) CONTENT body, so any genex valid in that
	// position resolves.
	Literal string
	// Target, when non-empty, names the cmake target whose
	// context the literal evaluates in — passed as file(GENERATE
	// … TARGET <Target>). Target-context genexes ($<COMPILE_*>,
	// bare $<TARGET_PROPERTY:prop>) need this; project-scoped
	// literals ($<TARGET_FILE:explicit>) leave it empty.
	Target string
}

// Hash is the stable filename stem the probe output uses for this
// request — a hex SHA-256 prefix over (Literal, Target). Stable
// across runs so the hook output, the reader, and any golden stay
// in lockstep; collision-resistant enough that two distinct
// requests don't alias on one probe file.
func (r LiteralProbeRequest) Hash() string {
	sum := sha256.Sum256([]byte(r.Literal + "\x00" + r.Target))
	return hex.EncodeToString(sum[:])[:16]
}

const (
	// LiteralProbeFilename is the basename of the generated hook
	// Configure stages into the build dir when Options.LiteralProbes
	// is non-empty.
	LiteralProbeFilename = "cmake-to-bazel.probe-literals.cmake"
	// LiteralProbeDirname is the per-build subdirectory cmake's
	// file(GENERATE) declarations populate with resolved literal
	// bytes, one <hash>.<config>.txt per request.
	LiteralProbeDirname = "cmake-to-bazel.litgenex"
)

// RenderLiteralProbeHook generates the .cmake hook body that
// resolves each request via a deferred file(GENERATE). Requests
// are emitted in a deterministic order (sorted by hash) so the
// generated file is byte-stable for a given request set. Returns
// nil for an empty request set so callers can skip staging.
//
// Each request becomes:
//
//	file(GENERATE
//	     OUTPUT "${_d}/<hash>.$<CONFIG>.txt"
//	     CONTENT "<escaped-literal>"
//	     [TARGET <target>])
//
// The $<CONFIG> in OUTPUT gives one file per configuration so the
// hook composes with Ninja Multi-Config (without per-config
// OUTPUT, cmake refuses with "Evaluation file to be written
// multiple times with different content"). ReadLiteralProbe reads
// the per-config files back and lets the caller decide flat-value
// vs select().
func RenderLiteralProbeHook(reqs []LiteralProbeRequest) []byte {
	if len(reqs) == 0 {
		return nil
	}
	sorted := make([]LiteralProbeRequest, len(reqs))
	copy(sorted, reqs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Hash() < sorted[j].Hash() })

	var b strings.Builder
	b.WriteString("# Generated by cmakerun — generalized genex literal probe\n")
	b.WriteString("# (Options.LiteralProbes, the warm second configure pass).\n")
	b.WriteString("# Resolves arbitrary genex literals the converter discovered\n")
	b.WriteString("# in the first pass's trace via cmake's own evaluator. One\n")
	b.WriteString("# file(GENERATE) per literal, $<CONFIG> in OUTPUT so the hook\n")
	b.WriteString("# composes with Ninja Multi-Config.\n")
	b.WriteString("if(NOT _CMTB_LITPROBE_REGISTERED)\n")
	b.WriteString("    set(_CMTB_LITPROBE_REGISTERED TRUE)\n")
	b.WriteString("    cmake_language(DEFER DIRECTORY \"${CMAKE_SOURCE_DIR}\" CALL _cmtb_litprobe)\n")
	b.WriteString("endif()\n\n")
	b.WriteString("function(_cmtb_litprobe)\n")
	b.WriteString("    set(_d \"${CMAKE_BINARY_DIR}/" + LiteralProbeDirname + "\")\n")
	for _, r := range sorted {
		out := "${_d}/" + r.Hash() + ".$<CONFIG>.txt"
		b.WriteString("    file(GENERATE\n")
		b.WriteString("         OUTPUT \"" + out + "\"\n")
		b.WriteString("         CONTENT \"" + escapeCMakeContent(r.Literal) + "\"")
		if r.Target != "" {
			b.WriteString("\n         TARGET " + r.Target)
		}
		b.WriteString(")\n")
	}
	b.WriteString("endfunction()\n")
	return []byte(b.String())
}

// escapeCMakeContent escapes a literal for embedding inside a
// cmake double-quoted argument (file(GENERATE CONTENT "…")).
// Backslash and double-quote are the only characters that break
// the quoting; `$` must pass through unescaped because that's
// where the genex the probe is meant to evaluate lives.
func escapeCMakeContent(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return s
}

// LiteralResolution is the per-config resolved bytes for one
// probed literal. PerConfig maps config name → resolved value;
// single-config builds carry one entry (config "" when the build
// has no CMAKE_BUILD_TYPE). The caller decides how to lower it:
// Unified() collapses to a flat value when every config agrees,
// otherwise the PerConfig map drives a select() over
// //config:<name>.
type LiteralResolution struct {
	PerConfig map[string]string
}

// Unified returns (value, true) when every configuration resolved
// the literal to the same bytes — the common case for literals
// that don't depend on $<CONFIG>. Returns ("", false) when values
// diverge across configs, signalling the caller to emit a
// select() instead of a flat value.
func (r LiteralResolution) Unified() (string, bool) {
	return collapseConfigValues(r.PerConfig)
}

// ReadLiteralProbe walks <buildDir>/cmake-to-bazel.litgenex/ and
// returns one LiteralResolution per probed literal, keyed by the
// request hash (the filename stem). Returns (nil, nil) when the
// directory doesn't exist — the hook wasn't staged, cmake didn't
// reach generation, or the second pass was skipped.
//
// Unlike ReadGenexProbe, this reader PRESERVES per-config
// divergence (returns the full PerConfig map) rather than dropping
// it: an arbitrary literal that genuinely differs per config is
// exactly the multi-config case the lifter wants to lower to a
// select() over //config:<name>.
func ReadLiteralProbe(buildDir string) (map[string]LiteralResolution, error) {
	root := filepath.Join(buildDir, LiteralProbeDirname)
	entries, err := os.ReadDir(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("cmakerun: read literal probe dir: %w", err)
	}
	perHash := map[string]map[string]string{}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		hash, config, ok := splitLiteralProbeFilename(e.Name())
		if !ok {
			continue
		}
		val, err := os.ReadFile(filepath.Join(root, e.Name()))
		if err != nil {
			return nil, fmt.Errorf("cmakerun: read literal probe %s: %w", e.Name(), err)
		}
		bucket, ok := perHash[hash]
		if !ok {
			bucket = map[string]string{}
			perHash[hash] = bucket
		}
		bucket[config] = string(val)
	}
	if len(perHash) == 0 {
		return nil, nil
	}
	out := make(map[string]LiteralResolution, len(perHash))
	for hash, perConfig := range perHash {
		out[hash] = LiteralResolution{PerConfig: perConfig}
	}
	return out, nil
}

// splitLiteralProbeFilename parses "<hash>.<config>.txt" into
// ("<hash>", "<config>", true). The hash is a hex SHA-256 prefix
// (no `.`), so the first `.` reliably marks the hash/config
// boundary even when the config name itself contains a `.`. An
// empty $<CONFIG> (a build with no CMAKE_BUILD_TYPE) writes
// "<hash>..txt", which parses to config "" — handled explicitly
// rather than dropped, so single-config no-build-type probes
// aren't silently lost.
func splitLiteralProbeFilename(fname string) (hash, config string, ok bool) {
	const suffix = ".txt"
	if !strings.HasSuffix(fname, suffix) {
		return "", "", false
	}
	stem := fname[:len(fname)-len(suffix)]
	dot := strings.Index(stem, ".")
	if dot <= 0 {
		// No separator, or a leading dot (no hash) — not our shape.
		return "", "", false
	}
	return stem[:dot], stem[dot+1:], true
}
