package sanitizerfeatures_test

import (
	"strings"
	"testing"

	"github.com/sstriker/buildstream-bazel/converter/internal/configfold"
	"github.com/sstriker/buildstream-bazel/converter/internal/emit/sanitizerfeatures"
)

func TestEmit_EmptyInput(t *testing.T) {
	out := string(sanitizerfeatures.Emit(nil))
	if !strings.Contains(out, "SANITIZER_FEATURES = []") {
		t.Errorf("empty input should produce empty SANITIZER_FEATURES; got:\n%s", out)
	}
	// Header always present.
	if !strings.Contains(out, "Generated by convert-element-cmake") {
		t.Errorf("missing attribution header")
	}
}

func TestEmit_SingleSanitizer(t *testing.T) {
	sets := map[string]configfold.SanitizerFlagSet{
		"ASan": {
			FeatureName: "asan",
			CompileFlags: map[string][]string{
				"C":   {"-fsanitize=address", "-fno-omit-frame-pointer", "-g"},
				"CXX": {"-fsanitize=address", "-fno-omit-frame-pointer", "-g"},
			},
			LinkFlags: []string{"-fsanitize=address"},
		},
	}
	out := string(sanitizerfeatures.Emit(sets))

	// Attribution comment naming the cmake source config.
	if !strings.Contains(out, `Generated from cmake config "ASan"`) {
		t.Errorf("missing per-feature attribution; got:\n%s", out)
	}
	// Feature definition shape.
	if !strings.Contains(out, "asan_feature = feature(") {
		t.Errorf("missing feature definition; got:\n%s", out)
	}
	if !strings.Contains(out, `name = "asan"`) {
		t.Errorf("missing feature name attribute; got:\n%s", out)
	}
	if !strings.Contains(out, "enabled = False") {
		t.Errorf("missing opt-in default; got:\n%s", out)
	}
	// Compile + link actions.
	if !strings.Contains(out, "ACTION_NAMES.c_compile") {
		t.Errorf("missing c_compile action; got:\n%s", out)
	}
	if !strings.Contains(out, "ACTION_NAMES.cpp_compile") {
		t.Errorf("missing cpp_compile action; got:\n%s", out)
	}
	if !strings.Contains(out, "ACTION_NAMES.cpp_link_executable") {
		t.Errorf("missing link action; got:\n%s", out)
	}
	// Exported list at the bottom.
	if !strings.Contains(out, "SANITIZER_FEATURES = [\n    asan_feature,\n]") {
		t.Errorf("missing exported list; got:\n%s", out)
	}
}

func TestEmit_DeterministicOrder(t *testing.T) {
	// Map insertion order is non-deterministic; the emitter
	// orders by feature name so re-runs produce byte-identical
	// output.
	sets := map[string]configfold.SanitizerFlagSet{
		"TSan":     {FeatureName: "tsan", LinkFlags: []string{"-fsanitize=thread"}},
		"ASan":     {FeatureName: "asan", LinkFlags: []string{"-fsanitize=address"}},
		"Coverage": {FeatureName: "coverage", LinkFlags: []string{"--coverage"}},
	}
	out1 := string(sanitizerfeatures.Emit(sets))
	out2 := string(sanitizerfeatures.Emit(sets))
	if out1 != out2 {
		t.Errorf("emit not deterministic")
	}
	// Sorted by feature name: asan < coverage < tsan.
	posAsan := strings.Index(out1, "asan_feature = feature(")
	posCov := strings.Index(out1, "coverage_feature = feature(")
	posTsan := strings.Index(out1, "tsan_feature = feature(")
	if !(posAsan < posCov && posCov < posTsan) {
		t.Errorf("features not in feature-name order: %d %d %d", posAsan, posCov, posTsan)
	}
}

func TestEmit_OmitsLanguageWithoutFlags(t *testing.T) {
	// Only C flags set; CXX should NOT appear as an action.
	sets := map[string]configfold.SanitizerFlagSet{
		"ASan": {
			FeatureName: "asan",
			CompileFlags: map[string][]string{
				"C": {"-fsanitize=address"},
			},
			LinkFlags: []string{"-fsanitize=address"},
		},
	}
	out := string(sanitizerfeatures.Emit(sets))
	if !strings.Contains(out, "ACTION_NAMES.c_compile") {
		t.Errorf("missing c_compile (should be present); got:\n%s", out)
	}
	if strings.Contains(out, "ACTION_NAMES.cpp_compile") {
		t.Errorf("cpp_compile should be absent (no CXX flags); got:\n%s", out)
	}
}

func TestEmit_FlagValueEscaping(t *testing.T) {
	// Quotes inside flags get %q'd correctly.
	sets := map[string]configfold.SanitizerFlagSet{
		"ASan": {
			FeatureName: "asan",
			CompileFlags: map[string][]string{
				"C": {`-DSTR="hello"`},
			},
		},
	}
	out := string(sanitizerfeatures.Emit(sets))
	if !strings.Contains(out, `"-DSTR=\"hello\""`) {
		t.Errorf("flag with quotes not escaped; got:\n%s", out)
	}
}
