// Package sanitizerfeatures emits a cc_toolchain feature .bzl file
// from cmake's CMAKE_<LANG>_FLAGS_<CONFIG> cache entries.
//
// Phase 5 of the generator-parity uplift (ROADMAP.md). The
// generated .bzl file pairs with the operator's cc_toolchain to
// route per-sanitizer flag sets onto --features=<name> opt-in,
// replacing the per-rule select() anti-pattern Phase 7's audit
// catches.
//
// The generated file is byte-stable across runs against the same
// cmake cache and explicitly attributed via a leading header so
// operators know it's converter-derived (versus their own
// hand-edited toolchain features.bzl).
package sanitizerfeatures

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/sstriker/buildstream-bazel/converter/internal/configfold"
)

// Emit renders the sanitizer flag sets as a .bzl file content.
// Caller is responsible for writing to disk.
//
// Empty input returns the file header + an empty SANITIZER_FEATURES
// list so the operator's load() doesn't break when no sanitizer
// configs were converted.
func Emit(sets map[string]configfold.SanitizerFlagSet) []byte {
	var buf bytes.Buffer
	buf.WriteString(header)
	if len(sets) == 0 {
		buf.WriteString("SANITIZER_FEATURES = []\n")
		return buf.Bytes()
	}

	buf.WriteString(loads)
	buf.WriteString("\n")
	buf.WriteString(actionConstants)
	buf.WriteString("\n")

	// Sorted by feature name for byte stability.
	order := configfold.SanitizerConfigOrder(sets)
	for _, cfg := range order {
		emitFeature(&buf, cfg, sets[cfg])
		buf.WriteString("\n")
	}
	// Exported list.
	buf.WriteString("SANITIZER_FEATURES = [\n")
	for _, cfg := range order {
		fmt.Fprintf(&buf, "    %s_feature,\n", sets[cfg].FeatureName)
	}
	buf.WriteString("]\n")
	return buf.Bytes()
}

// emitFeature renders one feature() definition.
//
// Compile flag_sets emit one per language (C, CXX, ASM) — Bazel's
// action_name split mirrors cmake's per-language CMAKE_<LANG>_FLAGS
// keying. Languages with no flags omit the flag_set entirely (vs
// emitting an empty flag_group, which would clutter the output).
//
// Link flag_set emits once with all three link action names so the
// flags apply to executables, dynamic libraries, and nodeps
// dynamic libraries uniformly.
func emitFeature(buf *bytes.Buffer, cmakeName string, set configfold.SanitizerFlagSet) {
	fmt.Fprintf(buf, "# Generated from cmake config %q.\n", cmakeName)
	fmt.Fprintf(buf, "%s_feature = feature(\n", set.FeatureName)
	fmt.Fprintf(buf, "    name = %q,\n", set.FeatureName)
	buf.WriteString("    enabled = False,  # opt-in via --features=" + set.FeatureName + "\n")
	buf.WriteString("    flag_sets = [\n")

	// Per-language compile flag_sets in deterministic order.
	langs := make([]string, 0, len(set.CompileFlags))
	for l := range set.CompileFlags {
		langs = append(langs, l)
	}
	sort.Strings(langs)
	for _, lang := range langs {
		flags := set.CompileFlags[lang]
		if len(flags) == 0 {
			continue
		}
		actions := compileActions(lang)
		if len(actions) == 0 {
			continue
		}
		emitFlagSet(buf, actions, flags)
	}
	// Link flag_set.
	if len(set.LinkFlags) > 0 {
		emitFlagSet(buf, linkActions(), set.LinkFlags)
	}
	buf.WriteString("    ],\n")
	buf.WriteString(")\n")
}

func emitFlagSet(buf *bytes.Buffer, actions, flags []string) {
	buf.WriteString("        flag_set(\n")
	buf.WriteString("            actions = [\n")
	for _, a := range actions {
		fmt.Fprintf(buf, "                %s,\n", a)
	}
	buf.WriteString("            ],\n")
	buf.WriteString("            flag_groups = [flag_group(flags = [\n")
	for _, f := range flags {
		fmt.Fprintf(buf, "                %q,\n", f)
	}
	buf.WriteString("            ])],\n")
	buf.WriteString("        ),\n")
}

// compileActions maps a cmake language to the matching
// ACTION_NAMES.* constants. C drives both c_compile + assemble
// since cmake's CMAKE_C_FLAGS covers .S preprocessing in some
// projects; ASM gets its own action set explicitly.
func compileActions(lang string) []string {
	switch strings.ToUpper(lang) {
	case "C":
		return []string{"ACTION_NAMES.c_compile"}
	case "CXX":
		return []string{
			"ACTION_NAMES.cpp_compile",
			"ACTION_NAMES.cpp_module_compile",
		}
	case "ASM":
		return []string{
			"ACTION_NAMES.assemble",
			"ACTION_NAMES.preprocess_assemble",
		}
	}
	return nil
}

func linkActions() []string {
	return []string{
		"ACTION_NAMES.cpp_link_executable",
		"ACTION_NAMES.cpp_link_dynamic_library",
		"ACTION_NAMES.cpp_link_nodeps_dynamic_library",
	}
}

const header = `# Generated by convert-element-cmake. DO NOT EDIT.
#
# Sanitizer cc_toolchain features extracted from cmake's
# CMAKE_<LANG>_FLAGS_<CONFIG> cache entries for every
# sanitizer-shaped configuration the operator passed via
# --build-types. Operators thread SANITIZER_FEATURES into
# cc_common.create_cc_toolchain_config_info(... features = ...)
# to opt-in via --features=<name>.
#
# Drop-in shape: this file is byte-stable across runs against the
# same cmake cache. Re-generated whenever the operator runs
# convert-element-cmake --out-sanitizer-features=<path>; manual
# edits will be overwritten. To customize beyond what cmake
# records, copy the SANITIZER_FEATURES list into your own
# features.bzl and edit there.
#
# See examples/sanitizer-features/README.md for the convention.

`

const loads = `load("@bazel_tools//tools/build_defs/cc:action_names.bzl", "ACTION_NAMES")
load(
    "@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl",
    "feature",
    "flag_group",
    "flag_set",
)
`

const actionConstants = `# Compile / link action sets each feature instruments.
# Inlined here rather than imported because Bazel's
# cc_toolchain_config_lib does not export aggregate slices.
`
