// Package bazel emits a BUILD.bazel file from the IR.
//
// M1 uses text/template for stable, easy-to-diff output and zero external
// deps. The plan calls for a buildtools-AST spike in week 1; if it's adopted,
// it replaces the template here without changing the Emit signature.
//
// Output is deterministic: every list attribute is sorted before emission.
package bazel

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/bazelbuild/buildtools/build"
	"github.com/sstriker/buildstream-bazel/converter/internal/bazelconstraints"
	"github.com/sstriker/buildstream-bazel/converter/internal/failure"
	"github.com/sstriker/buildstream-bazel/converter/ir"
)

// header is intentionally path-free so the emitted BUILD.bazel is
// byte-identical across runs, machines, and per-orchestration tmpdirs.
// The element / codebase the file belongs to is implicit in its
// on-disk location (out/elements/<name>/BUILD.bazel for orchestrator
// runs; whatever --out-build the operator passed for standalone runs).
const header = `# Generated by convert-element-cmake. DO NOT EDIT.

`

// ccRuleLoads maps each Kind to its rules_cc load symbol. Bazel 9
// removed cc_library/cc_binary/cc_import from the global namespace;
// every emitted BUILD.bazel using one of these rules must `load()`
// it explicitly. Older Bazels accept the load + load-less form alike.
var ccRuleLoads = map[ir.Kind]string{
	ir.KindCCLibrary:   "cc_library",
	ir.KindCCBinary:    "cc_binary",
	ir.KindCCImport:    "cc_import",
	ir.KindCCInterface: "cc_library",
	ir.KindCCTest:      "cc_test",
}

// emitPackageDefaultVisibility writes the file-head
// `package(default_visibility = ["//visibility:public"])` line
// that every generated BUILD carries. Gazelle / gazelle_cc
// canon: visibility is set once at the package level and
// per-rule `visibility` is emitted only when overriding the
// default. The corresponding per-rule suppression lives in
// nonDefaultVisibility (called from each ccView/ccImportView/
// shBinaryView/genruleView constructor), which drops the
// public default from each target's emitted attributes.
//
// This pairs with the per-rule logic: visibility set on a
// target that equals the package default is omitted from the
// emitted rule; a target with a different visibility (e.g.
// `//visibility:private` or a specific package_group) still
// emits its own visibility line, which Bazel treats as the
// override per the standard precedence.
func emitPackageDefaultVisibility(buf *bytes.Buffer) {
	buf.WriteString(`package(default_visibility = ["//visibility:public"])` + "\n\n")
}

// emitProvenanceComment writes a leading `# Source: <file>:<line>
// (<command>)` comment above the next emitted rule. Phase 1
// task 1 of the generator-parity uplift — the backtrace-derived
// annotation that tells the operator which cmake call site
// declared the target.
//
// File / Line / Command are written verbatim. The buildtools
// canonicalize pass preserves leading comments attached to rule
// calls, so the comment survives the formatter round-trip.
func emitProvenanceComment(buf *bytes.Buffer, p ir.Provenance) {
	buf.WriteString("# Source: ")
	buf.WriteString(p.File)
	if p.Line > 0 {
		buf.WriteString(":")
		buf.WriteString(itoa(p.Line))
	}
	if p.Command != "" {
		buf.WriteString(" (")
		buf.WriteString(p.Command)
		buf.WriteString(")")
	}
	buf.WriteString("\n")
}

// itoa is a tiny non-fmt int-to-string helper for the per-rule
// provenance comment's hot path. Avoids pulling fmt into emit's
// per-target loop.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var b [20]byte
	i := len(b)
	for n > 0 {
		i--
		b[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		b[i] = '-'
	}
	return string(b[i:])
}

// defaultPublicVisibility is the package-level default emitted
// by emitPackageDefaultVisibility. Per-rule Visibility slices
// matching this exact list are suppressed by
// nonDefaultVisibility — the package default already covers
// them and a duplicate per-rule line would be noise that
// `gazelle fix` would later remove.
var defaultPublicVisibility = []string{"//visibility:public"}

// nonDefaultVisibility returns vis verbatim when it represents
// an override of the package-level default
// (//visibility:public), and nil when vis equals the package
// default. Centralizing the comparison here means every view
// constructor (ccView, ccImportView, shBinaryView,
// genruleView) emits the same elision policy without each
// having to spell out the public-default literal.
//
// vis is returned as a fresh slice in the override case so the
// caller can mutate freely without aliasing the IR-side
// Visibility slice; the IR is read-only from emit's
// perspective.
func nonDefaultVisibility(vis []string) []string {
	if len(vis) == len(defaultPublicVisibility) {
		match := true
		for i, v := range vis {
			if v != defaultPublicVisibility[i] {
				match = false
				break
			}
		}
		if match {
			return nil
		}
	}
	if len(vis) == 0 {
		return nil
	}
	return append([]string(nil), vis...)
}

// emitGazelleCcSearch writes `# gazelle:cc_search "" <pkgpath>/<dir>`
// file-head directives mirroring the union of every target's
// `includes` attribute values. Per ROADMAP.md
// Phase 7d: gazelle_cc's header-scan resolver needs the same
// include search paths the converter extracted from CMake so an
// operator-added unqualified `#include "X"` of an in-tree header
// resolves to the right label on `gazelle fix`.
//
// Frame mismatch the two-arg shape fixes: `cc_library.includes`
// is package-relative ("include" → `-I <pkgpath>/include` at
// compile time), whereas gazelle_cc's `cc_search` directive
// takes (<strip_include_prefix>, <include_prefix>) pairs
// interpreted **repo-root relative**, where `gazelle_cc` prepends
// `<include_prefix>` to the include text and looks the result up
// in `cc_index.json`. The directive that gives gazelle_cc the
// same name-resolution view the `-I <pkgpath>/include` flag
// gives the compiler is `# gazelle:cc_search "" <pkgpath>/include`
// — strip nothing, prepend the package-rooted include dir.
// The single-arg form we previously emitted left the second arg
// empty, which gazelle_cc treats as "strip leading <arg>/ from
// the include and look at the repo root" — wrong semantics.
//
// Inert when opts.BazelPackagePath is empty (the directive can't
// be correctly framed without the repo-relative package path) or
// when no target carries `includes`. Tests that don't care about
// gazelle_cc resolution pass the zero-value Options and get no
// directive, keeping their goldens shape-pure.
func emitGazelleCcSearch(buf *bytes.Buffer, pkg *ir.Package, opts Options) {
	if opts.BazelPackagePath == "" {
		return
	}
	seen := map[string]struct{}{}
	var dirs []string
	for _, t := range pkg.Targets {
		for _, d := range t.Includes {
			if _, ok := seen[d]; ok {
				continue
			}
			seen[d] = struct{}{}
			dirs = append(dirs, d)
		}
	}
	if len(dirs) == 0 {
		return
	}
	sort.Strings(dirs)
	pkgPath := strings.Trim(opts.BazelPackagePath, "/")
	for _, d := range dirs {
		// Join package path + include dir using the same
		// slash-rooted form gazelle_cc expects. Skip leading
		// "./" or "/" on the include dir for cleanliness; CMake
		// includes are normally simple package-relative names
		// ("include", "src") but defend against the occasional
		// "./include" the lower path might produce.
		rel := strings.TrimPrefix(strings.TrimPrefix(d, "./"), "/")
		// A "." include dir (the split-packages synthesized header
		// lib's own-package include) means "this package's root" —
		// emit the package path alone rather than "<pkg>/." so the
		// directive reads cleanly and gazelle_cc resolves it to the
		// package, not a literal "." subdir.
		if rel == "." || rel == "" {
			fmt.Fprintf(buf, "# gazelle:cc_search \"\" %s\n", pkgPath)
			continue
		}
		fmt.Fprintf(buf, "# gazelle:cc_search \"\" %s/%s\n", pkgPath, rel)
	}
	buf.WriteString("\n")
}

// emitLoad writes a single `load("@rules_cc//cc:defs.bzl", ...)` line
// covering every cc_* symbol used by pkg's targets. Symbols are sorted
// for byte-stability. Returns nothing if pkg has no cc_* targets.
func emitLoad(buf *bytes.Buffer, pkg *ir.Package) {
	used := map[string]struct{}{}
	for _, t := range pkg.Targets {
		if sym, ok := ccRuleLoads[t.Kind]; ok {
			used[sym] = struct{}{}
		}
	}
	if len(used) == 0 {
		return
	}
	syms := make([]string, 0, len(used))
	for s := range used {
		syms = append(syms, s)
	}
	sort.Strings(syms)
	buf.WriteString(`load("@rules_cc//cc:defs.bzl"`)
	for _, s := range syms {
		fmt.Fprintf(buf, ", %q", s)
	}
	buf.WriteString(")\n\n")
}

// emitInstallLoad writes the
// `load("@rules_buildstream_bazel//rules:install.bzl", "pick_file")`
// line when pkg emits any pick_file target (the round-2
// execute-process fallback shape). No-op otherwise so the cc-only
// BUILD output stays byte-stable.
func emitInstallLoad(buf *bytes.Buffer, pkg *ir.Package) {
	for _, t := range pkg.Targets {
		if t.Kind == ir.KindPickFile {
			buf.WriteString(`load("@rules_buildstream_bazel//rules:install.bzl", "pick_file")` + "\n\n")
			return
		}
	}
}

// emitPkgFilesLoad writes the
// `load("@rules_pkg//pkg:mappings.bzl", "pkg_files")` line when pkg
// emits any pkg_files target (the install(FILES)/install(DIRECTORY)
// declarative-packaging shape, Phase 1 slice 1b). No-op otherwise so
// the cc-only / filegroup-only BUILD output stays byte-stable — an
// element with no install(FILES) emits no rules_pkg load and the
// consuming MODULE.bazel needs no rules_pkg bazel_dep. The
// corresponding write-a-side dep wiring lives in moduleBazelB.
func emitPkgFilesLoad(buf *bytes.Buffer, pkg *ir.Package) {
	hasPkgFiles := false
	hasStripPrefix := false
	for _, t := range pkg.Targets {
		if t.Kind != ir.KindPkgFiles {
			continue
		}
		hasPkgFiles = true
		// The install(DIRECTORY) glob shape renders
		// `strip_prefix.from_pkg(...)`, which needs the `strip_prefix`
		// symbol loaded alongside `pkg_files`. install(FILES) targets
		// (literal srcs list, no strip_prefix) don't, so a FILES-only
		// BUILD keeps the single-symbol load — preserving the
		// file-case output byte-for-byte.
		if t.PkgSrcsGlob && t.PkgStripPrefix != "" {
			hasStripPrefix = true
		}
	}
	if !hasPkgFiles {
		return
	}
	if hasStripPrefix {
		buf.WriteString(`load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")` + "\n\n")
		return
	}
	buf.WriteString(`load("@rules_pkg//pkg:mappings.bzl", "pkg_files")` + "\n\n")
}

// Options tunes the BUILD.bazel emission. Zero-value Options
// preserves the legacy relative-path emission.
type Options struct {
	// SourceKey, when non-empty, prefixes every source path in
	// emitted cc_library/cc_binary/cc_test `srcs = [...]` with
	// "@src_<SourceKey>//:" so project B references the bytes
	// by digest-stable Bazel label rather than by local
	// filesystem path. Used by the FUSE-sources route to keep
	// project B's compile actions BwoB without a project-B-side
	// FUSE mount of its own.
	SourceKey string

	// Header overrides the default "# Generated by
	// convert-element-cmake. DO NOT EDIT.\n\n" file-head comment.
	// Multiple cmd/* binaries share this emitter (convert-
	// element / convert-element-meson / convert-element-trace
	// / fold-element); each can attribute its own output via
	// Header so the operator-visible provenance comment names
	// the actual binary that produced the file. Must end with
	// a trailing "\n\n" if the caller wants a blank line
	// separating the header from the rest of the BUILD; this
	// field is appended verbatim to the buffer.
	Header string

	// BazelPackagePath is the repo-root-relative path of the
	// Bazel package the emitted BUILD.bazel lives in (e.g.
	// "elements/hello-world"). Used to frame the
	// `# gazelle:cc_search "" <pkgpath>/<include>` directives so
	// gazelle_cc's header-scan resolver sees the same include
	// search paths the converter extracted from CMake.
	// gazelle_cc interprets `cc_search` arguments repo-root
	// relative, whereas `cc_library.includes` is package-relative
	// — without the package-path frame the directive points at
	// the wrong place. Empty value (zero Options) suppresses the
	// directive entirely, which is the right shape for unit
	// tests that don't care about gazelle_cc resolution.
	BazelPackagePath string

	// EmitProvenance enables Phase 1 task 1's backtrace-derived
	// per-rule annotation: when true, each rule whose Target has
	// a non-zero Provenance gets a leading
	// `# Source: <file>:<line> (<command>)` comment. Operators
	// use the annotation to navigate "why does this Bazel target
	// exist?" without re-running the converter.
	//
	// Off by default — comments change BUILD output bytes and
	// would invalidate every existing golden if always-on. CLI
	// surface via `convert-element-cmake --emit-provenance`.
	EmitProvenance bool
}

// Emit returns the contents of a BUILD.bazel file for pkg using
// default Options.
func Emit(pkg *ir.Package) ([]byte, error) {
	return EmitWithOptions(pkg, Options{})
}

// EmitWithOptions is the configurable form of Emit.
//
// The emitter constructs each rule via the in-package text
// templates and then routes the assembled output through
// `bazel.build/buildtools/build`'s Parse + Format pipeline —
// the same pipeline `buildifier --mode=fix` uses. That gives
// project B the Phase 3 contract from
// ROADMAP.md: `buildifier
// --mode=fix` against our generated BUILDs is a no-op (we
// emit what buildifier would produce). Side effect: attribute
// order pulls from buildtools' `tables.NamePriority` rather
// than the template's manual order, so the rendered shape
// matches what an operator hand-formatting via buildifier
// would see post-conversion.
func EmitWithOptions(pkg *ir.Package, opts Options) ([]byte, error) {
	// Pre-emit constraint pass. Catches the small set of
	// Bazel-side semantic violations that have produced real
	// operator bugs (empty genrule cmd #193, duplicate deps
	// #194, malformed rule names) before they hit disk. See
	// converter/internal/bazelconstraints for the constraint
	// list and the rationale per check.
	if err := bazelconstraints.ValidatePackage(pkg); err != nil {
		return nil, fmt.Errorf("bazel constraint violation: %w", err)
	}
	var buf bytes.Buffer
	if opts.Header != "" {
		buf.WriteString(opts.Header)
	} else {
		buf.WriteString(header)
	}
	// Package-level header comments — find_package resolutions
	// and other attribution data the lifter wants to surface.
	// Collapse any embedded newlines / carriage returns to spaces
	// so a multi-line cmake HELPSTRING (LLVM's
	// `option(LLVM_BUILD_BENCHMARKS "Add ...\ntargets. If OFF
	// ...")` shape) doesn't break the comment block by emitting an
	// unprefixed continuation line that Bazel parses as bare
	// syntax. Producers in lower/ aren't aware of this constraint;
	// the emit-side scrub keeps every producer safe by
	// construction.
	for _, line := range pkg.HeaderComments {
		buf.WriteString("# ")
		buf.WriteString(collapseToSingleLine(line))
		buf.WriteString("\n")
	}
	if len(pkg.HeaderComments) > 0 {
		buf.WriteString("\n")
	}
	emitGazelleCcSearch(&buf, pkg, opts)
	emitLoad(&buf, pkg)
	emitInstallLoad(&buf, pkg)
	emitPkgFilesLoad(&buf, pkg)
	emitWriteFileLoad(&buf, pkg)
	emitBoolFlagLoad(&buf, pkg)
	emitCMakeConfigureFileLoad(&buf, pkg)
	emitPackageDefaultVisibility(&buf)

	for i, t := range pkg.Targets {
		if i > 0 {
			buf.WriteString("\n")
		}
		if opts.EmitProvenance && !t.Provenance.IsZero() {
			emitProvenanceComment(&buf, t.Provenance)
		}
		if t.Kind == ir.KindGenrule {
			if err := emitGenrule(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindCCImport {
			if err := emitCCImport(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindShBinary {
			if err := emitShBinary(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindPickFile {
			if err := emitPickFile(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindFilegroup {
			if err := emitFilegroup(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindPkgFiles {
			if err := emitPkgFiles(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindAlias {
			if err := emitAlias(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindWriteFile {
			if err := emitWriteFile(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindCMakeConfigureFile {
			if err := emitCMakeConfigureFile(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindBoolFlag {
			if err := emitBoolFlag(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindConfigSetting {
			if err := emitConfigSetting(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if err := emitCCTargetWithOptions(&buf, t, opts); err != nil {
			return nil, err
		}
	}
	return canonicalize(buf.Bytes())
}

// canonicalize routes the template-assembled BUILD text
// through buildtools' Parse + Format pipeline so the final
// output matches what `buildifier --mode=fix` would produce.
// Attribute order pulls from `tables.NamePriority`; list
// wrapping, quote normalization, and load() symbol sorting
// fall out of the formatter's default Rewriter pass.
//
// We use a synthetic filename ending in `BUILD.bazel` so
// buildtools parses with TypeBuild semantics (it dispatches
// off the path basename). The bytes never touch disk; the
// name is purely a parse-mode hint.
//
// On a parse error we return a typed Tier-1 `*failure.Error`
// with code `BazelCanonicalizeFailed` carrying both the
// buildtools diagnostic and the offending body. The typed
// failure means convert-element-cmake's handleError surfaces
// the operator-friendly failure.json without per-caller
// wrapping — keeping the typed-code contract LOCAL to the
// failure site so a future emit-side error of a different
// shape (e.g. a new constraint check) doesn't inherit the
// `bazel-canonicalize-failed` label by mistake.
//
// Test code that drives canonicalize directly (see
// `keep_markers_test`) sees the same typed error and can
// match on `failure.BazelCanonicalizeFailed`. The pre-#210
// shape — an uncaught panic — silently broke the
// buildifier-no-op contract without a test-visible trigger;
// the typed return surfaces it loudly in both unit tests
// and production paths.
func canonicalize(body []byte) ([]byte, error) {
	f, err := build.Parse("BUILD.bazel", body)
	if err != nil {
		return nil, failure.New(failure.BazelCanonicalizeFailed,
			"bazel.canonicalize: template emitted unparseable BUILD bytes: %v\n%s", err, body)
	}
	addKeepMarkers(f)
	return build.Format(f), nil
}

// addKeepMarkers walks every rule in f and tags load-bearing
// attribute lines (and whole rules, for genrule / filegroup)
// with `# keep` comments. Per docs/design/build-output-
// conventions.md's Phase 7a roundtrip spec: these markers
// prevent a downstream `gazelle fix` run from rewriting
// values the converter extracted from CMake/Meson/trace —
// signals gazelle wouldn't be able to re-derive from
// post-conversion sources alone.
//
// The marker scope follows the conventions doc's table:
//
//   - cc_library / cc_binary / cc_test: copts, defines,
//     linkopts, includes, tags, linkstatic, alwayslink,
//     include_prefix, strip_include_prefix.
//   - cc_test additionally: args, env, timeout, data.
//   - cc_import + alias + pkg_files: whole-rule keep. gazelle /
//     gazelle_cc can't regenerate install-export imports (the
//     round-2 fallback's library exports), aliases, or the
//     install(FILES)/install(DIRECTORY)-derived pkg_files
//     packaging rules from post-conversion sources, so a
//     rule-level keep is the only scope that survives a gazelle
//     maintenance pass — an attribute-level keep leaves the rule
//     itself a deletion candidate when gazelle finds no source to
//     back it.
//   - genrule + filegroup: whole-rule keep (closing-paren
//     suffix comment).
//   - package(...): whole-rule keep.
//
// The marker doesn't trigger when gazelle isn't installed —
// it's an inert # comment to any tool that doesn't look for
// it. Phase 3's buildifier-canonical contract is preserved:
// buildifier honors the keep markers and doesn't reformat
// the tagged lines.
func addKeepMarkers(f *build.File) {
	for _, stmt := range f.Stmt {
		call, ok := stmt.(*build.CallExpr)
		if !ok {
			continue
		}
		kind := callRuleKind(call)
		switch kind {
		case "genrule", "filegroup", "package", "cc_import", "alias", "pkg_files", "write_file", "cmake_configure_file":
			markCallKeep(call)
		case "cc_library", "cc_binary", "cc_test":
			if kind == "cc_library" && callHasTag(call, generatedHeadersTag) {
				// The fully synthesized generated-header wrapper has no
				// on-disk srcs for gazelle to reconcile it against — a
				// maintenance pass would delete it. Whole-rule keep pins it.
				// Keyed on the tag, not the name, so a user rule that shares
				// the name is left for gazelle to manage.
				markCallKeep(call)
			} else {
				markAttrsKeep(call, ccKeepAttrs(kind))
				markGeneratedHeaderDeps(call)
			}
		}
	}
}

// callHasTag reports whether a rule call's `tags` attribute (a plain list
// literal) contains tag. Used to recognize converter-synthesized rules by
// their tag rather than a collidable name.
func callHasTag(call *build.CallExpr, tag string) bool {
	for _, arg := range call.List {
		assign, ok := arg.(*build.AssignExpr)
		if !ok {
			continue
		}
		ident, ok := assign.LHS.(*build.Ident)
		if !ok || ident.Name != "tags" {
			continue
		}
		list, ok := assign.RHS.(*build.ListExpr)
		if !ok {
			continue
		}
		for _, item := range list.List {
			if str, ok := item.(*build.StringExpr); ok && str.Value == tag {
				return true
			}
		}
	}
	return false
}

// callRuleKind returns the rule kind for a CallExpr (e.g.
// "cc_library", "genrule") or "" if the call's function
// position isn't a bare identifier. Top-level BUILD calls
// are typically Ident-headed; load() is the exception (it's
// an Ident but routed elsewhere via stmt type).
func callRuleKind(call *build.CallExpr) string {
	if ident, ok := call.X.(*build.Ident); ok {
		return ident.Name
	}
	return ""
}

// markCallKeep appends a `# keep` suffix comment to the
// CallExpr itself. The formatter renders this on the line
// of the closing `)` of the call.
func markCallKeep(call *build.CallExpr) {
	if hasKeepSuffix(call.Comment().Suffix) {
		return
	}
	call.Comment().Suffix = append(call.Comment().Suffix, build.Comment{Token: "# keep"})
}

// markAttrsKeep walks the call's positional/keyword args
// and tags each AssignExpr whose LHS is one of attrNames
// with a `# keep` suffix.
func markAttrsKeep(call *build.CallExpr, attrNames map[string]bool) {
	if len(attrNames) == 0 {
		return
	}
	for _, arg := range call.List {
		assign, ok := arg.(*build.AssignExpr)
		if !ok {
			continue
		}
		ident, ok := assign.LHS.(*build.Ident)
		if !ok {
			continue
		}
		if !attrNames[ident.Name] {
			continue
		}
		if hasKeepSuffix(assign.Comment().Suffix) {
			continue
		}
		assign.Comment().Suffix = append(assign.Comment().Suffix, build.Comment{Token: "# keep"})
	}
}

// markGeneratedHeaderDeps tags each `deps` list item that references a
// synthesized generated-header wrapper library (label suffix
// `:generated_headers`, see split.go's generatedHeadersName) with a
// per-item `# keep`. gazelle's cc extension resolves deps from #include
// directives; it can't resolve a generated `.inc` to the wrapper (the file
// isn't on disk at gazelle time), so without the marker a maintenance pass
// would strip the edge. Per-item (not whole-attr) so gazelle still manages
// the consumer's ordinary, resolvable deps.
func markGeneratedHeaderDeps(call *build.CallExpr) {
	for _, arg := range call.List {
		assign, ok := arg.(*build.AssignExpr)
		if !ok {
			continue
		}
		ident, ok := assign.LHS.(*build.Ident)
		if !ok || ident.Name != "deps" {
			continue
		}
		list, ok := assign.RHS.(*build.ListExpr)
		if !ok {
			continue
		}
		for _, item := range list.List {
			str, ok := item.(*build.StringExpr)
			if !ok {
				continue
			}
			if !strings.HasSuffix(str.Value, ":"+generatedHeadersName) {
				continue
			}
			if hasKeepSuffix(str.Comment().Suffix) {
				continue
			}
			str.Comment().Suffix = append(str.Comment().Suffix, build.Comment{Token: "# keep"})
		}
	}
}

// hasKeepSuffix reports whether the comment slice already
// contains a `# keep` marker. Used to make addKeepMarkers
// idempotent — calling canonicalize twice on the same body
// (e.g. round-tripping through write-a's BUILD.bazel
// canonicalize plus the embedded one here) doesn't double
// up markers.
func hasKeepSuffix(comments []build.Comment) bool {
	for _, c := range comments {
		if strings.TrimSpace(c.Token) == "# keep" {
			return true
		}
	}
	return false
}

// ccKeepAttrs returns the set of attribute names that
// receive `# keep` markers for a cc_* rule kind. cc_test
// gets the cc_library set plus its test-only attributes.
func ccKeepAttrs(kind string) map[string]bool {
	base := map[string]bool{
		"copts":                true,
		"defines":              true,
		"linkopts":             true,
		"includes":             true,
		"tags":                 true,
		"linkstatic":           true,
		"alwayslink":           true,
		"include_prefix":       true,
		"strip_include_prefix": true,
		// textual_hdrs are x-macro / generated `.inc` fragments gazelle's
		// cc extension can't resolve from disk (a tablegen output isn't
		// present at gazelle time); keep them so a maintenance pass doesn't
		// strip the generated-header wrapper's contents.
		"textual_hdrs": true,
	}
	if kind == "cc_test" {
		base["args"] = true
		base["env"] = true
		base["timeout"] = true
		base["data"] = true
	}
	return base
}

var ccRuleTmpl = template.Must(template.New("rule").Funcs(template.FuncMap{
	"strList": strList,
	"strDict": strDict,
}).Parse(`{{.RuleKind}}(
    name = "{{.Name}}",
{{- if .SrcsExpr}}
    srcs = {{.SrcsExpr}},
{{- end}}
{{- if .HdrsExpr}}
    hdrs = {{.HdrsExpr}},
{{- end}}
{{- if .TextualHdrsExpr}}
    textual_hdrs = {{.TextualHdrsExpr}},
{{- end}}
{{- if .IncludesExpr}}
    includes = {{.IncludesExpr}},
{{- end}}
{{- if .IncludePrefix}}
    include_prefix = "{{.IncludePrefix}}",
{{- end}}
{{- if .StripIncludePrefix}}
    strip_include_prefix = "{{.StripIncludePrefix}}",
{{- end}}
{{- if .CoptsExpr}}
    copts = {{.CoptsExpr}},
{{- end}}
{{- if .DefinesExpr}}
    defines = {{.DefinesExpr}},
{{- end}}
{{- if .LocalDefinesExpr}}
    local_defines = {{.LocalDefinesExpr}},
{{- end}}
{{- if .LinkoptsExpr}}
    linkopts = {{.LinkoptsExpr}},
{{- end}}
{{- if .AdditionalLinkerInputsExpr}}
    additional_linker_inputs = {{.AdditionalLinkerInputsExpr}},
{{- end}}
{{- if .DepsExpr}}
    deps = {{.DepsExpr}},
{{- end}}
{{- if .ImplementationDepsExpr}}
    implementation_deps = {{.ImplementationDepsExpr}},
{{- end}}
{{- if .Data}}
    data = {{strList .Data}},
{{- end}}
{{- if .Args}}
    args = {{strList .Args}},
{{- end}}
{{- if .Env}}
    env = {{strDict .Env}},
{{- end}}
{{- if .Timeout}}
    timeout = "{{.Timeout}}",
{{- end}}
{{- if .Linkstatic}}
    linkstatic = True,
{{- end}}
{{- if .Alwayslink}}
    alwayslink = True,
{{- end}}
{{- if .Features}}
    features = {{strList .Features}},
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// ccImportTmpl renders cc_import. Distinct from the generic
// cc_library / cc_binary template because cc_import's
// attribute set is fundamentally different — it wraps a
// pre-built archive / shared object (StaticLibrary /
// SharedLibrary as single-file label refs) plus optional hdrs;
// no srcs / copts / defines / deps. The *Expr fields are
// pre-rendered strings: a quoted path literal when every cell
// agrees, or a `select({...})` block when elementfold's per-
// platform fold populated PerPlatformScalar (round-2 fallback
// path attrs diverge between linux multiarch lib dirs and
// darwin .dylib paths).
var ccImportTmpl = template.Must(template.New("cc_import").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`cc_import(
    name = "{{.Name}}",
{{- if .StaticLibraryExpr}}
    static_library = {{.StaticLibraryExpr}},
{{- end}}
{{- if .SharedLibraryExpr}}
    shared_library = {{.SharedLibraryExpr}},
{{- end}}
{{- if .HdrsExpr}}
    hdrs = {{.HdrsExpr}},
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// shBinaryTmpl renders sh_binary. Bazel's sh_binary expects a
// single-element srcs (the executable) — no hdrs, no copts.
// Used by the kind:cmake round-2 fallback's per-target stubs
// for EXECUTABLE targets, where the placeholder references
// the installed binary path directly. SrcsExpr is the pre-
// rendered list expression — flat literal when single-platform,
// `select({...})` (or `[…] + select({...})`) when elementfold
// populated PerPlatform["srcs"] for the round-2 multi-platform
// fan-out (where the install root's binary path is
// arch-tagged on some platforms).
var shBinaryTmpl = template.Must(template.New("sh_binary").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`sh_binary(
    name = "{{.Name}}",
    srcs = {{.SrcsExpr}},
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// filegroupTmpl renders filegroup. Bazel-native rule (no load
// needed) used by the cmake converter's install(FILES) /
// install(DIRECTORY) lowering (Phase 1 task 2 of the
// generator-parity uplift). SrcsExpr is pre-rendered as a
// list expression or select() expression, same shape as
// ccView srcs handling.
var filegroupTmpl = template.Must(template.New("filegroup").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`filegroup(
    name = "{{.Name}}",
    srcs = {{.SrcsExpr}},
{{- if .OutputGroup}}
    output_group = "{{.OutputGroup}}",
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// pkgFilesTmpl renders rules_pkg's
// `pkg_files(name=, srcs=[...], prefix="<dest>")`. Used by the cmake
// converter's install(FILES)/install(DIRECTORY) lowering (Phase 1
// slice 1b). Needs the @rules_pkg//pkg:mappings.bzl load
// (emitPkgFilesLoad). SrcsExpr is pre-rendered as a list expression
// (the install(FILES)/install(DIRECTORY) lower never produces
// per-platform deltas, so it's always a flat list literal in
// practice — the attrExpr path is reused for shape consistency). The
// prefix attribute is omitted when empty so a destination-less
// installer (skipped upstream, but defensive) renders a valid rule.
var pkgFilesTmpl = template.Must(template.New("pkg_files").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`pkg_files(
    name = "{{.Name}}",
    srcs = {{.SrcsExpr}},
{{- if .Prefix}}
    prefix = "{{.Prefix}}",
{{- end}}
{{- if .StripPrefixExpr}}
    strip_prefix = {{.StripPrefixExpr}},
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// writeFileTmpl renders bazel_skylib's
// `write_file(name=, out=, content=[...], newline="unix")`. Used by
// the file(GENERATE) bake tier to carry fully-resolved bodies as a
// human-readable line list instead of the legacy
// `echo <base64> | base64 -d` genrule. Needs the
// @bazel_skylib//rules:write_file.bzl load (emitWriteFileLoad).
var writeFileTmpl = template.Must(template.New("write_file").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`write_file(
    name = "{{.Name}}",
    out = "{{.Out}}",
    content = {{strList .Content}},
    newline = "{{.Newline}}",
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// pickFileTmpl renders the rules_buildstream_bazel `pick_file()`
// rule. Projects one file out of a pipeline_install install-root
// TreeArtifact (the round-2 fallback's per-artefact / per-header
// stub mechanism). Needs the install.bzl load (emitInstallLoad).
var pickFileTmpl = template.Must(template.New("pick_file").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`pick_file(
    name = "{{.Name}}",
    src = "{{.Src}}",
    path = "{{.Path}}",
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// aliasTmpl renders Bazel-native `alias()`. Lifts cmake's
// `add_library(<alias> ALIAS <target>)` shape recovered from the
// trace; emitted via lowerAliasTargets. No load() needed; alias
// is in the global Bazel namespace.
var aliasTmpl = template.Must(template.New("alias").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`alias(
    name = "{{.Name}}",
    actual = "{{.Actual}}",
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

var genruleTmpl = template.Must(template.New("genrule").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`genrule(
    name = "{{.Name}}",
{{- if .Srcs}}
    srcs = {{strList .Srcs}},
{{- end}}
    outs = {{strList .Outs}},
    cmd = {{.CmdLiteral}},
{{- if .Tools}}
    tools = {{strList .Tools}},
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// cmakeConfigureFileTmpl renders the rules_buildstream_bazel
// `cmake_configure_file()` rule — the configure_file / file(GENERATE)
// lift tier. Needs the cmake_configure_file.bzl load
// (emitCMakeConfigureFileLoad). The substitution inputs ride as readable
// attributes (values / genex_values dicts, genex_context JSON, inline
// content) rather than base64-in-shell. canonicalize() reformats the
// emitted dict / string literals, so this template only has to get the
// attribute set and omission rules right.
var cmakeConfigureFileTmpl = template.Must(template.New("cmake_configure_file").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`cmake_configure_file(
    name = "{{.Name}}",
    out = "{{.Out}}",
{{- if .Template}}
    template = "{{.Template}}",
{{- else}}
    content = {{.ContentLiteral}},
{{- end}}
    values = {{.Values}},
{{- if .StampValues}}
    stamp_values = {{.StampValues}},
{{- end}}
{{- if .GenexValues}}
    genex_values = {{.GenexValues}},
{{- end}}
{{- if .GenexContext}}
    genex_context = {{.GenexContextLiteral}},
{{- end}}
{{- if .TargetFiles}}
    target_files = {{.TargetFiles}},
{{- end}}
{{- if .TargetObjects}}
    target_objects = {{.TargetObjects}},
{{- end}}
    tool = "{{.Tool}}",
{{- if .AtOnly}}
    at_only = True,
{{- end}}
{{- if .CopyOnly}}
    copy_only = True,
{{- end}}
{{- if .EscapeQuotes}}
    escape_quotes = True,
{{- end}}
{{- if .NewlineStyle}}
    newline_style = "{{.NewlineStyle}}",
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// cmakeConfigureFileView projects ir.Target / CMakeConfigureFileSpec into
// the cmake_configure_file template. The dict-valued attributes are
// pre-rendered Starlark literals; the optional ones carry "" to signal
// omission (the template's `{{- if }}` guards). values is always emitted
// (even "{}") since the empty map is a meaningful COPYONLY lift.
type cmakeConfigureFileView struct {
	Name                string
	Out                 string
	Template            string
	ContentLiteral      string
	Values              string
	StampValues         string
	GenexValues         string
	GenexContext        string // truthiness guard
	GenexContextLiteral string
	TargetFiles         string
	TargetObjects       string
	Tool                string
	AtOnly              bool
	CopyOnly            bool
	EscapeQuotes        bool
	NewlineStyle        string
	Tags                []string
	Visibility          []string
}

func emitCMakeConfigureFile(w *bytes.Buffer, t ir.Target) error {
	s := t.CMakeConfigureFile
	if s == nil {
		return fmt.Errorf("emit cmake_configure_file %q: nil CMakeConfigureFile spec", t.Name)
	}
	v := cmakeConfigureFileView{
		Name:           t.Name,
		Out:            s.Out,
		Template:       s.Template,
		ContentLiteral: fmt.Sprintf("%q", s.Content),
		Values:         strDict(s.Values),
		Tool:           s.Tool,
		AtOnly:         s.AtOnly,
		CopyOnly:       s.CopyOnly,
		EscapeQuotes:   s.EscapeQuotes,
		NewlineStyle:   s.NewlineStyle,
		Tags:           sortedCopy(t.Tags),
		Visibility:     nonDefaultVisibility(t.Visibility),
	}
	// stamp_values omitted (left "") for the common non-stamp configure_file;
	// rendered as a readable string_dict when a VCS-stamp var feeds it.
	if len(s.StampValues) > 0 {
		v.StampValues = strDict(s.StampValues)
	}
	if len(s.GenexValuesPerConfig) > 0 {
		// Per-config divergence → render the genex_values attr as a select()
		// over the //config:<name> arms. The rule's string_dict attr is
		// configurable, so Bazel resolves the active config's map before the
		// rule impl runs (no rule change needed).
		v.GenexValues = renderConfigDictSelect(s.GenexValuesPerConfig)
	} else if len(s.GenexValues) > 0 {
		v.GenexValues = strDict(s.GenexValues)
	}
	if s.GenexContext != "" {
		v.GenexContext = s.GenexContext
		v.GenexContextLiteral = fmt.Sprintf("%q", s.GenexContext)
	}
	if len(s.TargetFiles) > 0 {
		v.TargetFiles = strDict(s.TargetFiles)
	}
	if len(s.TargetObjects) > 0 {
		v.TargetObjects = strDict(s.TargetObjects)
	}
	return cmakeConfigureFileTmpl.Execute(w, v)
}

// renderConfigDictSelect renders a per-config map (config label -> string dict)
// as a Starlark `select({...})` expression for the genex_values attribute. Keys
// are the `//config:<name>` labels the multi-config //config package backs;
// build_type's string_flag default always resolves to one of them, so no
// `//conditions:default` arm is needed. canonicalize() reformats the result, so
// this only has to emit a valid select() with sorted, byte-stable arms.
func renderConfigDictSelect(perConfig map[string]map[string]string) string {
	labels := make([]string, 0, len(perConfig))
	for l := range perConfig {
		labels = append(labels, l)
	}
	sort.Strings(labels)
	var b bytes.Buffer
	b.WriteString("select({\n")
	for _, l := range labels {
		fmt.Fprintf(&b, "        %q: %s,\n", l, strDict(perConfig[l]))
	}
	b.WriteString("    })")
	return b.String()
}

// ccView projects ir.Target into the cc-rule template. The
// *Expr fields are pre-rendered attribute values: each carries
// either a flat Starlark list literal (when the IR target has
// no PerPlatform deltas for that attribute) or a
// "<flat> + select({...})" / "select({...})" composite (when
// the per-element multi-platform fold populated the deltas).
// Pre-rendering in Go keeps the template free of conditional
// list-vs-select logic — the template just emits the raw
// expression. An empty *Expr signals "omit this attribute"
// (the template's `{{- if }}` guard does the right thing).
//
// Test-only fields (Args, Env, Timeout, Data) stay zero except
// when RuleKind == "cc_test".
type ccView struct {
	RuleKind                   string
	Name                       string
	SrcsExpr                   string
	HdrsExpr                   string
	TextualHdrsExpr            string
	IncludesExpr               string
	IncludePrefix              string
	StripIncludePrefix         string
	CoptsExpr                  string
	DefinesExpr                string
	LocalDefinesExpr           string
	LinkoptsExpr               string
	AdditionalLinkerInputsExpr string
	DepsExpr                   string
	ImplementationDepsExpr     string
	Linkstatic                 bool
	Alwayslink                 bool
	Features                   []string
	Tags                       []string
	Visibility                 []string

	// cc_test-only.
	Args    []string
	Env     map[string]string
	Timeout string // Bazel test-rule timeout enum (short/moderate/long/eternal), empty = unset
	Data    []string
}

type genruleView struct {
	Name       string
	Srcs       []string
	Outs       []string
	Tools      []string
	CmdLiteral string // already-quoted Starlark string literal
	Tags       []string
	Visibility []string
}

// ccImportView projects ir.Target into the cc_import template.
// The *Expr fields are pre-rendered attribute values: a quoted
// literal when the IR target has no per-platform delta, or a
// `select({...})` block when elementfold populated
// PerPlatformScalar / PerPlatform for the round-2 multi-platform
// fan-out. Pre-rendering in Go keeps the template free of
// scalar-vs-select branching — an empty *Expr signals "omit the
// attribute" (the template's `{{- if }}` guard does the right
// thing).
type ccImportView struct {
	Name              string
	StaticLibraryExpr string
	SharedLibraryExpr string
	HdrsExpr          string
	Tags              []string
	Visibility        []string
}

// shBinaryView projects ir.Target into the sh_binary template.
// SrcsExpr is pre-rendered; sh_binary requires srcs so the field
// is never empty in practice — the fold's target-set-agreement
// invariant means every cell declares srcs, and emit always
// produces a list literal or a select() expression.
type shBinaryView struct {
	Name       string
	SrcsExpr   string
	Tags       []string
	Visibility []string
}

func emitCCImport(w *bytes.Buffer, t ir.Target) error {
	return ccImportTmpl.Execute(w, ccImportView{
		Name:              t.Name,
		StaticLibraryExpr: scalarAttrExpr(t.StaticLibrary, perPlatformScalarAttr(t, "static_library")),
		SharedLibraryExpr: scalarAttrExpr(t.SharedLibrary, perPlatformScalarAttr(t, "shared_library")),
		HdrsExpr:          attrExpr(sortedCopy(t.Hdrs), perPlatformAttr(t, "hdrs")),
		Tags:              sortedCopy(t.Tags),
		Visibility:        nonDefaultVisibility(t.Visibility),
	})
}

func emitShBinary(w *bytes.Buffer, t ir.Target) error {
	return shBinaryTmpl.Execute(w, shBinaryView{
		Name:       t.Name,
		SrcsExpr:   attrExpr(sortedCopy(t.Srcs), perPlatformAttr(t, "srcs")),
		Tags:       sortedCopy(t.Tags),
		Visibility: nonDefaultVisibility(t.Visibility),
	})
}

// filegroupView projects ir.Target into the filegroup template.
type filegroupView struct {
	Name        string
	SrcsExpr    string
	OutputGroup string
	Tags        []string
	Visibility  []string
}

// pickFileView projects ir.Target into the pick_file template.
type pickFileView struct {
	Name       string
	Src        string
	Path       string
	Tags       []string
	Visibility []string
}

func emitPickFile(w *bytes.Buffer, t ir.Target) error {
	return pickFileTmpl.Execute(w, pickFileView{
		Name:       t.Name,
		Src:        t.PickSrc,
		Path:       t.PickPath,
		Tags:       sortedCopy(t.Tags),
		Visibility: nonDefaultVisibility(t.Visibility),
	})
}

func emitFilegroup(w *bytes.Buffer, t ir.Target) error {
	srcsExpr := attrExpr(sortedCopy(t.Srcs), perPlatformAttr(t, "srcs"))
	// Build-time glob shape (synthesized file(GLOB)-derived filegroups):
	// srcs = glob(["<pat>", ...]). Mirrors the pkg_files install(DIRECTORY)
	// glob rendering; keeps project B maintainable rather than freezing a
	// convert-time file list. (The tablegen include-closure is a separate
	// mechanism — it appends the resolved .td to the genrule's srcs, not a
	// filegroup.)
	if len(t.FilegroupGlob) > 0 {
		// Srcs and FilegroupGlob are mutually exclusive by the IR contract;
		// fail fast rather than silently dropping the explicit srcs if a
		// producer ever sets both.
		if len(t.Srcs) > 0 {
			return fmt.Errorf("filegroup %q sets both explicit srcs and FilegroupGlob; they are mutually exclusive", t.Name)
		}
		srcsExpr = "glob(" + strList(sortedCopy(t.FilegroupGlob)) + ")"
	}
	return filegroupTmpl.Execute(w, filegroupView{
		Name:        t.Name,
		SrcsExpr:    srcsExpr,
		OutputGroup: t.FilegroupOutputGroup,
		Tags:        sortedCopy(t.Tags),
		Visibility:  nonDefaultVisibility(t.Visibility),
	})
}

// pkgFilesView projects ir.Target into the pkg_files template.
type pkgFilesView struct {
	Name     string
	SrcsExpr string
	Prefix   string
	// StripPrefixExpr is the pre-rendered `strip_prefix = ...`
	// value (a `strip_prefix.from_pkg("<dir>")` call) for the
	// install(DIRECTORY) glob shape, or "" to omit the attribute
	// (install(FILES) literal-list shape). See pkgFilesSrcsExpr.
	StripPrefixExpr string
	Tags            []string
	Visibility      []string
}

func emitPkgFiles(w *bytes.Buffer, t ir.Target) error {
	srcsExpr, stripExpr := pkgFilesSrcsExpr(t)
	return pkgFilesTmpl.Execute(w, pkgFilesView{
		Name:            t.Name,
		SrcsExpr:        srcsExpr,
		Prefix:          t.PkgPrefix,
		StripPrefixExpr: stripExpr,
		Tags:            sortedCopy(t.Tags),
		Visibility:      nonDefaultVisibility(t.Visibility),
	})
}

// emitWriteFileLoad writes the
// `load("@bazel_skylib//rules:write_file.bzl", "write_file")` line
// when pkg emits any KindWriteFile target. No-op otherwise so output
// for elements without a write_file bake stays byte-stable and the
// consuming MODULE.bazel needs no bazel_skylib dep on its account.
// The corresponding write-a-side dep wiring lives in moduleBazelB
// (mirrors emitPkgFilesLoad / rules_pkg).
func emitWriteFileLoad(buf *bytes.Buffer, pkg *ir.Package) {
	for _, t := range pkg.Targets {
		if t.Kind == ir.KindWriteFile {
			buf.WriteString(`load("@bazel_skylib//rules:write_file.bzl", "write_file")` + "\n\n")
			return
		}
	}
}

// emitCMakeConfigureFileLoad emits the
// `load("@rules_buildstream_bazel//rules:cmake_configure_file.bzl", "cmake_configure_file")`
// line when pkg emits any KindCMakeConfigureFile target (the lift tier).
// No-op otherwise so output for packages without a lift stays byte-stable.
func emitCMakeConfigureFileLoad(buf *bytes.Buffer, pkg *ir.Package) {
	for _, t := range pkg.Targets {
		if t.Kind == ir.KindCMakeConfigureFile {
			buf.WriteString(`load("@rules_buildstream_bazel//rules:cmake_configure_file.bzl", "cmake_configure_file")` + "\n\n")
			return
		}
	}
}

// writeFileView projects ir.Target into the write_file template.
type writeFileView struct {
	Name       string
	Out        string
	Content    []string
	Newline    string
	Tags       []string
	Visibility []string
}

func emitWriteFile(w *bytes.Buffer, t ir.Target) error {
	newline := t.WriteFileNewline
	if newline == "" {
		newline = "unix"
	}
	return writeFileTmpl.Execute(w, writeFileView{
		Name: t.Name,
		Out:  t.WriteFileOut,
		// Content is intentionally NOT sorted — it's an ordered file
		// body, not a set. The template renders it via strList, whose
		// %q-quoting escapes each line into a valid Starlark string
		// literal; buildifier preserves the order (content is not a
		// sortable-list attribute).
		Content:    t.WriteFileContent,
		Newline:    newline,
		Tags:       sortedCopy(t.Tags),
		Visibility: nonDefaultVisibility(t.Visibility),
	})
}

// pkgFilesSrcsExpr renders the `srcs` expression (and, for the
// directory case, the `strip_prefix` expression) for a KindPkgFiles
// target.
//
//   - install(FILES) shape (PkgSrcsGlob == false): srcs is the literal
//     list `["a", "b"]` of individual files — byte-identical to the
//     pre-slice-1b-fix emission. No strip_prefix.
//   - install(DIRECTORY) shape (PkgSrcsGlob == true): srcs is a
//     `glob(["<dir>/**"])` over the source directory's contents (a
//     bare directory in srcs doesn't package its files — a consuming
//     pkg_tar fails with IsADirectoryError). One glob pattern per
//     source dir, sorted for byte-stable output. strip_prefix renders
//     as `strip_prefix.from_pkg("<dir>")` (package-relative; strips
//     the source dir so files land at "<prefix>/<rel>") when the
//     target carries a PkgStripPrefix.
func pkgFilesSrcsExpr(t ir.Target) (srcs string, strip string) {
	if !t.PkgSrcsGlob {
		return attrExpr(sortedCopy(t.Srcs), perPlatformAttr(t, "srcs")), ""
	}
	patterns := make([]string, 0, len(t.Srcs))
	for _, d := range sortedCopy(t.Srcs) {
		patterns = append(patterns, d+"/**")
	}
	srcs = "glob(" + strList(patterns) + ")"
	if t.PkgStripPrefix != "" {
		strip = fmt.Sprintf("strip_prefix.from_pkg(%q)", t.PkgStripPrefix)
	}
	return srcs, strip
}

// aliasView projects ir.Target into the alias template.
type aliasView struct {
	Name       string
	Actual     string
	Tags       []string
	Visibility []string
}

func emitAlias(w *bytes.Buffer, t ir.Target) error {
	return aliasTmpl.Execute(w, aliasView{
		Name:       t.Name,
		Actual:     t.AliasActual,
		Tags:       sortedCopy(t.Tags),
		Visibility: nonDefaultVisibility(t.Visibility),
	})
}

var boolFlagTmpl = template.Must(template.New("bool_flag").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`bool_flag(
    name = "{{.Name}}",
    build_setting_default = {{.Default}},
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

type boolFlagView struct {
	Name       string
	Default    string
	Tags       []string
	Visibility []string
}

func emitBoolFlag(w *bytes.Buffer, t ir.Target) error {
	def := "False"
	if t.BoolFlagDefault {
		def = "True"
	}
	return boolFlagTmpl.Execute(w, boolFlagView{
		Name:       t.Name,
		Default:    def,
		Tags:       sortedCopy(t.Tags),
		Visibility: nonDefaultVisibility(t.Visibility),
	})
}

var configSettingTmpl = template.Must(template.New("config_setting").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`config_setting(
    name = "{{.Name}}",
    flag_values = {
        "{{.Flag}}": "{{.Value}}",
    },
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

type configSettingView struct {
	Name       string
	Flag       string
	Value      string
	Visibility []string
}

func emitConfigSetting(w *bytes.Buffer, t ir.Target) error {
	return configSettingTmpl.Execute(w, configSettingView{
		Name:       t.Name,
		Flag:       t.ConfigSettingFlag,
		Value:      t.ConfigSettingValue,
		Visibility: nonDefaultVisibility(t.Visibility),
	})
}

// emitBoolFlagLoad writes the bazel_skylib common_settings load when any
// KindBoolFlag is present (config_setting is a built-in rule and needs
// no load). Mirrors emitWriteFileLoad's skylib precedent.
func emitBoolFlagLoad(buf *bytes.Buffer, pkg *ir.Package) {
	for _, t := range pkg.Targets {
		if t.Kind == ir.KindBoolFlag {
			buf.WriteString(`load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")` + "\n\n")
			return
		}
	}
}

func emitCCTargetWithOptions(w *bytes.Buffer, t ir.Target, opts Options) error {
	// Compute the per-attribute baselines first (matching the
	// existing single-platform sort/order conventions), then fold
	// in any per-platform deltas. cc_binary / cc_test fold their
	// hdrs into srcs before rendering; the FUSE source-label
	// rewrite applies after that fold. PerPlatform deltas are
	// rewritten with the same source-label prefix where they
	// describe per-platform srcs/hdrs.
	srcs := sortedCopy(t.Srcs)
	hdrs := sortedCopy(t.Hdrs)
	includes := sortedCopy(t.Includes)
	copts := append([]string(nil), t.Copts...) // preserve order; flag order matters
	defines := sortedCopy(t.Defines)
	linkopts := append([]string(nil), t.LinkOpts...) // preserve order
	deps := sortedCopy(t.Deps)
	implementationDeps := sortedCopy(t.ImplementationDeps)

	// cc_binary doesn't accept `hdrs` (Bazel 9 errors out where
	// older versions silently ignored). Fold any header into srcs
	// so the translation unit still sees them, even though that's
	// the rules_cc convention for binaries. cc_test inherits
	// cc_binary's stricture, so apply the same fold there.
	srcsSel := perPlatformAttr(t, "srcs")
	hdrsSel := perPlatformAttr(t, "hdrs")
	if (t.Kind == ir.KindCCBinary || t.Kind == ir.KindCCTest) && (len(hdrs) > 0 || len(hdrsSel) > 0) {
		srcs = append(srcs, hdrs...)
		sort.Strings(srcs)
		hdrs = nil
		// Per-platform hdrs deltas fold into the corresponding
		// srcs delta arms so cc_binary/cc_test still see those
		// headers as compilation inputs in their respective
		// platforms.
		if len(hdrsSel) > 0 {
			if srcsSel == nil {
				srcsSel = map[string][]string{}
			}
			for arm, items := range hdrsSel {
				srcsSel[arm] = append(srcsSel[arm], items...)
				// srcs is not order-sensitive: sort the merged
				// arm so it matches the baseline path's
				// sort-after-fold convention and so renders
				// stably regardless of cell iteration order.
				sort.Strings(srcsSel[arm])
			}
		}
		hdrsSel = nil
	}

	// FUSE-sources path: rewrite src + hdr paths to @src_<key>//:
	// labels so project B compiles against digest-referenced
	// inputs rather than relative paths. The `@…//:<path>` form
	// preserves the path exactly (no leading slash) — Bazel's
	// label parser handles it. Per-platform delta arms get the
	// same rewrite for the same reason.
	if opts.SourceKey != "" {
		srcs = prefixWithSourceLabel(srcs, opts.SourceKey)
		hdrs = prefixWithSourceLabel(hdrs, opts.SourceKey)
		srcsSel = prefixSelectWithSourceLabel(srcsSel, opts.SourceKey)
		hdrsSel = prefixSelectWithSourceLabel(hdrsSel, opts.SourceKey)
	}

	v := ccView{
		RuleKind:                   t.Kind.String(),
		Name:                       t.Name,
		SrcsExpr:                   attrExpr(srcs, srcsSel),
		HdrsExpr:                   attrExpr(hdrs, hdrsSel),
		TextualHdrsExpr:            attrExpr(sortedCopy(t.TextualHdrs), perPlatformAttr(t, "textual_hdrs")),
		IncludesExpr:               attrExpr(includes, perPlatformAttr(t, "includes")),
		IncludePrefix:              t.IncludePrefix,
		StripIncludePrefix:         t.StripIncludePrefix,
		CoptsExpr:                  attrExpr(copts, perPlatformAttr(t, "copts")),
		DefinesExpr:                attrExpr(defines, perPlatformAttr(t, "defines")),
		LocalDefinesExpr:           attrExpr(sortedCopy(t.LocalDefines), perPlatformAttr(t, "local_defines")),
		LinkoptsExpr:               attrExpr(linkopts, perPlatformAttr(t, "linkopts")),
		AdditionalLinkerInputsExpr: attrExpr(t.AdditionalLinkerInputs, nil),
		DepsExpr:                   attrExpr(deps, perPlatformAttr(t, "deps")),
		ImplementationDepsExpr:     attrExpr(implementationDeps, perPlatformAttr(t, "implementation_deps")),
		Linkstatic:                 t.Linkstatic,
		Alwayslink:                 t.Alwayslink,
		Features:                   sortedCopy(t.Features),
		// Data lifts cmake's add_dependencies-derived build-order
		// edges (set via the per-target backtrace recovery in
		// lower). cc_test additionally appends t.TestData below
		// for set_tests_properties WORKING_DIRECTORY etc.
		Data:       sortedCopy(t.Data),
		Tags:       sortedCopy(t.Tags),
		Visibility: nonDefaultVisibility(t.Visibility),
	}
	if t.Kind == ir.KindCCTest {
		v.Args = append([]string(nil), t.TestArgs...) // preserve order; arg order matters
		// cc_test: merge t.Data (add_dependencies-derived) with
		// t.TestData (set_tests_properties), sorted + deduped.
		merged := append([]string(nil), v.Data...)
		merged = append(merged, t.TestData...)
		v.Data = sortedDedup(merged)
		if t.TestTimeout > 0 {
			v.Timeout = formatBazelTimeout(t.TestTimeout)
		}
		if len(t.TestEnv) > 0 {
			v.Env = make(map[string]string, len(t.TestEnv))
			for _, kv := range t.TestEnv {
				if i := strings.IndexByte(kv, '='); i >= 0 {
					v.Env[kv[:i]] = kv[i+1:]
				}
			}
		}
	}
	return ccRuleTmpl.Execute(w, v)
}

// perPlatformScalarAttr returns the per-platform scalar delta map
// for the named attribute. Nil-safe: returns nil when the IR
// target has no PerPlatformScalar map or no entry for the
// requested name. Used by emitCCImport for static_library /
// shared_library, which are single-string attrs (cc_import's
// path attrs) that fold differently from the list-shaped
// PerPlatform.
func perPlatformScalarAttr(t ir.Target, name string) map[string]string {
	if len(t.PerPlatformScalar) == 0 {
		return nil
	}
	m, ok := t.PerPlatformScalar[name]
	if !ok || len(m) == 0 {
		return nil
	}
	out := make(map[string]string, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

// scalarAttrExpr renders a single-string cc-rule attribute's
// value. Returns:
//
//   - "" when both flat and sel are empty (caller omits the
//     attribute entirely — cc_import targets that only carry one
//     of static_library / shared_library leave the other empty).
//   - the quoted literal when sel is empty (single-platform
//     shape; byte-identical to the pre-PerPlatformScalar
//     emission).
//   - a `select({...})` block with a trailing
//     `"//conditions:default": None` arm when sel is non-empty.
//     Unlike the list case there's no `<flat> + select()` form
//     (scalars don't compose under "+"), but the default arm IS
//     present so in-matrix platforms without a value for this
//     attribute fall through to "attribute unset" rather than
//     hitting a missing-arm analysis error. The partial-platform
//     cc_import case — linux has only static_library, darwin has
//     only shared_library — needs this: a build for darwin sees
//     `static_library = select({linux: "...", "//conditions:default": None})`
//     and Bazel treats static_library as unset (cc_import's
//     default), the right outcome instead of an analysis error.
//     Out-of-matrix platforms also resolve to None (attribute
//     unset), which matches the "this target doesn't apply
//     outside the declared matrix" semantic.
func scalarAttrExpr(flat string, sel map[string]string) string {
	hasSel := len(sel) > 0
	hasFlat := flat != ""
	if !hasSel && !hasFlat {
		return ""
	}
	if !hasSel {
		return fmt.Sprintf("%q", flat)
	}
	keys := make([]string, 0, len(sel))
	for k := range sel {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b bytes.Buffer
	b.WriteString("select({\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "        %q: %q,\n", k, sel[k])
	}
	b.WriteString(`        "//conditions:default": None,` + "\n")
	b.WriteString("    })")
	return b.String()
}

// perPlatformAttr returns the per-platform delta map for the
// named attribute. Nil-safe: returns nil when the IR target has
// no PerPlatform map at all or no entry for the requested name.
// The returned map is a shallow copy so emit-time mutations
// (the cc_binary hdrs→srcs fold) don't bleed back into the
// caller's IR.
func perPlatformAttr(t ir.Target, name string) map[string][]string {
	if len(t.PerPlatform) == 0 {
		return nil
	}
	m, ok := t.PerPlatform[name]
	if !ok || len(m) == 0 {
		return nil
	}
	out := make(map[string][]string, len(m))
	for k, v := range m {
		out[k] = append([]string(nil), v...)
	}
	return out
}

// prefixSelectWithSourceLabel applies prefixWithSourceLabel to
// every arm of a select()-shaped delta map. Returns nil for nil
// input so a "no delta" signal stays a "no delta" signal.
func prefixSelectWithSourceLabel(sel map[string][]string, key string) map[string][]string {
	if sel == nil {
		return nil
	}
	out := make(map[string][]string, len(sel))
	for arm, items := range sel {
		out[arm] = prefixWithSourceLabel(items, key)
	}
	return out
}

// prefixWithSourceLabel maps relative source paths to
// @src_<key>//:tree_dir/<path> Bazel labels. The tree_dir/
// segment matches the repo rule's layout: rules/sources.bzl's
// _src_repo_impl ctx.symlinks the FUSE mount under tree_dir/
// inside the @src_<key>// repo and exports every path under
// it via exports_files(glob(["tree_dir/**"])). The label form
// preserves the relative path exactly under that prefix.
//
// Returns a fresh slice so the caller's view stays untouched on
// the legacy (non-fuse) path.
func prefixWithSourceLabel(paths []string, key string) []string {
	if len(paths) == 0 {
		return paths
	}
	out := make([]string, len(paths))
	for i, p := range paths {
		out[i] = "@src_" + key + "//:tree_dir/" + p
	}
	return out
}

// formatBazelTimeout maps a CTest TIMEOUT (a duration in seconds) to the
// Bazel test-rule `timeout` attribute, which is a fixed ENUM — "short"
// (≤60s), "moderate" (≤300s), "long" (≤900s), "eternal" (>900s) — NOT a
// duration string. Bazel rejects a duration like "120s" on a test rule's
// `timeout` at load time ("must be short, moderate, long, or eternal"), so
// CTest's integer seconds is bucketed into the smallest enum whose default
// budget covers it — except that "eternal" is the ceiling: a TIMEOUT beyond
// eternal's default (commonly 3600s) still maps to "eternal" as the largest
// available bucket (best effort; an operator can raise it with
// --test_timeout if a test genuinely needs longer). (Issue #314.)
func formatBazelTimeout(d time.Duration) string {
	switch {
	case d <= 60*time.Second:
		return "short"
	case d <= 300*time.Second:
		return "moderate"
	case d <= 900*time.Second:
		return "long"
	default:
		return "eternal"
	}
}

func emitGenrule(w *bytes.Buffer, t ir.Target) error {
	v := genruleView{
		Name:       t.Name,
		Srcs:       sortedCopy(t.Srcs),
		Outs:       sortedCopy(t.GenruleOuts),
		Tools:      sortedCopy(t.GenruleTools),
		CmdLiteral: fmt.Sprintf("%q", t.GenruleCmd),
		Tags:       sortedCopy(t.Tags),
		Visibility: nonDefaultVisibility(t.Visibility),
	}
	return genruleTmpl.Execute(w, v)
}

func sortedCopy(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}

// sortedDedup returns a sorted slice with consecutive duplicates
// removed. Cheap for the small slices the emitter typically
// composes (per-attribute fact lists).
func sortedDedup(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := append([]string(nil), in...)
	sort.Strings(out)
	w := out[:1]
	for _, x := range out[1:] {
		if x != w[len(w)-1] {
			w = append(w, x)
		}
	}
	return w
}

// strDict renders a Go map[string]string as a Starlark dict literal,
// keys sorted for byte-stable output. Empty maps render as "{}".
func strDict(m map[string]string) string {
	if len(m) == 0 {
		return "{}"
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var single bytes.Buffer
	single.WriteByte('{')
	for i, k := range keys {
		if i > 0 {
			single.WriteString(", ")
		}
		fmt.Fprintf(&single, "%q: %q", k, m[k])
	}
	single.WriteByte('}')
	if single.Len() <= 60 {
		return single.String()
	}
	var multi bytes.Buffer
	multi.WriteString("{\n")
	for _, k := range keys {
		fmt.Fprintf(&multi, "        %q: %q,\n", k, m[k])
	}
	multi.WriteString("    }")
	return multi.String()
}

// strList renders a Go []string as a Starlark list literal:
//
//	["a", "b"]                       (single-line if total <= 60 chars)
//	[
//	    "a",
//	    "b",
//	]                                 (multi-line otherwise)
func strList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	// single-line trial. %q escapes embedded quotes / backslashes /
	// control bytes so values like `LZ4_VERSION="1.8.0"` (cmake
	// derives these from add_definitions(-DLZ4_VERSION="1.8.0"))
	// produce valid Starlark string literals instead of unparseable
	// `"LZ4_VERSION="1.8.0""`. Same escaping the multi-line arm
	// already uses; the divergence was a latent bug surfaced by
	// real-world (VTK / lz4) defines.
	var single bytes.Buffer
	single.WriteByte('[')
	for i, s := range items {
		if i > 0 {
			single.WriteString(", ")
		}
		fmt.Fprintf(&single, "%q", s)
	}
	single.WriteByte(']')
	if single.Len() <= 60 {
		return single.String()
	}
	// multi-line
	var multi bytes.Buffer
	multi.WriteString("[\n")
	for _, s := range items {
		fmt.Fprintf(&multi, "        %q,\n", s)
	}
	multi.WriteString("    ]")
	return multi.String()
}

// attrExpr renders one cc-rule attribute's value combining a flat
// baseline list with optional per-platform deltas. Returns:
//
//   - "" when both flat and sel are empty (caller omits the
//     attribute entirely)
//   - strList(flat) when sel is empty (existing single-platform
//     behaviour, byte-identical to the pre-PerPlatform shape)
//   - "select({...})" when only sel is non-empty (no baseline
//     items shared across every platform)
//   - "<flat> + select({...})" when both are non-empty
//
// The select() block always carries a "//conditions:default": []
// arm so a Bazel build under a platform not in the select keys
// resolves to an empty list rather than failing analysis. Arm
// keys are emitted in sorted order so the rendered BUILD.bazel
// is byte-stable across runs (map iteration is randomized).
//
// Arm-list contents are emitted in the caller-supplied order.
// elementfold owns the per-attribute ordering convention: it
// sorts order-insensitive attrs (srcs, hdrs, includes, defines,
// deps) lexicographically and preserves cells' original sequence
// for order-sensitive attrs (copts, linkopts). emit-time
// fan-in (e.g. cc_binary's hdrs→srcs arm merge) is responsible
// for sorting its own merged arms before passing them in.
func attrExpr(flat []string, sel map[string][]string) string {
	hasSel := len(sel) > 0
	hasFlat := len(flat) > 0
	if !hasSel && !hasFlat {
		return ""
	}
	flatPart := ""
	if hasFlat {
		flatPart = strList(flat)
	}
	if !hasSel {
		return flatPart
	}
	// The "//conditions:default" arm is rendered LAST and exactly once.
	// When the caller's select map carries an explicit
	// "//conditions:default" delta (a platform if-chain's else() arm,
	// recovered by the #217 partition), its items populate that arm
	// instead of the empty list — emitting it as a normal key would
	// produce a duplicate "//conditions:default" key, which Bazel
	// rejects.
	defaultArm := sel["//conditions:default"]
	keys := make([]string, 0, len(sel))
	for k := range sel {
		if k == "//conditions:default" {
			continue
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b bytes.Buffer
	b.WriteString("select({\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "        %q: %s,\n", k, indentArmList(sel[k]))
	}
	fmt.Fprintf(&b, "        %q: %s,\n", "//conditions:default", indentArmList(defaultArm))
	b.WriteString("    })")

	if hasFlat {
		return flatPart + " + " + b.String()
	}
	return b.String()
}

// indentArmList renders a select() arm's value as a Starlark
// list literal indented for a select({}) block at the cc-rule
// attribute level (8 spaces leading on continuation lines, with
// the closing bracket lining up with the arm's key column).
// Empty list → "[]" inline; non-empty → multi-line so each
// item gets its own line, regardless of brevity, because the
// surrounding select() is already multi-line and a single-line
// arm would visually clash.
//
// Items are rendered in the caller-supplied order: the
// elementfold layer already produces arms in the right order
// per attribute (lexicographic for srcs/hdrs/etc., original
// sequence for order-sensitive copts/linkopts), and any
// emit-time fan-in (e.g. cc_binary's hdrs→srcs fold) sorts
// its merged arm explicitly before passing it down. Sorting
// unconditionally here would re-order copts/linkopts deltas
// out of the sequence the operator wrote.
func indentArmList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	var b bytes.Buffer
	b.WriteString("[\n")
	for _, s := range items {
		fmt.Fprintf(&b, "            %q,\n", s)
	}
	b.WriteString("        ]")
	return b.String()
}

// collapseToSingleLine maps any embedded newline / carriage return
// in a header-comment line to a single space, then collapses
// runs of whitespace introduced by the substitution. Used to keep
// the file-head `# <line>\n` shape stable when an upstream
// producer (cmake HELPSTRING, deprecation message, find_package
// attribution) carries multi-line text that would otherwise
// break the emitted comment block.
func collapseToSingleLine(s string) string {
	if !strings.ContainsAny(s, "\n\r") {
		return s
	}
	r := strings.NewReplacer("\r\n", " ", "\n", " ", "\r", " ")
	out := r.Replace(s)
	// Collapse adjacent spaces to one so "foo\n   bar" doesn't
	// render as "foo    bar".
	for strings.Contains(out, "  ") {
		out = strings.ReplaceAll(out, "  ", " ")
	}
	return strings.TrimSpace(out)
}
