// Package bazel emits a BUILD.bazel file from the IR.
//
// M1 uses text/template for stable, easy-to-diff output and zero external
// deps. The plan calls for a buildtools-AST spike in week 1; if it's adopted,
// it replaces the template here without changing the Emit signature.
//
// Output is deterministic: every list attribute is sorted before emission.
package bazel

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/bazelbuild/buildtools/build"
	"github.com/sstriker/buildstream-bazel/converter/ir"
)

// header is intentionally path-free so the emitted BUILD.bazel is
// byte-identical across runs, machines, and per-orchestration tmpdirs.
// The element / codebase the file belongs to is implicit in its
// on-disk location (out/elements/<name>/BUILD.bazel for orchestrator
// runs; whatever --out-build the operator passed for standalone runs).
const header = `# Generated by convert-element-cmake. DO NOT EDIT.

`

// ccRuleLoads maps each Kind to its rules_cc load symbol. Bazel 9
// removed cc_library/cc_binary/cc_import from the global namespace;
// every emitted BUILD.bazel using one of these rules must `load()`
// it explicitly. Older Bazels accept the load + load-less form alike.
var ccRuleLoads = map[ir.Kind]string{
	ir.KindCCLibrary:   "cc_library",
	ir.KindCCBinary:    "cc_binary",
	ir.KindCCImport:    "cc_import",
	ir.KindCCInterface: "cc_library",
	ir.KindCCTest:      "cc_test",
}

// emitPackageDefaultVisibility writes the file-head
// `package(default_visibility = ["//visibility:public"])` line
// that every generated BUILD carries. Gazelle / gazelle_cc
// canon: visibility is set once at the package level and
// per-rule `visibility` is emitted only when overriding the
// default. The corresponding per-rule suppression lives in
// nonDefaultVisibility (called from each ccView/ccImportView/
// shBinaryView/genruleView constructor), which drops the
// public default from each target's emitted attributes.
//
// This pairs with the per-rule logic: visibility set on a
// target that equals the package default is omitted from the
// emitted rule; a target with a different visibility (e.g.
// `//visibility:private` or a specific package_group) still
// emits its own visibility line, which Bazel treats as the
// override per the standard precedence.
func emitPackageDefaultVisibility(buf *bytes.Buffer) {
	buf.WriteString(`package(default_visibility = ["//visibility:public"])` + "\n\n")
}

// defaultPublicVisibility is the package-level default emitted
// by emitPackageDefaultVisibility. Per-rule Visibility slices
// matching this exact list are suppressed by
// nonDefaultVisibility — the package default already covers
// them and a duplicate per-rule line would be noise that
// `gazelle fix` would later remove.
var defaultPublicVisibility = []string{"//visibility:public"}

// nonDefaultVisibility returns vis verbatim when it represents
// an override of the package-level default
// (//visibility:public), and nil when vis equals the package
// default. Centralizing the comparison here means every view
// constructor (ccView, ccImportView, shBinaryView,
// genruleView) emits the same elision policy without each
// having to spell out the public-default literal.
//
// vis is returned as a fresh slice in the override case so the
// caller can mutate freely without aliasing the IR-side
// Visibility slice; the IR is read-only from emit's
// perspective.
func nonDefaultVisibility(vis []string) []string {
	if len(vis) == len(defaultPublicVisibility) {
		match := true
		for i, v := range vis {
			if v != defaultPublicVisibility[i] {
				match = false
				break
			}
		}
		if match {
			return nil
		}
	}
	if len(vis) == 0 {
		return nil
	}
	return append([]string(nil), vis...)
}

// emitGazelleCcSearch writes `# gazelle:cc_search <dir>` file-head
// directives mirroring the union of every target's `includes`
// attribute values. Per docs/design/build-output-conventions.md
// Phase 7d: gazelle_cc's header-scan resolver needs the same
// include search paths the converter extracted from CMake so an
// operator-added `#include` of an in-tree header resolves to the
// right label on `gazelle fix`. The directive is package-scoped,
// so the union across targets (deduped, sorted) is the right
// granularity.
//
// Inert when gazelle isn't installed — it's a plain `#` comment
// to any tool that doesn't look for it. No-op when no target
// carries `includes`, keeping includes-free goldens byte-stable.
func emitGazelleCcSearch(buf *bytes.Buffer, pkg *ir.Package) {
	seen := map[string]struct{}{}
	var dirs []string
	for _, t := range pkg.Targets {
		for _, d := range t.Includes {
			if _, ok := seen[d]; ok {
				continue
			}
			seen[d] = struct{}{}
			dirs = append(dirs, d)
		}
	}
	if len(dirs) == 0 {
		return
	}
	sort.Strings(dirs)
	for _, d := range dirs {
		fmt.Fprintf(buf, "# gazelle:cc_search %s\n", d)
	}
	buf.WriteString("\n")
}

// emitLoad writes a single `load("@rules_cc//cc:defs.bzl", ...)` line
// covering every cc_* symbol used by pkg's targets. Symbols are sorted
// for byte-stability. Returns nothing if pkg has no cc_* targets.
func emitLoad(buf *bytes.Buffer, pkg *ir.Package) {
	used := map[string]struct{}{}
	for _, t := range pkg.Targets {
		if sym, ok := ccRuleLoads[t.Kind]; ok {
			used[sym] = struct{}{}
		}
	}
	if len(used) == 0 {
		return
	}
	syms := make([]string, 0, len(used))
	for s := range used {
		syms = append(syms, s)
	}
	sort.Strings(syms)
	buf.WriteString(`load("@rules_cc//cc:defs.bzl"`)
	for _, s := range syms {
		fmt.Fprintf(buf, ", %q", s)
	}
	buf.WriteString(")\n\n")
}

// Options tunes the BUILD.bazel emission. Zero-value Options
// preserves the legacy relative-path emission.
type Options struct {
	// SourceKey, when non-empty, prefixes every source path in
	// emitted cc_library/cc_binary/cc_test `srcs = [...]` with
	// "@src_<SourceKey>//:" so project B references the bytes
	// by digest-stable Bazel label rather than by local
	// filesystem path. Used by the FUSE-sources route to keep
	// project B's compile actions BwoB without a project-B-side
	// FUSE mount of its own.
	SourceKey string

	// Header overrides the default "# Generated by
	// convert-element-cmake. DO NOT EDIT.\n\n" file-head comment.
	// Multiple cmd/* binaries share this emitter (convert-
	// element / convert-element-meson / convert-element-trace
	// / fold-element); each can attribute its own output via
	// Header so the operator-visible provenance comment names
	// the actual binary that produced the file. Must end with
	// a trailing "\n\n" if the caller wants a blank line
	// separating the header from the rest of the BUILD; this
	// field is appended verbatim to the buffer.
	Header string
}

// Emit returns the contents of a BUILD.bazel file for pkg using
// default Options.
func Emit(pkg *ir.Package) ([]byte, error) {
	return EmitWithOptions(pkg, Options{})
}

// EmitWithOptions is the configurable form of Emit.
//
// The emitter constructs each rule via the in-package text
// templates and then routes the assembled output through
// `bazel.build/buildtools/build`'s Parse + Format pipeline —
// the same pipeline `buildifier --mode=fix` uses. That gives
// project B the Phase 3 contract from
// docs/design/build-output-conventions.md: `buildifier
// --mode=fix` against our generated BUILDs is a no-op (we
// emit what buildifier would produce). Side effect: attribute
// order pulls from buildtools' `tables.NamePriority` rather
// than the template's manual order, so the rendered shape
// matches what an operator hand-formatting via buildifier
// would see post-conversion.
func EmitWithOptions(pkg *ir.Package, opts Options) ([]byte, error) {
	var buf bytes.Buffer
	if opts.Header != "" {
		buf.WriteString(opts.Header)
	} else {
		buf.WriteString(header)
	}
	emitGazelleCcSearch(&buf, pkg)
	emitLoad(&buf, pkg)
	emitPackageDefaultVisibility(&buf)

	for i, t := range pkg.Targets {
		if i > 0 {
			buf.WriteString("\n")
		}
		if t.Kind == ir.KindGenrule {
			if err := emitGenrule(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindCCImport {
			if err := emitCCImport(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindShBinary {
			if err := emitShBinary(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if err := emitCCTargetWithOptions(&buf, t, opts); err != nil {
			return nil, err
		}
	}
	return canonicalize(buf.Bytes()), nil
}

// canonicalize routes the template-assembled BUILD text
// through buildtools' Parse + Format pipeline so the final
// output matches what `buildifier --mode=fix` would produce.
// Attribute order pulls from `tables.NamePriority`; list
// wrapping, quote normalization, and load() symbol sorting
// fall out of the formatter's default Rewriter pass.
//
// We use a synthetic filename ending in `BUILD.bazel` so
// buildtools parses with TypeBuild semantics (it dispatches
// off the path basename). The bytes never touch disk; the
// name is purely a parse-mode hint.
//
// On a parse error we panic — see the inline comment in
// the function body for rationale. The templates in this
// package are the only source of the body bytes, so a
// parse failure means the emitter regressed to producing
// syntactically invalid Bazel. Silent fallback would let
// the buildifier-no-op contract break without a test-
// visible trigger; the panic surfaces it loudly in the
// test suite instead.
func canonicalize(body []byte) []byte {
	f, err := build.Parse("BUILD.bazel", body)
	if err != nil {
		// This emitter's templates are the only source of
		// the body bytes; a buildtools-Parse failure here
		// means the templates regressed to producing
		// syntactically invalid Bazel. Surface loudly so
		// the test suite sees the diagnostic, rather than
		// silently swallowing and quietly writing
		// non-canonical output (which would break the
		// Phase 3 buildifier-no-op contract without a
		// test-visible trigger).
		panic(fmt.Sprintf("bazel.canonicalize: template emitted unparseable BUILD bytes: %v\n%s", err, body))
	}
	addKeepMarkers(f)
	return build.Format(f)
}

// addKeepMarkers walks every rule in f and tags load-bearing
// attribute lines (and whole rules, for genrule / filegroup)
// with `# keep` comments. Per docs/design/build-output-
// conventions.md's Phase 7a roundtrip spec: these markers
// prevent a downstream `gazelle fix` run from rewriting
// values the converter extracted from CMake/Meson/trace —
// signals gazelle wouldn't be able to re-derive from
// post-conversion sources alone.
//
// The marker scope follows the conventions doc's table:
//
//   - cc_library / cc_binary / cc_test: copts, defines,
//     linkopts, includes, tags, linkstatic, alwayslink,
//     include_prefix, strip_include_prefix.
//   - cc_test additionally: args, env, timeout, data.
//   - cc_import: includes (when present), system_provided,
//     alwayslink (per the rule schema differences).
//   - genrule + filegroup: whole-rule keep (closing-paren
//     suffix comment).
//   - package(...): whole-rule keep.
//
// The marker doesn't trigger when gazelle isn't installed —
// it's an inert # comment to any tool that doesn't look for
// it. Phase 3's buildifier-canonical contract is preserved:
// buildifier honors the keep markers and doesn't reformat
// the tagged lines.
func addKeepMarkers(f *build.File) {
	for _, stmt := range f.Stmt {
		call, ok := stmt.(*build.CallExpr)
		if !ok {
			continue
		}
		kind := callRuleKind(call)
		switch kind {
		case "genrule", "filegroup", "package":
			markCallKeep(call)
		case "cc_library", "cc_binary", "cc_test":
			markAttrsKeep(call, ccKeepAttrs(kind))
		case "cc_import":
			markAttrsKeep(call, ccImportKeepAttrs)
		}
	}
}

// callRuleKind returns the rule kind for a CallExpr (e.g.
// "cc_library", "genrule") or "" if the call's function
// position isn't a bare identifier. Top-level BUILD calls
// are typically Ident-headed; load() is the exception (it's
// an Ident but routed elsewhere via stmt type).
func callRuleKind(call *build.CallExpr) string {
	if ident, ok := call.X.(*build.Ident); ok {
		return ident.Name
	}
	return ""
}

// markCallKeep appends a `# keep` suffix comment to the
// CallExpr itself. The formatter renders this on the line
// of the closing `)` of the call.
func markCallKeep(call *build.CallExpr) {
	if hasKeepSuffix(call.Comment().Suffix) {
		return
	}
	call.Comment().Suffix = append(call.Comment().Suffix, build.Comment{Token: "# keep"})
}

// markAttrsKeep walks the call's positional/keyword args
// and tags each AssignExpr whose LHS is one of attrNames
// with a `# keep` suffix.
func markAttrsKeep(call *build.CallExpr, attrNames map[string]bool) {
	if len(attrNames) == 0 {
		return
	}
	for _, arg := range call.List {
		assign, ok := arg.(*build.AssignExpr)
		if !ok {
			continue
		}
		ident, ok := assign.LHS.(*build.Ident)
		if !ok {
			continue
		}
		if !attrNames[ident.Name] {
			continue
		}
		if hasKeepSuffix(assign.Comment().Suffix) {
			continue
		}
		assign.Comment().Suffix = append(assign.Comment().Suffix, build.Comment{Token: "# keep"})
	}
}

// hasKeepSuffix reports whether the comment slice already
// contains a `# keep` marker. Used to make addKeepMarkers
// idempotent — calling canonicalize twice on the same body
// (e.g. round-tripping through write-a's BUILD.bazel
// canonicalize plus the embedded one here) doesn't double
// up markers.
func hasKeepSuffix(comments []build.Comment) bool {
	for _, c := range comments {
		if strings.TrimSpace(c.Token) == "# keep" {
			return true
		}
	}
	return false
}

// ccKeepAttrs returns the set of attribute names that
// receive `# keep` markers for a cc_* rule kind. cc_test
// gets the cc_library set plus its test-only attributes.
func ccKeepAttrs(kind string) map[string]bool {
	base := map[string]bool{
		"copts":                true,
		"defines":              true,
		"linkopts":             true,
		"includes":             true,
		"tags":                 true,
		"linkstatic":           true,
		"alwayslink":           true,
		"include_prefix":       true,
		"strip_include_prefix": true,
	}
	if kind == "cc_test" {
		base["args"] = true
		base["env"] = true
		base["timeout"] = true
		base["data"] = true
	}
	return base
}

// ccImportKeepAttrs are the keep-tagged attributes on
// cc_import — the rule schema differs from cc_library and
// excludes most of the compile-side attrs. Per Phase 2's
// `execute_process_fallback.go` gap update, stock
// rules_cc's cc_import doesn't actually accept `includes`
// either; the canonical fix for the round-2 fallback's
// bracket-include consumers is wrapping cc_import in a
// cc_library that uses strip_include_prefix. The
// `includes` entry stays in this map defensively for any
// future emit-time wrap that targets cc_import directly.
// `static_library` / `shared_library` carry the per-
// platform select() shapes the round-2 fallback emits.
var ccImportKeepAttrs = map[string]bool{
	"includes":        true,
	"system_provided": true,
	"alwayslink":      true,
	"static_library":  true,
	"shared_library":  true,
}

var ccRuleTmpl = template.Must(template.New("rule").Funcs(template.FuncMap{
	"strList": strList,
	"strDict": strDict,
}).Parse(`{{.RuleKind}}(
    name = "{{.Name}}",
{{- if .SrcsExpr}}
    srcs = {{.SrcsExpr}},
{{- end}}
{{- if .HdrsExpr}}
    hdrs = {{.HdrsExpr}},
{{- end}}
{{- if .IncludesExpr}}
    includes = {{.IncludesExpr}},
{{- end}}
{{- if .IncludePrefix}}
    include_prefix = "{{.IncludePrefix}}",
{{- end}}
{{- if .StripIncludePrefix}}
    strip_include_prefix = "{{.StripIncludePrefix}}",
{{- end}}
{{- if .CoptsExpr}}
    copts = {{.CoptsExpr}},
{{- end}}
{{- if .DefinesExpr}}
    defines = {{.DefinesExpr}},
{{- end}}
{{- if .LinkoptsExpr}}
    linkopts = {{.LinkoptsExpr}},
{{- end}}
{{- if .DepsExpr}}
    deps = {{.DepsExpr}},
{{- end}}
{{- if .ImplementationDepsExpr}}
    implementation_deps = {{.ImplementationDepsExpr}},
{{- end}}
{{- if .Data}}
    data = {{strList .Data}},
{{- end}}
{{- if .Args}}
    args = {{strList .Args}},
{{- end}}
{{- if .Env}}
    env = {{strDict .Env}},
{{- end}}
{{- if .Timeout}}
    timeout = "{{.Timeout}}",
{{- end}}
{{- if .Linkstatic}}
    linkstatic = True,
{{- end}}
{{- if .Alwayslink}}
    alwayslink = True,
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// ccImportTmpl renders cc_import. Distinct from the generic
// cc_library / cc_binary template because cc_import's
// attribute set is fundamentally different — it wraps a
// pre-built archive / shared object (StaticLibrary /
// SharedLibrary as single-file label refs) plus optional hdrs;
// no srcs / copts / defines / deps. The *Expr fields are
// pre-rendered strings: a quoted path literal when every cell
// agrees, or a `select({...})` block when elementfold's per-
// platform fold populated PerPlatformScalar (round-2 fallback
// path attrs diverge between linux multiarch lib dirs and
// darwin .dylib paths).
var ccImportTmpl = template.Must(template.New("cc_import").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`cc_import(
    name = "{{.Name}}",
{{- if .StaticLibraryExpr}}
    static_library = {{.StaticLibraryExpr}},
{{- end}}
{{- if .SharedLibraryExpr}}
    shared_library = {{.SharedLibraryExpr}},
{{- end}}
{{- if .HdrsExpr}}
    hdrs = {{.HdrsExpr}},
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// shBinaryTmpl renders sh_binary. Bazel's sh_binary expects a
// single-element srcs (the executable) — no hdrs, no copts.
// Used by the kind:cmake round-2 fallback's per-target stubs
// for EXECUTABLE targets, where the placeholder references
// the installed binary path directly. SrcsExpr is the pre-
// rendered list expression — flat literal when single-platform,
// `select({...})` (or `[…] + select({...})`) when elementfold
// populated PerPlatform["srcs"] for the round-2 multi-platform
// fan-out (where the install_tree.tar's binary path is
// arch-tagged on some platforms).
var shBinaryTmpl = template.Must(template.New("sh_binary").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`sh_binary(
    name = "{{.Name}}",
    srcs = {{.SrcsExpr}},
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

var genruleTmpl = template.Must(template.New("genrule").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`genrule(
    name = "{{.Name}}",
{{- if .Srcs}}
    srcs = {{strList .Srcs}},
{{- end}}
    outs = {{strList .Outs}},
    cmd = {{.CmdLiteral}},
{{- if .Tools}}
    tools = {{strList .Tools}},
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// ccView projects ir.Target into the cc-rule template. The
// *Expr fields are pre-rendered attribute values: each carries
// either a flat Starlark list literal (when the IR target has
// no PerPlatform deltas for that attribute) or a
// "<flat> + select({...})" / "select({...})" composite (when
// the per-element multi-platform fold populated the deltas).
// Pre-rendering in Go keeps the template free of conditional
// list-vs-select logic — the template just emits the raw
// expression. An empty *Expr signals "omit this attribute"
// (the template's `{{- if }}` guard does the right thing).
//
// Test-only fields (Args, Env, Timeout, Data) stay zero except
// when RuleKind == "cc_test".
type ccView struct {
	RuleKind               string
	Name                   string
	SrcsExpr               string
	HdrsExpr               string
	IncludesExpr           string
	IncludePrefix          string
	StripIncludePrefix     string
	CoptsExpr              string
	DefinesExpr            string
	LinkoptsExpr           string
	DepsExpr               string
	ImplementationDepsExpr string
	Linkstatic             bool
	Alwayslink             bool
	Tags                   []string
	Visibility             []string

	// cc_test-only.
	Args    []string
	Env     map[string]string
	Timeout string // pre-formatted Bazel duration ("30s", "5m"), empty = unset
	Data    []string
}

type genruleView struct {
	Name       string
	Srcs       []string
	Outs       []string
	Tools      []string
	CmdLiteral string // already-quoted Starlark string literal
	Tags       []string
	Visibility []string
}

// ccImportView projects ir.Target into the cc_import template.
// The *Expr fields are pre-rendered attribute values: a quoted
// literal when the IR target has no per-platform delta, or a
// `select({...})` block when elementfold populated
// PerPlatformScalar / PerPlatform for the round-2 multi-platform
// fan-out. Pre-rendering in Go keeps the template free of
// scalar-vs-select branching — an empty *Expr signals "omit the
// attribute" (the template's `{{- if }}` guard does the right
// thing).
type ccImportView struct {
	Name              string
	StaticLibraryExpr string
	SharedLibraryExpr string
	HdrsExpr          string
	Tags              []string
	Visibility        []string
}

// shBinaryView projects ir.Target into the sh_binary template.
// SrcsExpr is pre-rendered; sh_binary requires srcs so the field
// is never empty in practice — the fold's target-set-agreement
// invariant means every cell declares srcs, and emit always
// produces a list literal or a select() expression.
type shBinaryView struct {
	Name       string
	SrcsExpr   string
	Tags       []string
	Visibility []string
}

func emitCCImport(w *bytes.Buffer, t ir.Target) error {
	return ccImportTmpl.Execute(w, ccImportView{
		Name:              t.Name,
		StaticLibraryExpr: scalarAttrExpr(t.StaticLibrary, perPlatformScalarAttr(t, "static_library")),
		SharedLibraryExpr: scalarAttrExpr(t.SharedLibrary, perPlatformScalarAttr(t, "shared_library")),
		HdrsExpr:          attrExpr(sortedCopy(t.Hdrs), perPlatformAttr(t, "hdrs")),
		Tags:              sortedCopy(t.Tags),
		Visibility:        nonDefaultVisibility(t.Visibility),
	})
}

func emitShBinary(w *bytes.Buffer, t ir.Target) error {
	return shBinaryTmpl.Execute(w, shBinaryView{
		Name:       t.Name,
		SrcsExpr:   attrExpr(sortedCopy(t.Srcs), perPlatformAttr(t, "srcs")),
		Tags:       sortedCopy(t.Tags),
		Visibility: nonDefaultVisibility(t.Visibility),
	})
}

func emitCCTarget(w *bytes.Buffer, t ir.Target) error {
	return emitCCTargetWithOptions(w, t, Options{})
}

func emitCCTargetWithOptions(w *bytes.Buffer, t ir.Target, opts Options) error {
	// Compute the per-attribute baselines first (matching the
	// existing single-platform sort/order conventions), then fold
	// in any per-platform deltas. cc_binary / cc_test fold their
	// hdrs into srcs before rendering; the FUSE source-label
	// rewrite applies after that fold. PerPlatform deltas are
	// rewritten with the same source-label prefix where they
	// describe per-platform srcs/hdrs.
	srcs := sortedCopy(t.Srcs)
	hdrs := sortedCopy(t.Hdrs)
	includes := sortedCopy(t.Includes)
	copts := append([]string(nil), t.Copts...) // preserve order; flag order matters
	defines := sortedCopy(t.Defines)
	linkopts := append([]string(nil), t.LinkOpts...) // preserve order
	deps := sortedCopy(t.Deps)
	implementationDeps := sortedCopy(t.ImplementationDeps)

	// cc_binary doesn't accept `hdrs` (Bazel 9 errors out where
	// older versions silently ignored). Fold any header into srcs
	// so the translation unit still sees them, even though that's
	// the rules_cc convention for binaries. cc_test inherits
	// cc_binary's stricture, so apply the same fold there.
	srcsSel := perPlatformAttr(t, "srcs")
	hdrsSel := perPlatformAttr(t, "hdrs")
	if (t.Kind == ir.KindCCBinary || t.Kind == ir.KindCCTest) && (len(hdrs) > 0 || len(hdrsSel) > 0) {
		srcs = append(srcs, hdrs...)
		sort.Strings(srcs)
		hdrs = nil
		// Per-platform hdrs deltas fold into the corresponding
		// srcs delta arms so cc_binary/cc_test still see those
		// headers as compilation inputs in their respective
		// platforms.
		if len(hdrsSel) > 0 {
			if srcsSel == nil {
				srcsSel = map[string][]string{}
			}
			for arm, items := range hdrsSel {
				srcsSel[arm] = append(srcsSel[arm], items...)
				// srcs is not order-sensitive: sort the merged
				// arm so it matches the baseline path's
				// sort-after-fold convention and so renders
				// stably regardless of cell iteration order.
				sort.Strings(srcsSel[arm])
			}
		}
		hdrsSel = nil
	}

	// FUSE-sources path: rewrite src + hdr paths to @src_<key>//:
	// labels so project B compiles against digest-referenced
	// inputs rather than relative paths. The `@…//:<path>` form
	// preserves the path exactly (no leading slash) — Bazel's
	// label parser handles it. Per-platform delta arms get the
	// same rewrite for the same reason.
	if opts.SourceKey != "" {
		srcs = prefixWithSourceLabel(srcs, opts.SourceKey)
		hdrs = prefixWithSourceLabel(hdrs, opts.SourceKey)
		srcsSel = prefixSelectWithSourceLabel(srcsSel, opts.SourceKey)
		hdrsSel = prefixSelectWithSourceLabel(hdrsSel, opts.SourceKey)
	}

	v := ccView{
		RuleKind:               t.Kind.String(),
		Name:                   t.Name,
		SrcsExpr:               attrExpr(srcs, srcsSel),
		HdrsExpr:               attrExpr(hdrs, hdrsSel),
		IncludesExpr:           attrExpr(includes, perPlatformAttr(t, "includes")),
		IncludePrefix:          t.IncludePrefix,
		StripIncludePrefix:     t.StripIncludePrefix,
		CoptsExpr:              attrExpr(copts, perPlatformAttr(t, "copts")),
		DefinesExpr:            attrExpr(defines, perPlatformAttr(t, "defines")),
		LinkoptsExpr:           attrExpr(linkopts, perPlatformAttr(t, "linkopts")),
		DepsExpr:               attrExpr(deps, perPlatformAttr(t, "deps")),
		ImplementationDepsExpr: attrExpr(implementationDeps, perPlatformAttr(t, "implementation_deps")),
		Linkstatic:             t.Linkstatic,
		Alwayslink:             t.Alwayslink,
		Tags:                   sortedCopy(t.Tags),
		Visibility:             nonDefaultVisibility(t.Visibility),
	}
	if t.Kind == ir.KindCCTest {
		v.Args = append([]string(nil), t.TestArgs...) // preserve order; arg order matters
		v.Data = sortedCopy(t.TestData)
		if t.TestTimeout > 0 {
			v.Timeout = formatBazelDuration(t.TestTimeout)
		}
		if len(t.TestEnv) > 0 {
			v.Env = make(map[string]string, len(t.TestEnv))
			for _, kv := range t.TestEnv {
				if i := strings.IndexByte(kv, '='); i >= 0 {
					v.Env[kv[:i]] = kv[i+1:]
				}
			}
		}
	}
	return ccRuleTmpl.Execute(w, v)
}

// perPlatformScalarAttr returns the per-platform scalar delta map
// for the named attribute. Nil-safe: returns nil when the IR
// target has no PerPlatformScalar map or no entry for the
// requested name. Used by emitCCImport for static_library /
// shared_library, which are single-string attrs (cc_import's
// path attrs) that fold differently from the list-shaped
// PerPlatform.
func perPlatformScalarAttr(t ir.Target, name string) map[string]string {
	if len(t.PerPlatformScalar) == 0 {
		return nil
	}
	m, ok := t.PerPlatformScalar[name]
	if !ok || len(m) == 0 {
		return nil
	}
	out := make(map[string]string, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

// scalarAttrExpr renders a single-string cc-rule attribute's
// value. Returns:
//
//   - "" when both flat and sel are empty (caller omits the
//     attribute entirely — cc_import targets that only carry one
//     of static_library / shared_library leave the other empty).
//   - the quoted literal when sel is empty (single-platform
//     shape; byte-identical to the pre-PerPlatformScalar
//     emission).
//   - a `select({...})` block with a trailing
//     `"//conditions:default": None` arm when sel is non-empty.
//     Unlike the list case there's no `<flat> + select()` form
//     (scalars don't compose under "+"), but the default arm IS
//     present so in-matrix platforms without a value for this
//     attribute fall through to "attribute unset" rather than
//     hitting a missing-arm analysis error. The partial-platform
//     cc_import case — linux has only static_library, darwin has
//     only shared_library — needs this: a build for darwin sees
//     `static_library = select({linux: "...", "//conditions:default": None})`
//     and Bazel treats static_library as unset (cc_import's
//     default), the right outcome instead of an analysis error.
//     Out-of-matrix platforms also resolve to None (attribute
//     unset), which matches the "this target doesn't apply
//     outside the declared matrix" semantic.
func scalarAttrExpr(flat string, sel map[string]string) string {
	hasSel := len(sel) > 0
	hasFlat := flat != ""
	if !hasSel && !hasFlat {
		return ""
	}
	if !hasSel {
		return fmt.Sprintf("%q", flat)
	}
	keys := make([]string, 0, len(sel))
	for k := range sel {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b bytes.Buffer
	b.WriteString("select({\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "        %q: %q,\n", k, sel[k])
	}
	b.WriteString(`        "//conditions:default": None,` + "\n")
	b.WriteString("    })")
	return b.String()
}

// perPlatformAttr returns the per-platform delta map for the
// named attribute. Nil-safe: returns nil when the IR target has
// no PerPlatform map at all or no entry for the requested name.
// The returned map is a shallow copy so emit-time mutations
// (the cc_binary hdrs→srcs fold) don't bleed back into the
// caller's IR.
func perPlatformAttr(t ir.Target, name string) map[string][]string {
	if len(t.PerPlatform) == 0 {
		return nil
	}
	m, ok := t.PerPlatform[name]
	if !ok || len(m) == 0 {
		return nil
	}
	out := make(map[string][]string, len(m))
	for k, v := range m {
		out[k] = append([]string(nil), v...)
	}
	return out
}

// prefixSelectWithSourceLabel applies prefixWithSourceLabel to
// every arm of a select()-shaped delta map. Returns nil for nil
// input so a "no delta" signal stays a "no delta" signal.
func prefixSelectWithSourceLabel(sel map[string][]string, key string) map[string][]string {
	if sel == nil {
		return nil
	}
	out := make(map[string][]string, len(sel))
	for arm, items := range sel {
		out[arm] = prefixWithSourceLabel(items, key)
	}
	return out
}

// prefixWithSourceLabel maps relative source paths to
// @src_<key>//:tree_dir/<path> Bazel labels. The tree_dir/
// segment matches the repo rule's layout: rules/sources.bzl's
// _src_repo_impl ctx.symlinks the FUSE mount under tree_dir/
// inside the @src_<key>// repo and exports every path under
// it via exports_files(glob(["tree_dir/**"])). The label form
// preserves the relative path exactly under that prefix.
//
// Returns a fresh slice so the caller's view stays untouched on
// the legacy (non-fuse) path.
func prefixWithSourceLabel(paths []string, key string) []string {
	if len(paths) == 0 {
		return paths
	}
	out := make([]string, len(paths))
	for i, p := range paths {
		out[i] = "@src_" + key + "//:tree_dir/" + p
	}
	return out
}

// formatBazelDuration renders a Go time.Duration as a Bazel-accepted
// timeout string. Bazel accepts "Ns", "Nm", "Nh"; we round to the
// largest unit that doesn't lose precision.
func formatBazelDuration(d time.Duration) string {
	switch {
	case d%time.Hour == 0:
		return fmt.Sprintf("%dh", d/time.Hour)
	case d%time.Minute == 0:
		return fmt.Sprintf("%dm", d/time.Minute)
	default:
		return fmt.Sprintf("%ds", d/time.Second)
	}
}

func emitGenrule(w *bytes.Buffer, t ir.Target) error {
	v := genruleView{
		Name:       t.Name,
		Srcs:       sortedCopy(t.Srcs),
		Outs:       sortedCopy(t.GenruleOuts),
		Tools:      sortedCopy(t.GenruleTools),
		CmdLiteral: fmt.Sprintf("%q", t.GenruleCmd),
		Tags:       sortedCopy(t.Tags),
		Visibility: nonDefaultVisibility(t.Visibility),
	}
	return genruleTmpl.Execute(w, v)
}

func sortedCopy(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}

// strDict renders a Go map[string]string as a Starlark dict literal,
// keys sorted for byte-stable output. Empty maps render as "{}".
func strDict(m map[string]string) string {
	if len(m) == 0 {
		return "{}"
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var single bytes.Buffer
	single.WriteByte('{')
	for i, k := range keys {
		if i > 0 {
			single.WriteString(", ")
		}
		fmt.Fprintf(&single, "%q: %q", k, m[k])
	}
	single.WriteByte('}')
	if single.Len() <= 60 {
		return single.String()
	}
	var multi bytes.Buffer
	multi.WriteString("{\n")
	for _, k := range keys {
		fmt.Fprintf(&multi, "        %q: %q,\n", k, m[k])
	}
	multi.WriteString("    }")
	return multi.String()
}

// strList renders a Go []string as a Starlark list literal:
//
//	["a", "b"]                       (single-line if total <= 60 chars)
//	[
//	    "a",
//	    "b",
//	]                                 (multi-line otherwise)
func strList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	// single-line trial
	var single bytes.Buffer
	single.WriteByte('[')
	for i, s := range items {
		if i > 0 {
			single.WriteString(", ")
		}
		single.WriteByte('"')
		single.WriteString(s)
		single.WriteByte('"')
	}
	single.WriteByte(']')
	if single.Len() <= 60 {
		return single.String()
	}
	// multi-line
	var multi bytes.Buffer
	multi.WriteString("[\n")
	for _, s := range items {
		fmt.Fprintf(&multi, "        %q,\n", s)
	}
	multi.WriteString("    ]")
	return multi.String()
}

// attrExpr renders one cc-rule attribute's value combining a flat
// baseline list with optional per-platform deltas. Returns:
//
//   - "" when both flat and sel are empty (caller omits the
//     attribute entirely)
//   - strList(flat) when sel is empty (existing single-platform
//     behaviour, byte-identical to the pre-PerPlatform shape)
//   - "select({...})" when only sel is non-empty (no baseline
//     items shared across every platform)
//   - "<flat> + select({...})" when both are non-empty
//
// The select() block always carries a "//conditions:default": []
// arm so a Bazel build under a platform not in the select keys
// resolves to an empty list rather than failing analysis. Arm
// keys are emitted in sorted order so the rendered BUILD.bazel
// is byte-stable across runs (map iteration is randomized).
//
// Arm-list contents are emitted in the caller-supplied order.
// elementfold owns the per-attribute ordering convention: it
// sorts order-insensitive attrs (srcs, hdrs, includes, defines,
// deps) lexicographically and preserves cells' original sequence
// for order-sensitive attrs (copts, linkopts). emit-time
// fan-in (e.g. cc_binary's hdrs→srcs arm merge) is responsible
// for sorting its own merged arms before passing them in.
func attrExpr(flat []string, sel map[string][]string) string {
	hasSel := len(sel) > 0
	hasFlat := len(flat) > 0
	if !hasSel && !hasFlat {
		return ""
	}
	flatPart := ""
	if hasFlat {
		flatPart = strList(flat)
	}
	if !hasSel {
		return flatPart
	}
	keys := make([]string, 0, len(sel))
	for k := range sel {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b bytes.Buffer
	b.WriteString("select({\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "        %q: %s,\n", k, indentArmList(sel[k]))
	}
	b.WriteString(`        "//conditions:default": [],` + "\n")
	b.WriteString("    })")

	if hasFlat {
		return flatPart + " + " + b.String()
	}
	return b.String()
}

// indentArmList renders a select() arm's value as a Starlark
// list literal indented for a select({}) block at the cc-rule
// attribute level (8 spaces leading on continuation lines, with
// the closing bracket lining up with the arm's key column).
// Empty list → "[]" inline; non-empty → multi-line so each
// item gets its own line, regardless of brevity, because the
// surrounding select() is already multi-line and a single-line
// arm would visually clash.
//
// Items are rendered in the caller-supplied order: the
// elementfold layer already produces arms in the right order
// per attribute (lexicographic for srcs/hdrs/etc., original
// sequence for order-sensitive copts/linkopts), and any
// emit-time fan-in (e.g. cc_binary's hdrs→srcs fold) sorts
// its merged arm explicitly before passing it down. Sorting
// unconditionally here would re-order copts/linkopts deltas
// out of the sequence the operator wrote.
func indentArmList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	var b bytes.Buffer
	b.WriteString("[\n")
	for _, s := range items {
		fmt.Fprintf(&b, "            %q,\n", s)
	}
	b.WriteString("        ]")
	return b.String()
}
