// Package bazel emits a BUILD.bazel file from the IR.
//
// M1 uses text/template for stable, easy-to-diff output and zero external
// deps. The plan calls for a buildtools-AST spike in week 1; if it's adopted,
// it replaces the template here without changing the Emit signature.
//
// Output is deterministic: every list attribute is sorted before emission.
package bazel

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/sstriker/cmake-to-bazel/converter/internal/ir"
)

// header is intentionally path-free so the emitted BUILD.bazel is
// byte-identical across runs, machines, and per-orchestration tmpdirs.
// The element / codebase the file belongs to is implicit in its
// on-disk location (out/elements/<name>/BUILD.bazel for orchestrator
// runs; whatever --out-build the operator passed for standalone runs).
const header = `# Generated by convert-element. DO NOT EDIT.

`

// ccRuleLoads maps each Kind to its rules_cc load symbol. Bazel 9
// removed cc_library/cc_binary/cc_import from the global namespace;
// every emitted BUILD.bazel using one of these rules must `load()`
// it explicitly. Older Bazels accept the load + load-less form alike.
var ccRuleLoads = map[ir.Kind]string{
	ir.KindCCLibrary:   "cc_library",
	ir.KindCCBinary:    "cc_binary",
	ir.KindCCImport:    "cc_import",
	ir.KindCCInterface: "cc_library",
	ir.KindCCTest:      "cc_test",
}

// emitLoad writes a single `load("@rules_cc//cc:defs.bzl", ...)` line
// covering every cc_* symbol used by pkg's targets. Symbols are sorted
// for byte-stability. Returns nothing if pkg has no cc_* targets.
func emitLoad(buf *bytes.Buffer, pkg *ir.Package) {
	used := map[string]struct{}{}
	for _, t := range pkg.Targets {
		if sym, ok := ccRuleLoads[t.Kind]; ok {
			used[sym] = struct{}{}
		}
	}
	if len(used) == 0 {
		return
	}
	syms := make([]string, 0, len(used))
	for s := range used {
		syms = append(syms, s)
	}
	sort.Strings(syms)
	buf.WriteString(`load("@rules_cc//cc:defs.bzl"`)
	for _, s := range syms {
		fmt.Fprintf(buf, ", %q", s)
	}
	buf.WriteString(")\n\n")
}

// Options tunes the BUILD.bazel emission. Zero-value Options
// preserves the legacy relative-path emission.
type Options struct {
	// SourceKey, when non-empty, prefixes every source path in
	// emitted cc_library/cc_binary/cc_test `srcs = [...]` with
	// "@src_<SourceKey>//:" so project B references the bytes
	// by digest-stable Bazel label rather than by local
	// filesystem path. Used by the FUSE-sources route to keep
	// project B's compile actions BwoB without a project-B-side
	// FUSE mount of its own.
	SourceKey string
}

// Emit returns the contents of a BUILD.bazel file for pkg using
// default Options.
func Emit(pkg *ir.Package) ([]byte, error) {
	return EmitWithOptions(pkg, Options{})
}

// EmitWithOptions is the configurable form of Emit.
func EmitWithOptions(pkg *ir.Package, opts Options) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(header)
	emitLoad(&buf, pkg)

	for i, t := range pkg.Targets {
		if i > 0 {
			buf.WriteString("\n")
		}
		if t.Kind == ir.KindGenrule {
			if err := emitGenrule(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindCCImport {
			if err := emitCCImport(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if t.Kind == ir.KindShBinary {
			if err := emitShBinary(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if err := emitCCTargetWithOptions(&buf, t, opts); err != nil {
			return nil, err
		}
	}
	return buf.Bytes(), nil
}

var ccRuleTmpl = template.Must(template.New("rule").Funcs(template.FuncMap{
	"strList": strList,
	"strDict": strDict,
}).Parse(`{{.RuleKind}}(
    name = "{{.Name}}",
{{- if .SrcsExpr}}
    srcs = {{.SrcsExpr}},
{{- end}}
{{- if .HdrsExpr}}
    hdrs = {{.HdrsExpr}},
{{- end}}
{{- if .IncludesExpr}}
    includes = {{.IncludesExpr}},
{{- end}}
{{- if .CoptsExpr}}
    copts = {{.CoptsExpr}},
{{- end}}
{{- if .DefinesExpr}}
    defines = {{.DefinesExpr}},
{{- end}}
{{- if .LinkoptsExpr}}
    linkopts = {{.LinkoptsExpr}},
{{- end}}
{{- if .DepsExpr}}
    deps = {{.DepsExpr}},
{{- end}}
{{- if .Data}}
    data = {{strList .Data}},
{{- end}}
{{- if .Args}}
    args = {{strList .Args}},
{{- end}}
{{- if .Env}}
    env = {{strDict .Env}},
{{- end}}
{{- if .Timeout}}
    timeout = "{{.Timeout}}",
{{- end}}
{{- if .Linkstatic}}
    linkstatic = True,
{{- end}}
{{- if .Alwayslink}}
    alwayslink = True,
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// ccImportTmpl renders cc_import. Distinct from the generic
// cc_library / cc_binary template because cc_import's
// attribute set is fundamentally different — it wraps a
// pre-built archive / shared object (StaticLibrary /
// SharedLibrary as single-file label refs) plus optional hdrs;
// no srcs / copts / defines / deps.
var ccImportTmpl = template.Must(template.New("cc_import").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`cc_import(
    name = "{{.Name}}",
{{- if .StaticLibrary}}
    static_library = "{{.StaticLibrary}}",
{{- end}}
{{- if .SharedLibrary}}
    shared_library = "{{.SharedLibrary}}",
{{- end}}
{{- if .Hdrs}}
    hdrs = {{strList .Hdrs}},
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// shBinaryTmpl renders sh_binary. Bazel's sh_binary expects a
// single-element srcs (the executable) — no hdrs, no copts.
// Used by the kind:cmake round-2 fallback's per-target stubs
// for EXECUTABLE targets, where the placeholder references
// the installed binary path directly.
var shBinaryTmpl = template.Must(template.New("sh_binary").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`sh_binary(
    name = "{{.Name}}",
    srcs = {{strList .Srcs}},
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

var genruleTmpl = template.Must(template.New("genrule").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`genrule(
    name = "{{.Name}}",
{{- if .Srcs}}
    srcs = {{strList .Srcs}},
{{- end}}
    outs = {{strList .Outs}},
    cmd = {{.CmdLiteral}},
{{- if .Tools}}
    tools = {{strList .Tools}},
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// ccView projects ir.Target into the cc-rule template. The
// *Expr fields are pre-rendered attribute values: each carries
// either a flat Starlark list literal (when the IR target has
// no PerPlatform deltas for that attribute) or a
// "<flat> + select({...})" / "select({...})" composite (when
// the per-element multi-platform fold populated the deltas).
// Pre-rendering in Go keeps the template free of conditional
// list-vs-select logic — the template just emits the raw
// expression. An empty *Expr signals "omit this attribute"
// (the template's `{{- if }}` guard does the right thing).
//
// Test-only fields (Args, Env, Timeout, Data) stay zero except
// when RuleKind == "cc_test".
type ccView struct {
	RuleKind     string
	Name         string
	SrcsExpr     string
	HdrsExpr     string
	IncludesExpr string
	CoptsExpr    string
	DefinesExpr  string
	LinkoptsExpr string
	DepsExpr     string
	Linkstatic   bool
	Alwayslink   bool
	Tags         []string
	Visibility   []string

	// cc_test-only.
	Args    []string
	Env     map[string]string
	Timeout string // pre-formatted Bazel duration ("30s", "5m"), empty = unset
	Data    []string
}

type genruleView struct {
	Name       string
	Srcs       []string
	Outs       []string
	Tools      []string
	CmdLiteral string // already-quoted Starlark string literal
	Tags       []string
	Visibility []string
}

// ccImportView projects ir.Target into the cc_import template.
type ccImportView struct {
	Name          string
	StaticLibrary string
	SharedLibrary string
	Hdrs          []string
	Tags          []string
	Visibility    []string
}

// shBinaryView projects ir.Target into the sh_binary template.
type shBinaryView struct {
	Name       string
	Srcs       []string
	Tags       []string
	Visibility []string
}

func emitCCImport(w *bytes.Buffer, t ir.Target) error {
	return ccImportTmpl.Execute(w, ccImportView{
		Name:          t.Name,
		StaticLibrary: t.StaticLibrary,
		SharedLibrary: t.SharedLibrary,
		Hdrs:          sortedCopy(t.Hdrs),
		Tags:          sortedCopy(t.Tags),
		Visibility:    append([]string(nil), t.Visibility...),
	})
}

func emitShBinary(w *bytes.Buffer, t ir.Target) error {
	return shBinaryTmpl.Execute(w, shBinaryView{
		Name:       t.Name,
		Srcs:       sortedCopy(t.Srcs),
		Tags:       sortedCopy(t.Tags),
		Visibility: append([]string(nil), t.Visibility...),
	})
}

func emitCCTarget(w *bytes.Buffer, t ir.Target) error {
	return emitCCTargetWithOptions(w, t, Options{})
}

func emitCCTargetWithOptions(w *bytes.Buffer, t ir.Target, opts Options) error {
	// Compute the per-attribute baselines first (matching the
	// existing single-platform sort/order conventions), then fold
	// in any per-platform deltas. cc_binary / cc_test fold their
	// hdrs into srcs before rendering; the FUSE source-label
	// rewrite applies after that fold. PerPlatform deltas are
	// rewritten with the same source-label prefix where they
	// describe per-platform srcs/hdrs.
	srcs := sortedCopy(t.Srcs)
	hdrs := sortedCopy(t.Hdrs)
	includes := sortedCopy(t.Includes)
	copts := append([]string(nil), t.Copts...) // preserve order; flag order matters
	defines := sortedCopy(t.Defines)
	linkopts := append([]string(nil), t.LinkOpts...) // preserve order
	deps := sortedCopy(t.Deps)

	// cc_binary doesn't accept `hdrs` (Bazel 9 errors out where
	// older versions silently ignored). Fold any header into srcs
	// so the translation unit still sees them, even though that's
	// the rules_cc convention for binaries. cc_test inherits
	// cc_binary's stricture, so apply the same fold there.
	srcsSel := perPlatformAttr(t, "srcs")
	hdrsSel := perPlatformAttr(t, "hdrs")
	if (t.Kind == ir.KindCCBinary || t.Kind == ir.KindCCTest) && (len(hdrs) > 0 || len(hdrsSel) > 0) {
		srcs = append(srcs, hdrs...)
		sort.Strings(srcs)
		hdrs = nil
		// Per-platform hdrs deltas fold into the corresponding
		// srcs delta arms so cc_binary/cc_test still see those
		// headers as compilation inputs in their respective
		// platforms.
		if len(hdrsSel) > 0 {
			if srcsSel == nil {
				srcsSel = map[string][]string{}
			}
			for arm, items := range hdrsSel {
				srcsSel[arm] = append(srcsSel[arm], items...)
			}
		}
		hdrsSel = nil
	}

	// FUSE-sources path: rewrite src + hdr paths to @src_<key>//:
	// labels so project B compiles against digest-referenced
	// inputs rather than relative paths. The `@…//:<path>` form
	// preserves the path exactly (no leading slash) — Bazel's
	// label parser handles it. Per-platform delta arms get the
	// same rewrite for the same reason.
	if opts.SourceKey != "" {
		srcs = prefixWithSourceLabel(srcs, opts.SourceKey)
		hdrs = prefixWithSourceLabel(hdrs, opts.SourceKey)
		srcsSel = prefixSelectWithSourceLabel(srcsSel, opts.SourceKey)
		hdrsSel = prefixSelectWithSourceLabel(hdrsSel, opts.SourceKey)
	}

	v := ccView{
		RuleKind:     t.Kind.String(),
		Name:         t.Name,
		SrcsExpr:     attrExpr(srcs, srcsSel),
		HdrsExpr:     attrExpr(hdrs, hdrsSel),
		IncludesExpr: attrExpr(includes, perPlatformAttr(t, "includes")),
		CoptsExpr:    attrExpr(copts, perPlatformAttr(t, "copts")),
		DefinesExpr:  attrExpr(defines, perPlatformAttr(t, "defines")),
		LinkoptsExpr: attrExpr(linkopts, perPlatformAttr(t, "linkopts")),
		DepsExpr:     attrExpr(deps, perPlatformAttr(t, "deps")),
		Linkstatic:   t.Linkstatic,
		Alwayslink:   t.Alwayslink,
		Tags:         sortedCopy(t.Tags),
		Visibility:   append([]string(nil), t.Visibility...),
	}
	if t.Kind == ir.KindCCTest {
		v.Args = append([]string(nil), t.TestArgs...) // preserve order; arg order matters
		v.Data = sortedCopy(t.TestData)
		if t.TestTimeout > 0 {
			v.Timeout = formatBazelDuration(t.TestTimeout)
		}
		if len(t.TestEnv) > 0 {
			v.Env = make(map[string]string, len(t.TestEnv))
			for _, kv := range t.TestEnv {
				if i := strings.IndexByte(kv, '='); i >= 0 {
					v.Env[kv[:i]] = kv[i+1:]
				}
			}
		}
	}
	return ccRuleTmpl.Execute(w, v)
}

// perPlatformAttr returns the per-platform delta map for the
// named attribute. Nil-safe: returns nil when the IR target has
// no PerPlatform map at all or no entry for the requested name.
// The returned map is a shallow copy so emit-time mutations
// (the cc_binary hdrs→srcs fold) don't bleed back into the
// caller's IR.
func perPlatformAttr(t ir.Target, name string) map[string][]string {
	if len(t.PerPlatform) == 0 {
		return nil
	}
	m, ok := t.PerPlatform[name]
	if !ok || len(m) == 0 {
		return nil
	}
	out := make(map[string][]string, len(m))
	for k, v := range m {
		out[k] = append([]string(nil), v...)
	}
	return out
}

// prefixSelectWithSourceLabel applies prefixWithSourceLabel to
// every arm of a select()-shaped delta map. Returns nil for nil
// input so a "no delta" signal stays a "no delta" signal.
func prefixSelectWithSourceLabel(sel map[string][]string, key string) map[string][]string {
	if sel == nil {
		return nil
	}
	out := make(map[string][]string, len(sel))
	for arm, items := range sel {
		out[arm] = prefixWithSourceLabel(items, key)
	}
	return out
}

// prefixWithSourceLabel maps relative source paths to
// @src_<key>//:tree_dir/<path> Bazel labels. The tree_dir/
// segment matches the repo rule's layout: rules/sources.bzl's
// _src_repo_impl ctx.symlinks the FUSE mount under tree_dir/
// inside the @src_<key>// repo and exports every path under
// it via exports_files(glob(["tree_dir/**"])). The label form
// preserves the relative path exactly under that prefix.
//
// Returns a fresh slice so the caller's view stays untouched on
// the legacy (non-fuse) path.
func prefixWithSourceLabel(paths []string, key string) []string {
	if len(paths) == 0 {
		return paths
	}
	out := make([]string, len(paths))
	for i, p := range paths {
		out[i] = "@src_" + key + "//:tree_dir/" + p
	}
	return out
}

// formatBazelDuration renders a Go time.Duration as a Bazel-accepted
// timeout string. Bazel accepts "Ns", "Nm", "Nh"; we round to the
// largest unit that doesn't lose precision.
func formatBazelDuration(d time.Duration) string {
	switch {
	case d%time.Hour == 0:
		return fmt.Sprintf("%dh", d/time.Hour)
	case d%time.Minute == 0:
		return fmt.Sprintf("%dm", d/time.Minute)
	default:
		return fmt.Sprintf("%ds", d/time.Second)
	}
}

func emitGenrule(w *bytes.Buffer, t ir.Target) error {
	v := genruleView{
		Name:       t.Name,
		Srcs:       sortedCopy(t.Srcs),
		Outs:       sortedCopy(t.GenruleOuts),
		Tools:      sortedCopy(t.GenruleTools),
		CmdLiteral: fmt.Sprintf("%q", t.GenruleCmd),
		Tags:       sortedCopy(t.Tags),
		Visibility: append([]string(nil), t.Visibility...),
	}
	return genruleTmpl.Execute(w, v)
}

func sortedCopy(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}

// strDict renders a Go map[string]string as a Starlark dict literal,
// keys sorted for byte-stable output. Empty maps render as "{}".
func strDict(m map[string]string) string {
	if len(m) == 0 {
		return "{}"
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var single bytes.Buffer
	single.WriteByte('{')
	for i, k := range keys {
		if i > 0 {
			single.WriteString(", ")
		}
		fmt.Fprintf(&single, "%q: %q", k, m[k])
	}
	single.WriteByte('}')
	if single.Len() <= 60 {
		return single.String()
	}
	var multi bytes.Buffer
	multi.WriteString("{\n")
	for _, k := range keys {
		fmt.Fprintf(&multi, "        %q: %q,\n", k, m[k])
	}
	multi.WriteString("    }")
	return multi.String()
}

// strList renders a Go []string as a Starlark list literal:
//
//	["a", "b"]                       (single-line if total <= 60 chars)
//	[
//	    "a",
//	    "b",
//	]                                 (multi-line otherwise)
func strList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	// single-line trial
	var single bytes.Buffer
	single.WriteByte('[')
	for i, s := range items {
		if i > 0 {
			single.WriteString(", ")
		}
		single.WriteByte('"')
		single.WriteString(s)
		single.WriteByte('"')
	}
	single.WriteByte(']')
	if single.Len() <= 60 {
		return single.String()
	}
	// multi-line
	var multi bytes.Buffer
	multi.WriteString("[\n")
	for _, s := range items {
		fmt.Fprintf(&multi, "        %q,\n", s)
	}
	multi.WriteString("    ]")
	return multi.String()
}

// attrExpr renders one cc-rule attribute's value combining a flat
// baseline list with optional per-platform deltas. Returns:
//
//   - "" when both flat and sel are empty (caller omits the
//     attribute entirely)
//   - strList(flat) when sel is empty (existing single-platform
//     behaviour, byte-identical to the pre-PerPlatform shape)
//   - "select({...})" when only sel is non-empty (no baseline
//     items shared across every platform)
//   - "<flat> + select({...})" when both are non-empty
//
// The select() block always carries a "//conditions:default": []
// arm so a Bazel build under a platform not in the select keys
// resolves to an empty list rather than failing analysis. Arm
// keys are emitted in sorted order so the rendered BUILD.bazel
// is byte-stable across runs (map iteration is randomized).
//
// The arm-list contents are sorted within each arm via the same
// sortedCopy convention the rest of emit uses; callers shouldn't
// rely on input order surviving.
func attrExpr(flat []string, sel map[string][]string) string {
	hasSel := len(sel) > 0
	hasFlat := len(flat) > 0
	if !hasSel && !hasFlat {
		return ""
	}
	flatPart := ""
	if hasFlat {
		flatPart = strList(flat)
	}
	if !hasSel {
		return flatPart
	}
	keys := make([]string, 0, len(sel))
	for k := range sel {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b bytes.Buffer
	b.WriteString("select({\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "        %q: %s,\n", k, indentArmList(sel[k]))
	}
	b.WriteString(`        "//conditions:default": [],` + "\n")
	b.WriteString("    })")

	if hasFlat {
		return flatPart + " + " + b.String()
	}
	return b.String()
}

// indentArmList renders a select() arm's value as a Starlark
// list literal indented for a select({}) block at the cc-rule
// attribute level (8 spaces leading on continuation lines, with
// the closing bracket lining up with the arm's key column).
// Empty list → "[]" inline; non-empty → multi-line so each
// item gets its own line, regardless of brevity, because the
// surrounding select() is already multi-line and a single-line
// arm would visually clash.
func indentArmList(items []string) string {
	items = append([]string(nil), items...)
	sort.Strings(items)
	if len(items) == 0 {
		return "[]"
	}
	var b bytes.Buffer
	b.WriteString("[\n")
	for _, s := range items {
		fmt.Fprintf(&b, "            %q,\n", s)
	}
	b.WriteString("        ]")
	return b.String()
}
