/* foo_value() is generated by tool.py into a temp dir and relocated into
 * OUTPUT_DIR by a `cmake -E copy_if_different` subprocess in the cmake -P
 * wrapper, as an undeclared side effect of the stamp edge. */
#include "foo.h"

int main(void) {
	return foo_value() == 7 ? 0 : 1;
}
