package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeAOut(t *testing.T, projectA, name, file, content string) {
	t.Helper()
	p := filepath.Join(projectA, "bazel-bin", "elements", name, file)
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

const optionsBody = `# Generated by convert-element-cmake. DO NOT EDIT.
load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")

bool_flag(
    name = "foo_feature",
    build_setting_default = True,
    visibility = ["//visibility:public"],
)
`

// TestRun_StagesOptionsPackage: an element whose converter produced a
// substantive options-BUILD.bazel gets it staged as project B's root
// //options package; header-only placeholders (nothing lifted) don't.
func TestRun_StagesOptionsPackage(t *testing.T) {
	projectA, projectB := mkProject(t,
		map[string]string{"libfoo": "cc_library(name='x')", "libbar": "cc_library(name='y')"},
		nil)
	writeAOut(t, projectA, "libfoo", "options-BUILD.bazel", optionsBody)
	writeAOut(t, projectA, "libbar", "options-BUILD.bazel", "# Generated by convert-element-cmake. DO NOT EDIT.\n#\n# No options lifted.\n")

	changed, err := run(args{projectA: projectA, projectB: projectB})
	if err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(projectB, "options", "BUILD.bazel"))
	if err != nil {
		t.Fatalf("//options package not staged: %v", err)
	}
	if string(got) != optionsBody {
		t.Errorf("staged //options body:\n%s", got)
	}
	found := false
	for _, c := range changed {
		if c == "options" {
			found = true
		}
	}
	if !found {
		t.Errorf("changed set missing options: %v", changed)
	}

	// Second run: byte-identical → not reported changed.
	changed, err = run(args{projectA: projectA, projectB: projectB})
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range changed {
		if c == "options" {
			t.Errorf("unchanged //options reported changed: %v", changed)
		}
	}
}

// TestRun_OptionsDivergenceFirstWins: two elements with differing
// substantive packages — the first (sorted) element's package stages.
func TestRun_OptionsDivergenceFirstWins(t *testing.T) {
	projectA, projectB := mkProject(t,
		map[string]string{"aaa": "cc_library(name='x')", "zzz": "cc_library(name='y')"},
		nil)
	writeAOut(t, projectA, "aaa", "options-BUILD.bazel", optionsBody)
	writeAOut(t, projectA, "zzz", "options-BUILD.bazel", strings.Replace(optionsBody, "True", "False", 1))

	if _, err := run(args{projectA: projectA, projectB: projectB}); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(projectB, "options", "BUILD.bazel"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "build_setting_default = True") {
		t.Errorf("first element's package must win:\n%s", got)
	}
}

// TestRun_NoOptionsNoPackage: without any options-BUILD.bazel, no
// //options package appears.
func TestRun_NoOptionsNoPackage(t *testing.T) {
	projectA, projectB := mkProject(t,
		map[string]string{"libfoo": "cc_library(name='x')"}, nil)
	if _, err := run(args{projectA: projectA, projectB: projectB}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(projectB, "options", "BUILD.bazel")); !os.IsNotExist(err) {
		t.Errorf("no //options package expected: %v", err)
	}
}
