#!/usr/bin/env python3
# Trivial generator: emits a header that records the build's
# argument list. Used by the execute-process-file-producing
# fixture to exercise the converter's lifter for
# OUTPUT_FILE-redirected execute_process calls.
import sys

print("/* generated by scripts/gen.py */")
print('#define GEN_INPUT "{}"'.format(sys.argv[1] if len(sys.argv) > 1 else ""))
print("#define GEN_VERSION 1")
