package configsettings

import (
	"strings"
	"testing"
)

func TestEmit_Basic(t *testing.T) {
	got := string(Emit([]string{"Release", "Debug", "RelWithDebInfo"}, "Release"))

	// Header + skylib load present.
	for _, want := range []string{
		"# Generated by convert-element-cmake. DO NOT EDIT.",
		`load("@bazel_skylib//rules:common_settings.bzl", "string_flag")`,
		`name = "build_type"`,
		`build_setting_default = "release"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("output missing %q\n---\n%s", want, got)
		}
	}

	// One config_setting per (lowercased) config, keyed on the flag.
	for _, name := range []string{"debug", "release", "relwithdebinfo"} {
		cs := "config_setting(\n    name = \"" + name + "\",\n    flag_values = {\":build_type\": \"" + name + "\"},"
		if !strings.Contains(got, cs) {
			t.Errorf("missing config_setting for %q\n---\n%s", name, got)
		}
	}

	// config_setting names must match lower's configLabel lowercasing
	// exactly (the select arms are //config:<lowercased>).
	if strings.Contains(got, `name = "Debug"`) || strings.Contains(got, `name = "Release"`) {
		t.Errorf("config_setting names should be lowercased\n---\n%s", got)
	}
}

func TestEmit_ByteStable_OrderIndependent(t *testing.T) {
	a := Emit([]string{"Release", "Debug", "RelWithDebInfo"}, "Release")
	b := Emit([]string{"RelWithDebInfo", "release", "Debug"}, "RELEASE")
	if string(a) != string(b) {
		t.Errorf("Emit not order/case-stable:\n--- a ---\n%s\n--- b ---\n%s", a, b)
	}
}

func TestEmit_FewerThanTwoConfigs_Nil(t *testing.T) {
	if Emit(nil, "") != nil {
		t.Error("nil configs should yield nil")
	}
	if Emit([]string{"Release"}, "Release") != nil {
		t.Error("single config has no multi-config select to back; want nil")
	}
	// Duplicates that collapse to one distinct name also yield nil.
	if Emit([]string{"Release", "release"}, "Release") != nil {
		t.Error("one distinct config after lowercasing should yield nil")
	}
}

func TestEmit_DefaultNotInSet_FallsBackToFirst(t *testing.T) {
	// "fastbuild" isn't a declared config; default must still be a valid
	// flag value (one of the declared, sorted names → "debug").
	got := string(Emit([]string{"Release", "Debug"}, "fastbuild"))
	if !strings.Contains(got, `build_setting_default = "debug"`) {
		t.Errorf("default should fall back to first sorted config 'debug'\n---\n%s", got)
	}
}
