#!/bin/sh
# meta-cmake-probe-genex-duplicate-subdir.sh — render gate for the
# structural genex probe's duplicate-target-name fix.
#
# Drives convert-element-cmake with --probe-genex against
# converter/testdata/sample-projects/probe-genex-duplicate-subdir,
# which add_subdirectory()'s the SAME source dir twice into two binary
# dirs (a vendoring pattern). cmake lists that source dir twice under
# the parent's SUBDIRECTORIES property, so probe-genex.cmake's recursive
# BUILDSYSTEM_TARGETS walk collected the dir's target name twice.
#
# Pre-fix, the duplicate name made the structural probe emit two
# file(GENERATE) calls with the SAME OUTPUT path
# (cmake-to-bazel.genex/<tgt>/type.txt). cmake 3.x tolerated the
# identical-content duplicate; cmake 4 rejects it as a hard error
# ("Files to be generated by multiple different commands") and aborts
# the whole configure — so --probe-genex couldn't convert ANY project
# using this pattern on cmake 4. The fix de-duplicates the collected
# target list (list(REMOVE_DUPLICATES)) before emitting any probe.
#
# Asserts:
#   1. convert-element-cmake exits 0 with --probe-genex (cmake's
#      generation step no longer aborts on the duplicate OUTPUT).
#   2. The BUILD.bazel carries a cc_library for the lifted shared
#      library — the convert produced real output, not an empty file.
#
# Gating: skips cleanly when cmake isn't on PATH. The cmake-4-specific
# failure only reproduces on cmake >= 4, but the dedup is correct on
# every version, so the gate runs (and passes) on any cmake.

set -eu

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

if ! command -v cmake >/dev/null 2>&1; then
    echo "skip: cmake not on PATH"
    exit 0
fi

bin_dir="$repo_root/build/bin"
mkdir -p "$bin_dir"
make converter >/dev/null

fixture="$repo_root/converter/testdata/sample-projects/probe-genex-duplicate-subdir"
work_dir="$(mktemp -d)"
trap "rm -rf '$work_dir'" EXIT

out_build="$work_dir/BUILD.bazel.out"

"$bin_dir/convert-element-cmake" \
    --source-root "$fixture" \
    --out-build "$out_build" \
    --probe-genex \
    >"$work_dir/convert.stdout" 2>"$work_dir/convert.stderr" || {
    echo "FAIL: convert-element-cmake exited non-zero with --probe-genex"
    echo "   the structural probe must have emitted a duplicate file(GENERATE)"
    echo "   OUTPUT for the twice-collected target name (cmake 4 hard error)"
    sed 's/^/   stderr: /' "$work_dir/convert.stderr"
    exit 1
}

# A duplicate-OUTPUT generation error is what aborts cmake; assert the
# message never reached stderr even on a cmake that would tolerate it,
# so the gate is meaningful regardless of the local cmake version.
if grep -qF 'Files to be generated by multiple different commands' "$work_dir/convert.stderr"; then
    echo "FAIL: the structural probe emitted a duplicate file(GENERATE) OUTPUT"
    sed 's/^/   stderr: /' "$work_dir/convert.stderr"
    exit 1
fi

if ! grep -q 'cc_library(' "$out_build"; then
    echo "FAIL: expected a cc_library for the lifted shared library in BUILD.bazel"
    sed 's/^/   /' "$out_build"
    exit 1
fi

echo "ok  meta-cmake-probe-genex-duplicate-subdir: --probe-genex de-duplicates a twice-collected target name (no duplicate file(GENERATE) OUTPUT; survives cmake 4)"
