#!/bin/sh
# meta-cmake-execute-process-argv-codegen.sh — render+build gate for the
# argv-declared execute_process codegen lift.
#
# add_custom_command codegen lifts because cmake declares OUTPUT/DEPENDS
# into the ninja edge; execute_process declares nothing — but for the
# `tool <input…> <output…>` shape the contract is recoverable from the
# configure's own evidence, with NO convert-time re-execution: source-tree
# argv paths are inputs, build-dir argv paths existing on disk
# post-configure are outputs, and paths produced by earlier recoveries are
# generated inputs (chains resolve in trace order). The lift emits a
# multi-output genrule re-running the tool at Bazel build time.
#
# Fixture shapes: positional+flag operands (sort -o out in), keyed operands
# (dd if=/of=), and a two-call chain (the second sort consumes the first's
# output). Asserts the three genrules render with $(location)-wired srcs
# and outs, then bazel-builds //... and checks the generated bytes.

set -eu

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

if ! command -v cmake >/dev/null 2>&1; then
    echo "skip: cmake not on PATH"
    exit 0
fi

bin_dir="$repo_root/build/bin"
mkdir -p "$bin_dir"
make converter >/dev/null

fixture="$repo_root/converter/testdata/sample-projects/execute-process-argv-codegen"
work_dir="$(mktemp -d)"
trap "rm -rf '$work_dir'" EXIT

"$bin_dir/convert-element-cmake" \
    --source-root "$fixture" \
    --out-build "$work_dir/BUILD.bazel" \
    >"$work_dir/convert.stdout" 2>"$work_dir/convert.stderr" || {
    echo "FAIL: convert-element-cmake exited non-zero"
    sed 's/^/   stderr: /' "$work_dir/convert.stderr"
    exit 1
}

build="$work_dir/BUILD.bazel"

fail() {
    echo "FAIL: $1"
    echo "   --- BUILD.bazel ---"
    sed 's/^/   /' "$build" 2>/dev/null || true
    exit 1
}

grep -qF 'outs = ["sorted.txt"]' "$build" || fail "positional sort -o output not lifted"
grep -qF 'outs = ["copy.bin"]' "$build" || fail "keyed dd of= output not lifted"
grep -qF 'outs = ["reversed.txt"]' "$build" || fail "chained output not lifted"
grep -qF 'if=$(location raw.bin)' "$build" || fail "keyed input operand not \$(location)-wired"
grep -qF 'srcs = ["sorted.txt"]' "$build" || fail "chain's generated input not staged via srcs"
grep -qF 'cmake-codegen-execute-process-argv-outs' "$build" || fail "argv-outs audit facet missing"
grep -q "unsupported-" "$work_dir/convert.stderr" \
    && fail "converter emitted a typed refusal (all three calls should lift)"

echo "ok  meta-cmake-execute-process-argv-codegen: argv-declared in/out codegen lifted (positional, keyed, chained)"

# --- Bazel-build half ---
if command -v bazel >/dev/null; then
    BZL=bazel
elif command -v bazelisk >/dev/null; then
    BZL=bazelisk
else
    echo "ok  meta-cmake-execute-process-argv-codegen: bazel not on PATH, skipping build half"
    exit 0
fi
if ! bazel_version_out=$("$BZL" version 2>&1); then
    echo "FAIL: '$BZL version' failed:"; printf '%s\n' "$bazel_version_out" | sed 's/^/   /'; exit 1
fi
bazel_major=$(printf '%s\n' "$bazel_version_out" | awk -F': ' '/^Build label:/{print $2; exit}' | cut -d. -f1)
case "$bazel_major" in [0-9]*) ;; *) bazel_major=0 ;; esac
if [ "$bazel_major" -lt 7 ]; then
    echo "ok  meta-cmake-execute-process-argv-codegen: bazel < 7, skipping build half"
    exit 0
fi

ws="$work_dir/ws"
mkdir -p "$ws"
cp "$fixture"/words.txt "$fixture"/raw.bin "$ws/"
cp "$build" "$ws/BUILD.bazel"
cat > "$ws/MODULE.bazel" <<'EOF'
module(name = "argvcodegen", version = "0.0.0")
bazel_dep(name = "rules_cc", version = "0.0.17")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
EOF

bz_cache="$work_dir/.bzcache"
# shellcheck disable=SC2086
if ! (cd "$ws" && "$BZL" --output_user_root="$bz_cache" ${META_BAZEL_STARTUP_ARGS:-} \
        build ${META_BAZEL_BUILD_ARGS:-} //...) >"$work_dir/bazel.log" 2>&1; then
    echo "FAIL: building the argv-codegen genrules failed"
    sed 's/^/   /' "$work_dir/bazel.log"
    exit 1
fi
got=$(head -1 "$ws/bazel-bin/sorted.txt")
[ "$got" = "apple" ] || { echo "FAIL: sorted.txt head = '$got', want apple"; exit 1; }
gotr=$(head -1 "$ws/bazel-bin/reversed.txt")
[ "$gotr" = "zebra" ] || { echo "FAIL: reversed.txt head = '$gotr', want zebra (chain re-ran)"; exit 1; }
cmp -s "$ws/raw.bin" "$ws/bazel-bin/copy.bin" || { echo "FAIL: dd copy bytes differ"; exit 1; }

echo "ok  meta-cmake-execute-process-argv-codegen: the genrules re-run the tools at Bazel time with correct bytes (no cmake)"
