// Package configsettings emits the //config package BUILD content that
// backs the multi-config fold's select() arms.
//
// Phase 5 of the generator-parity uplift (ROADMAP.md). lower's
// multi-config fold projects each cmake configuration's flag / src / dep
// deltas onto //config:<name> select() arms (configLabel →
// "//config:<name-lowercased>"). Those labels must resolve to real
// config_settings for the converted BUILD to load. This package renders a
// project-level //config package: a string_flag `build_type` plus one
// config_setting per configuration, selected at build time with
// --//config:build_type=<name>.
//
// Mapping to a dedicated string_flag rather than Bazel's built-in
// compilation_mode (dbg/opt/fastbuild) keeps the config_settings 1:1 with
// cmake's build types — Release and RelWithDebInfo both map to `opt`, so
// compilation_mode would conflate them and silently drop one config's
// deltas. The flag is 1:1, lossless, and explicit.
//
// The generated BUILD is byte-stable across runs against the same
// configuration set and carries a leading attribution header.
package configsettings

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// Emit renders the //config package BUILD content for the given cmake
// configuration names. defaultConfig is the configuration the unset flag
// resolves to (typically the codemodel's primary configuration, whose
// deltas lower flattens into the rule baseline). Names are lowercased to
// match lower's configLabel (`//config:<name-lowercased>`), de-duplicated,
// and sorted for byte stability.
//
// Returns nil when fewer than two distinct configurations are supplied —
// there's no multi-config select to back, so no //config package is
// needed.
func Emit(configs []string, defaultConfig string) []byte {
	seen := map[string]bool{}
	var names []string
	for _, c := range configs {
		n := strings.ToLower(c)
		if n == "" || seen[n] {
			continue
		}
		seen[n] = true
		names = append(names, n)
	}
	if len(names) < 2 {
		return nil
	}
	sort.Strings(names)

	def := strings.ToLower(defaultConfig)
	if !seen[def] {
		// Default isn't one of the declared configs — fall back to the
		// first (sorted) name so build_setting_default is always a valid
		// value the string_flag's `values` accepts.
		def = names[0]
	}

	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString(loads)
	b.WriteString("\n")

	b.WriteString("string_flag(\n")
	b.WriteString("    name = \"build_type\",\n")
	fmt.Fprintf(&b, "    build_setting_default = %q,\n", def)
	b.WriteString("    values = [\n")
	for _, n := range names {
		fmt.Fprintf(&b, "        %q,\n", n)
	}
	b.WriteString("    ],\n")
	b.WriteString("    visibility = [\"//visibility:public\"],\n")
	b.WriteString(")\n")

	for _, n := range names {
		b.WriteString("\n")
		b.WriteString("config_setting(\n")
		fmt.Fprintf(&b, "    name = %q,\n", n)
		fmt.Fprintf(&b, "    flag_values = {\":build_type\": %q},\n", n)
		b.WriteString("    visibility = [\"//visibility:public\"],\n")
		b.WriteString(")\n")
	}
	return b.Bytes()
}

const header = `# Generated by convert-element-cmake. DO NOT EDIT.
#
# config_settings backing the multi-config fold's //config:<name>
# select() arms — one per cmake configuration passed via --build-types.
# Select a configuration at build time with --//config:build_type=<name>
# (e.g. --//config:build_type=debug). The default below is the primary
# configuration, so an unset flag reproduces the converter's baseline view.
#
# Byte-stable across runs against the same configuration set; re-generated
# whenever the operator runs convert-element-cmake --out-config-settings.

`

const loads = `load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
`
