// Package wrappergen synthesizes prebuilt-wrapper BUILD packages from
// an imports manifest and rewrites the manifest onto the wrappers —
// the mechanical form of the cc_import + cc_library idiom for
// host-install prefixes. See cmd/imports-wrapper-gen's doc for the
// operator contract; the design discussion lives on the Export.Deps
// schema doc (internal/manifest): the generator is the
// consume-and-clear party of the "Deps = unmodeled closure" invariant.
package wrappergen

import (
	"encoding/json"
	"fmt"
	"os"
	"path"
	"sort"
	"strings"

	"github.com/sstriker/buildstream-bazel/internal/manifest"
)

// headerGlobExts is the header-surface extension family the wrapper
// hdrs glob covers (matching the converter's header recognition).
var headerGlobExts = []string{"h", "hh", "hpp", "hxx", "inc", "inl", "ipp", "def"}

// Generate renders the wrapper BUILD for every selected element's
// exports and returns it together with the rewritten manifest:
// bazel_label repointed at `//<pkgPath>:<target>`, Deps cleared
// (the closure now lives on the wrapper as real Bazel deps),
// everything else preserved (link_paths / link_libraries still key the
// consumer-side fragment redirects, which must keep resolving to the
// wrapper).
//
// Per export the BUILD carries:
//
//   - cc_import `<name>_archive` over the first prefix-anchored
//     link_path (static_library / shared_library by extension),
//     omitted for archive-less (header-only / INTERFACE) exports;
//   - cc_library `<name>` — the consumer-facing wrapper — with deps on
//     its own archive plus the export's declared closure, each closure
//     label remapped onto its wrapper when it names another export's
//     OLD label (cross-element labels pass through verbatim);
//     hdrs/includes from interface_includes (defaulting to include/
//     when an archive exists, so the common layout resolves);
//   - exports with Kind == manifest.KindExecutable (protoc-shaped
//     installed programs) get a `filegroup` over their prefix-relative
//     link_paths instead — an ELF program is not a static_library, and
//     genrule tool lifts need a file-shaped label, not a cc_library.
//
// Target names derive from the export's cmake name (the part after
// the last "::", sanitized); a collision across exports is an error —
// wrapper labels are consumer-facing and must be stable. A dependency
// cycle among the selected exports' Deps is likewise an error: Bazel
// rejects cyclic deps at load time, so the generator refuses up front
// (harvested manifests are cycle-free by construction — the harvester
// breaks cycles with a warning; hand-written ones are caught here).
func Generate(im *manifest.Imports, pkgPath, element string) ([]byte, *manifest.Imports, error) {
	if im == nil {
		return nil, nil, fmt.Errorf("nil manifest")
	}
	type entry struct {
		ex   *manifest.Export
		name string
	}
	var entries []entry
	nameSeen := map[string]string{}
	oldLabelToNew := map[string]string{}
	for _, el := range im.Elements {
		if el == nil || (element != "" && el.Name != element) {
			continue
		}
		for _, ex := range el.Exports {
			if ex == nil {
				continue
			}
			name := WrapperName(ex.CMakeTarget)
			if prev, dup := nameSeen[name]; dup {
				return nil, nil, fmt.Errorf("wrapper name %q collides (%s vs %s); disambiguate the manifest", name, prev, ex.CMakeTarget)
			}
			nameSeen[name] = ex.CMakeTarget
			oldLabelToNew[ex.BazelLabel] = "//" + pkgPath + ":" + name
			entries = append(entries, entry{ex: ex, name: name})
		}
	}
	if len(entries) == 0 {
		return nil, nil, fmt.Errorf("no exports selected (element %q)", element)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].name < entries[j].name })
	exports := make([]*manifest.Export, len(entries))
	for i, e := range entries {
		exports[i] = e.ex
	}
	if err := checkDepCycles(exports, oldLabelToNew); err != nil {
		return nil, nil, err
	}

	var b strings.Builder
	b.WriteString("# Generated by imports-wrapper-gen. DO NOT EDIT.\n")
	b.WriteString("# Prebuilt wrappers: cc_import per archive + cc_library carrying the\n")
	b.WriteString("# manifest-declared closure as real Bazel deps (Export.Deps consumed\n")
	b.WriteString("# and cleared in the rewritten manifest — the invariant's generator\n")
	b.WriteString("# half). Place at the staged prefix root: archive paths are\n")
	b.WriteString("# prefix-relative.\n\n")
	b.WriteString(`load("@rules_cc//cc:defs.bzl", "cc_import", "cc_library")` + "\n\n")
	b.WriteString(`package(default_visibility = ["//visibility:public"])` + "\n")

	for _, e := range entries {
		b.WriteString("\n")
		if e.ex.Kind == manifest.KindExecutable {
			renderExecutable(&b, e.name, e.ex)
			continue
		}
		renderLibrary(&b, e.name, e.ex, oldLabelToNew)
	}

	rewritten := rewriteManifest(im, element, oldLabelToNew)
	return []byte(b.String()), rewritten, nil
}

// renderExecutable writes the wrapper for an installed program: a
// filegroup over the prefix-relative bin paths — a file-shaped target
// the genrule tool lift's label resolution can put in `tools`.
// Wrapping it as cc_import/cc_library would hand consumers an ELF
// program as a static_library.
//
// Known limits: an executable export's Deps have no filegroup slot
// and are NOT represented — fine for statically linked tools (the
// common host-install shape), but a dynamically linked tool whose
// runtime .so's live in the prefix won't have them staged into a
// genrule sandbox; that shape needs the runtime closure in srcs (or
// `data` on the consuming genrule) when it shows up. Multiple link
// paths render a multi-file filegroup, which a consumer's
// $(execpath) rejects loudly — single-path rows are the assumed
// invariant (the harvester's canonicalKey dedup folds symlink
// spellings, so multi-path executable rows shouldn't arise).
func renderExecutable(b *strings.Builder, name string, ex *manifest.Export) {
	fmt.Fprintf(b, "filegroup(\n    name = %q,\n    srcs = [\n", name)
	for _, lp := range ex.LinkPaths {
		if rel, ok := strings.CutPrefix(lp, manifest.PrefixAnchor); ok && rel != "" {
			fmt.Fprintf(b, "        %q,\n", rel)
		}
	}
	b.WriteString("    ],\n)\n")
}

// renderLibrary writes the cc_import (when an archive exists) and the
// consumer-facing cc_library wrapper for one library export.
func renderLibrary(b *strings.Builder, name string, ex *manifest.Export, oldLabelToNew map[string]string) {
	archiveRel := archivePath(ex)
	if archiveRel != "" {
		fmt.Fprintf(b, "cc_import(\n    name = %q,\n", name+"_archive")
		attr := "static_library"
		if strings.Contains(path.Base(archiveRel), ".so") || strings.HasSuffix(archiveRel, ".dylib") {
			attr = "shared_library"
		}
		fmt.Fprintf(b, "    %s = %q,\n", attr, archiveRel)
		// A cyclic static-archive SCC member: whole-archive it so every
		// object links regardless of position (cmake broke the cycle by
		// repetition / --start-group; alwayslink is the Bazel equivalent).
		// Only meaningful for a static archive.
		if ex.AlwaysLink && attr == "static_library" {
			b.WriteString("    alwayslink = True,\n")
		}
		b.WriteString("    visibility = [\"//visibility:private\"],\n)\n\n")
	}
	fmt.Fprintf(b, "cc_library(\n    name = %q,\n", name)
	incs := ex.InterfaceIncludes
	if len(incs) == 0 && archiveRel != "" {
		incs = []string{"include"}
	}
	if len(incs) > 0 {
		// The full header-ish surface, not just *.h: host-install
		// prefixes ship .inc (abseil), .hpp/.hh/.hxx/.ipp (C++), and
		// .def/.inl — and with allow_empty a too-narrow glob fails
		// SILENTLY (the wrapper builds, consumers miss textual
		// includes). Same extension family the converter's header
		// machinery recognizes.
		globs := make([]string, 0, len(incs)*len(headerGlobExts))
		for _, inc := range incs {
			for _, ext := range headerGlobExts {
				globs = append(globs, fmt.Sprintf("%q", path.Join(inc, "**", "*."+ext)))
			}
		}
		fmt.Fprintf(b, "    hdrs = glob(\n        [\n")
		for _, g := range globs {
			fmt.Fprintf(b, "            %s,\n", g)
		}
		fmt.Fprintf(b, "        ],\n        allow_empty = True,\n    ),\n")
		sorted := append([]string(nil), incs...)
		sort.Strings(sorted)
		b.WriteString("    includes = [\n")
		for _, inc := range sorted {
			fmt.Fprintf(b, "        %q,\n", inc)
		}
		b.WriteString("    ],\n")
	}
	deps := wrapperDeps(ex, name, archiveRel, oldLabelToNew)
	if len(deps) > 0 {
		b.WriteString("    deps = [\n")
		for _, d := range deps {
			fmt.Fprintf(b, "        %q,\n", d)
		}
		b.WriteString("    ],\n")
	}
	// linkopts carry the harvested system-lib / -l<name> fragments
	// (Export.LinkLibraries). Without these a consumer that pulls the
	// wrapper still fails at the FINAL link on the leaf system libs the
	// prebuilt needs — Threads::Threads → -lpthread, ${CMAKE_DL_LIBS} →
	// -ldl, a bare m → -lm — even though the target-label deps resolved.
	if lo := wrapperLinkopts(ex); len(lo) > 0 {
		b.WriteString("    linkopts = [\n")
		for _, l := range lo {
			fmt.Fprintf(b, "        %q,\n", l)
		}
		b.WriteString("    ],\n")
	}
	b.WriteString(")\n")
}

// wrapperLinkopts renders Export.LinkLibraries as cc_library linkopts. The
// harvester stores these as bare lib names (`m`, `pthread`, `dl`) or already-flag
// fragments (`-pthread`); a bare name gets a `-l` prefix, an existing flag passes
// through. SOURCE ORDER is preserved (only deduped): linker argv order is
// semantically significant — a positional `-Wl,--as-needed` / `--no-as-needed`
// applies to the libs that follow it — and the harvester already builds
// LinkLibraries deterministically, so this stays byte-stable without sorting.
func wrapperLinkopts(ex *manifest.Export) []string {
	if len(ex.LinkLibraries) == 0 {
		return nil
	}
	seen := map[string]bool{}
	var out []string
	for _, l := range ex.LinkLibraries {
		l = strings.TrimSpace(l)
		if l == "" {
			continue
		}
		if !strings.HasPrefix(l, "-") {
			l = "-l" + l
		}
		if seen[l] {
			continue
		}
		seen[l] = true
		out = append(out, l)
	}
	return out
}

// checkDepCycles refuses manifests whose Deps close a cycle among the
// selected exports (after old→new label remapping, so a manifest that
// mixes spellings is still caught). Bazel rejects cyclic deps at load
// time; failing here names the cycle while the operator is still
// looking at the manifest. Edges to labels outside the selected
// exports can't cycle through the generated package and pass through.
func checkDepCycles(exports []*manifest.Export, oldToNew map[string]string) error {
	byNewLabel := map[string]*manifest.Export{}
	for _, ex := range exports {
		byNewLabel[oldToNew[ex.BazelLabel]] = ex
	}
	const (
		white = 0
		gray  = 1
		black = 2
	)
	state := map[*manifest.Export]int{}
	var stack []string
	var visit func(ex *manifest.Export) error
	visit = func(ex *manifest.Export) error {
		state[ex] = gray
		stack = append(stack, ex.CMakeTarget)
		for _, d := range ex.Deps {
			if n, ok := oldToNew[d]; ok {
				d = n
			}
			target := byNewLabel[d]
			if target == nil || target == ex {
				continue
			}
			if state[target] == gray {
				cyc := stack
				for i, n := range stack {
					if n == target.CMakeTarget {
						cyc = stack[i:]
						break
					}
				}
				return fmt.Errorf("dependency cycle among exports (%s); Bazel rejects cyclic deps — fuse or restructure the manifest",
					strings.Join(append(append([]string{}, cyc...), target.CMakeTarget), " -> "))
			}
			if state[target] == white {
				if err := visit(target); err != nil {
					return err
				}
			}
		}
		stack = stack[:len(stack)-1]
		state[ex] = black
		return nil
	}
	for _, ex := range exports {
		if state[ex] == white {
			if err := visit(ex); err != nil {
				return err
			}
		}
	}
	return nil
}

// wrapperDeps assembles the wrapper's dep list: its own archive first,
// then the declared closure with old export labels remapped onto their
// wrappers (sorted; deduped; never self-referential).
func wrapperDeps(ex *manifest.Export, name, archiveRel string, oldToNew map[string]string) []string {
	var out []string
	seen := map[string]bool{}
	if archiveRel != "" {
		out = append(out, ":"+name+"_archive")
		seen[":"+name+"_archive"] = true
	}
	var closure []string
	for _, d := range ex.Deps {
		if n, ok := oldToNew[d]; ok {
			d = n
		}
		if d == oldToNew[ex.BazelLabel] || seen[d] {
			continue
		}
		seen[d] = true
		closure = append(closure, d)
	}
	sort.Strings(closure)
	return append(out, closure...)
}

// archivePath returns the prefix-relative path of the export's first
// anchored link_path ("" when the export ships no artifact — the
// header-only / INTERFACE shape).
func archivePath(ex *manifest.Export) string {
	for _, lp := range ex.LinkPaths {
		if rel, ok := strings.CutPrefix(lp, manifest.PrefixAnchor); ok && rel != "" {
			return rel
		}
	}
	return ""
}

// WrapperName derives the consumer-facing target name from the cmake
// name: the segment after the last "::", with label-hostile runes
// folded to underscores. Exported so manifest PRODUCERS (the
// harvester) can synthesize labels that match the names this
// generator will emit — label-idempotent generation.
func WrapperName(cmakeTarget string) string {
	name := cmakeTarget
	if i := strings.LastIndex(name, "::"); i >= 0 {
		name = name[i+2:]
	}
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_', r == '-', r == '.':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

// rewriteManifest deep-copies the manifest with selected elements'
// export labels repointed at the wrappers and Deps cleared — the
// consume-and-clear half of the Export.Deps invariant. Unselected
// elements pass through untouched.
func rewriteManifest(im *manifest.Imports, element string, oldToNew map[string]string) *manifest.Imports {
	out := &manifest.Imports{Version: im.Version}
	for _, el := range im.Elements {
		if el == nil {
			continue
		}
		cel := *el
		if element == "" || el.Name == element {
			exports := make([]*manifest.Export, 0, len(el.Exports))
			for _, ex := range el.Exports {
				if ex == nil {
					continue
				}
				cex := *ex
				if n, ok := oldToNew[ex.BazelLabel]; ok {
					cex.BazelLabel = n
				}
				cex.Deps = nil
				exports = append(exports, &cex)
			}
			cel.Exports = exports
		}
		out.Elements = append(out.Elements, &cel)
	}
	return out
}

// WriteManifest writes the manifest as stable, indented JSON with a
// trailing newline (the exports.json convention).
func WriteManifest(path string, im *manifest.Imports) error {
	body, err := json.MarshalIndent(im, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(body, '\n'), 0o644)
}
