// Package wrappergen synthesizes prebuilt-wrapper BUILD packages from
// an imports manifest and rewrites the manifest onto the wrappers —
// the mechanical form of the cc_import + cc_library idiom for
// host-install prefixes. See cmd/imports-wrapper-gen's doc for the
// operator contract; the design discussion lives on the Export.Deps
// schema doc (internal/manifest): the generator is the
// consume-and-clear party of the "Deps = unmodeled closure" invariant.
package wrappergen

import (
	"encoding/json"
	"fmt"
	"os"
	"path"
	"sort"
	"strings"

	"github.com/sstriker/buildstream-bazel/internal/manifest"
)

// headerGlobExts is the header-surface extension family the wrapper
// hdrs glob covers (matching the converter's header recognition).
var headerGlobExts = []string{"h", "hh", "hpp", "hxx", "inc", "inl", "ipp", "def"}

// Generate renders the wrapper BUILD for every selected element's
// exports and returns it together with the rewritten manifest:
// bazel_label repointed at `//<pkgPath>:<target>`, Deps cleared
// (the closure now lives on the wrapper as real Bazel deps),
// everything else preserved (link_paths / link_libraries still key the
// consumer-side fragment redirects, which must keep resolving to the
// wrapper).
//
// Per export the BUILD carries:
//
//   - cc_import `<name>_archive` over the first prefix-anchored
//     link_path (static_library / shared_library by extension),
//     omitted for archive-less (header-only / INTERFACE) exports;
//   - cc_library `<name>` — the consumer-facing wrapper — with deps on
//     its own archive plus the export's declared closure, each closure
//     label remapped onto its wrapper when it names another export's
//     OLD label (cross-element labels pass through verbatim);
//     hdrs/includes from interface_includes (defaulting to include/
//     when an archive exists, so the common layout resolves).
//
// Target names derive from the export's cmake name (the part after
// the last "::", sanitized); a collision across exports is an error —
// wrapper labels are consumer-facing and must be stable.
func Generate(im *manifest.Imports, pkgPath, element string) ([]byte, *manifest.Imports, error) {
	if im == nil {
		return nil, nil, fmt.Errorf("nil manifest")
	}
	type entry struct {
		ex   *manifest.Export
		name string
	}
	var entries []entry
	nameSeen := map[string]string{}
	oldLabelToNew := map[string]string{}
	for _, el := range im.Elements {
		if el == nil || (element != "" && el.Name != element) {
			continue
		}
		for _, ex := range el.Exports {
			if ex == nil {
				continue
			}
			name := wrapperName(ex.CMakeTarget)
			if prev, dup := nameSeen[name]; dup {
				return nil, nil, fmt.Errorf("wrapper name %q collides (%s vs %s); disambiguate the manifest", name, prev, ex.CMakeTarget)
			}
			nameSeen[name] = ex.CMakeTarget
			oldLabelToNew[ex.BazelLabel] = "//" + pkgPath + ":" + name
			entries = append(entries, entry{ex: ex, name: name})
		}
	}
	if len(entries) == 0 {
		return nil, nil, fmt.Errorf("no exports selected (element %q)", element)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].name < entries[j].name })

	var b strings.Builder
	b.WriteString("# Generated by imports-wrapper-gen. DO NOT EDIT.\n")
	b.WriteString("# Prebuilt wrappers: cc_import per archive + cc_library carrying the\n")
	b.WriteString("# manifest-declared closure as real Bazel deps (Export.Deps consumed\n")
	b.WriteString("# and cleared in the rewritten manifest — the invariant's generator\n")
	b.WriteString("# half). Place at the staged prefix root: archive paths are\n")
	b.WriteString("# prefix-relative.\n\n")
	b.WriteString(`load("@rules_cc//cc:defs.bzl", "cc_import", "cc_library")` + "\n\n")
	b.WriteString(`package(default_visibility = ["//visibility:public"])` + "\n")

	for _, e := range entries {
		archiveRel := archivePath(e.ex)
		b.WriteString("\n")
		if archiveRel != "" {
			fmt.Fprintf(&b, "cc_import(\n    name = %q,\n", e.name+"_archive")
			attr := "static_library"
			if strings.Contains(path.Base(archiveRel), ".so") || strings.HasSuffix(archiveRel, ".dylib") {
				attr = "shared_library"
			}
			fmt.Fprintf(&b, "    %s = %q,\n", attr, archiveRel)
			b.WriteString("    visibility = [\"//visibility:private\"],\n)\n\n")
		}
		fmt.Fprintf(&b, "cc_library(\n    name = %q,\n", e.name)
		incs := e.ex.InterfaceIncludes
		if len(incs) == 0 && archiveRel != "" {
			incs = []string{"include"}
		}
		if len(incs) > 0 {
			// The full header-ish surface, not just *.h: host-install
			// prefixes ship .inc (abseil), .hpp/.hh/.hxx/.ipp (C++), and
			// .def/.inl — and with allow_empty a too-narrow glob fails
			// SILENTLY (the wrapper builds, consumers miss textual
			// includes). Same extension family the converter's header
			// machinery recognizes.
			globs := make([]string, 0, len(incs)*len(headerGlobExts))
			for _, inc := range incs {
				for _, ext := range headerGlobExts {
					globs = append(globs, fmt.Sprintf("%q", path.Join(inc, "**", "*."+ext)))
				}
			}
			fmt.Fprintf(&b, "    hdrs = glob(\n        [\n")
			for _, g := range globs {
				fmt.Fprintf(&b, "            %s,\n", g)
			}
			fmt.Fprintf(&b, "        ],\n        allow_empty = True,\n    ),\n")
			sorted := append([]string(nil), incs...)
			sort.Strings(sorted)
			b.WriteString("    includes = [\n")
			for _, inc := range sorted {
				fmt.Fprintf(&b, "        %q,\n", inc)
			}
			b.WriteString("    ],\n")
		}
		deps := wrapperDeps(e.ex, e.name, archiveRel, oldLabelToNew)
		if len(deps) > 0 {
			b.WriteString("    deps = [\n")
			for _, d := range deps {
				fmt.Fprintf(&b, "        %q,\n", d)
			}
			b.WriteString("    ],\n")
		}
		b.WriteString(")\n")
	}

	rewritten := rewriteManifest(im, element, oldLabelToNew)
	return []byte(b.String()), rewritten, nil
}

// wrapperDeps assembles the wrapper's dep list: its own archive first,
// then the declared closure with old export labels remapped onto their
// wrappers (sorted; deduped; never self-referential).
func wrapperDeps(ex *manifest.Export, name, archiveRel string, oldToNew map[string]string) []string {
	var out []string
	seen := map[string]bool{}
	if archiveRel != "" {
		out = append(out, ":"+name+"_archive")
		seen[":"+name+"_archive"] = true
	}
	var closure []string
	for _, d := range ex.Deps {
		if n, ok := oldToNew[d]; ok {
			d = n
		}
		if d == oldToNew[ex.BazelLabel] || seen[d] {
			continue
		}
		seen[d] = true
		closure = append(closure, d)
	}
	sort.Strings(closure)
	return append(out, closure...)
}

// archivePath returns the prefix-relative path of the export's first
// anchored link_path ("" when the export ships no artifact — the
// header-only / INTERFACE shape).
func archivePath(ex *manifest.Export) string {
	for _, lp := range ex.LinkPaths {
		if rel, ok := strings.CutPrefix(lp, manifest.PrefixAnchor); ok && rel != "" {
			return rel
		}
	}
	return ""
}

// wrapperName derives the consumer-facing target name from the cmake
// name: the segment after the last "::", with label-hostile runes
// folded to underscores.
func wrapperName(cmakeTarget string) string {
	name := cmakeTarget
	if i := strings.LastIndex(name, "::"); i >= 0 {
		name = name[i+2:]
	}
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_', r == '-', r == '.':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

// rewriteManifest deep-copies the manifest with selected elements'
// export labels repointed at the wrappers and Deps cleared — the
// consume-and-clear half of the Export.Deps invariant. Unselected
// elements pass through untouched.
func rewriteManifest(im *manifest.Imports, element string, oldToNew map[string]string) *manifest.Imports {
	out := &manifest.Imports{Version: im.Version}
	for _, el := range im.Elements {
		if el == nil {
			continue
		}
		cel := *el
		if element == "" || el.Name == element {
			exports := make([]*manifest.Export, 0, len(el.Exports))
			for _, ex := range el.Exports {
				if ex == nil {
					continue
				}
				cex := *ex
				if n, ok := oldToNew[ex.BazelLabel]; ok {
					cex.BazelLabel = n
				}
				cex.Deps = nil
				exports = append(exports, &cex)
			}
			cel.Exports = exports
		}
		out.Elements = append(out.Elements, &cel)
	}
	return out
}

// WriteManifest writes the manifest as stable, indented JSON with a
// trailing newline (the exports.json convention).
func WriteManifest(path string, im *manifest.Imports) error {
	body, err := json.MarshalIndent(im, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(body, '\n'), 0o644)
}
