// Package wrappergen synthesizes prebuilt-wrapper BUILD packages from
// an imports manifest and rewrites the manifest onto the wrappers —
// the mechanical form of the cc_import + cc_library idiom for
// host-install prefixes. See cmd/imports-wrapper-gen's doc for the
// operator contract; the design discussion lives on the Export.Deps
// schema doc (internal/manifest): the generator is the
// consume-and-clear party of the "Deps = unmodeled closure" invariant.
package wrappergen

import (
	"encoding/json"
	"fmt"
	"os"
	"path"
	"sort"
	"strings"

	"github.com/sstriker/buildstream-bazel/internal/manifest"
)

// headerGlobExts is the header-surface extension family the wrapper
// hdrs glob covers (matching the converter's header recognition).
var headerGlobExts = []string{"h", "hh", "hpp", "hxx", "inc", "inl", "ipp", "def"}

// Generate renders the wrapper BUILD for every selected element's
// exports and returns it together with the rewritten manifest:
// bazel_label repointed at `//<pkgPath>:<target>`, Deps cleared
// (the closure now lives on the wrapper as real Bazel deps),
// everything else preserved (link_paths / link_libraries still key the
// consumer-side fragment redirects, which must keep resolving to the
// wrapper).
//
// Per export the BUILD carries:
//
//   - cc_import `<name>_archive` over the first prefix-anchored
//     link_path (static_library / shared_library by extension),
//     omitted for archive-less (header-only / INTERFACE) exports;
//   - cc_library `<name>` — the consumer-facing wrapper — with deps on
//     its own archive plus the export's declared closure, each closure
//     label remapped onto its wrapper when it names another export's
//     OLD label (cross-element labels pass through verbatim);
//     hdrs/includes from interface_includes (defaulting to include/
//     when an archive exists, so the common layout resolves);
//   - exports with Kind == manifest.KindExecutable (protoc-shaped
//     installed programs) get a `filegroup` over their prefix-relative
//     link_paths instead — an ELF program is not a static_library, and
//     genrule tool lifts need a file-shaped label, not a cc_library.
//
// Target names derive from the export's cmake name (the part after
// the last "::", sanitized); a collision across exports is an error —
// wrapper labels are consumer-facing and must be stable. A dependency
// cycle among the selected exports' Deps is likewise an error: Bazel
// rejects cyclic deps at load time, so the generator refuses up front
// (harvested manifests are cycle-free by construction — the harvester
// breaks cycles with a warning; hand-written ones are caught here).
func Generate(im *manifest.Imports, pkgPath, element string) ([]byte, *manifest.Imports, error) {
	if im == nil {
		return nil, nil, fmt.Errorf("nil manifest")
	}
	type entry struct {
		ex   *manifest.Export
		name string
	}
	var entries []entry
	nameSeen := map[string]string{}
	oldLabelToNew := map[string]string{}
	for _, el := range im.Elements {
		if el == nil || (element != "" && el.Name != element) {
			continue
		}
		for _, ex := range el.Exports {
			if ex == nil {
				continue
			}
			name := WrapperName(ex.CMakeTarget)
			if prev, dup := nameSeen[name]; dup {
				return nil, nil, fmt.Errorf("wrapper name %q collides (%s vs %s); disambiguate the manifest", name, prev, ex.CMakeTarget)
			}
			nameSeen[name] = ex.CMakeTarget
			oldLabelToNew[ex.BazelLabel] = "//" + pkgPath + ":" + name
			entries = append(entries, entry{ex: ex, name: name})
		}
	}
	if len(entries) == 0 {
		return nil, nil, fmt.Errorf("no exports selected (element %q)", element)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].name < entries[j].name })
	exports := make([]*manifest.Export, len(entries))
	for i, e := range entries {
		exports[i] = e.ex
	}
	// Route each export's LinkLibraries into linkopts vs dep edges (the
	// producer-side verify-don't-assert fix) before the cycle check, so the
	// link-derived deps are part of the graph it refuses cycles over.
	archiveOwner, headerOnlyByName := buildLinkableIndexes(im)
	routes := map[*manifest.Export]linkRoute{}
	for _, e := range entries {
		routes[e.ex] = routeLinkLibraries(e.ex, archiveOwner, headerOnlyByName, oldLabelToNew)
	}
	if err := checkDepCycles(exports, oldLabelToNew, routes); err != nil {
		return nil, nil, err
	}

	var b strings.Builder
	b.WriteString("# Generated by imports-wrapper-gen. DO NOT EDIT.\n")
	b.WriteString("# Prebuilt wrappers: cc_import per archive + cc_library carrying the\n")
	b.WriteString("# manifest-declared closure as real Bazel deps (Export.Deps consumed\n")
	b.WriteString("# and cleared in the rewritten manifest — the invariant's generator\n")
	b.WriteString("# half). Place at the staged prefix root: archive paths are\n")
	b.WriteString("# prefix-relative.\n\n")
	b.WriteString(`load("@rules_cc//cc:defs.bzl", "cc_import", "cc_library")` + "\n\n")
	b.WriteString(`package(default_visibility = ["//visibility:public"])` + "\n")

	for _, e := range entries {
		b.WriteString("\n")
		if e.ex.Kind == manifest.KindExecutable {
			renderExecutable(&b, e.name, e.ex)
			continue
		}
		renderLibrary(&b, e.name, e.ex, oldLabelToNew, routes[e.ex])
	}

	rewritten := rewriteManifest(im, element, oldLabelToNew)
	return []byte(b.String()), rewritten, nil
}

// renderExecutable writes the wrapper for an installed program: a
// filegroup over the prefix-relative bin paths — a file-shaped target
// the genrule tool lift's label resolution can put in `tools`.
// Wrapping it as cc_import/cc_library would hand consumers an ELF
// program as a static_library.
//
// Known limits: an executable export's Deps have no filegroup slot
// and are NOT represented — fine for statically linked tools (the
// common host-install shape), but a dynamically linked tool whose
// runtime .so's live in the prefix won't have them staged into a
// genrule sandbox; that shape needs the runtime closure in srcs (or
// `data` on the consuming genrule) when it shows up. Multiple link
// paths render a multi-file filegroup, which a consumer's
// $(execpath) rejects loudly — single-path rows are the assumed
// invariant (the harvester's canonicalKey dedup folds symlink
// spellings, so multi-path executable rows shouldn't arise).
func renderExecutable(b *strings.Builder, name string, ex *manifest.Export) {
	fmt.Fprintf(b, "filegroup(\n    name = %q,\n    srcs = [\n", name)
	for _, lp := range ex.LinkPaths {
		if rel, ok := strings.CutPrefix(lp, manifest.PrefixAnchor); ok && rel != "" {
			fmt.Fprintf(b, "        %q,\n", rel)
		}
	}
	b.WriteString("    ],\n)\n")
}

// renderLibrary writes the cc_import (when an archive exists) and the
// consumer-facing cc_library wrapper for one library export. route carries the
// LinkLibraries classification: routed linkopts (genuine externals only) plus
// dep edges for LinkLibraries names the manifest owns.
func renderLibrary(b *strings.Builder, name string, ex *manifest.Export, oldLabelToNew map[string]string, route linkRoute) {
	archiveRel := archivePath(ex)
	if archiveRel != "" {
		fmt.Fprintf(b, "cc_import(\n    name = %q,\n", name+"_archive")
		attr := "static_library"
		if strings.Contains(path.Base(archiveRel), ".so") || strings.HasSuffix(archiveRel, ".dylib") {
			attr = "shared_library"
		}
		fmt.Fprintf(b, "    %s = %q,\n", attr, archiveRel)
		// A cyclic static-archive SCC member: whole-archive it so every
		// object links regardless of position (cmake broke the cycle by
		// repetition / --start-group; alwayslink is the Bazel equivalent).
		// Only meaningful for a static archive.
		if ex.AlwaysLink && attr == "static_library" {
			b.WriteString("    alwayslink = True,\n")
		}
		b.WriteString("    visibility = [\"//visibility:private\"],\n)\n\n")
	}
	fmt.Fprintf(b, "cc_library(\n    name = %q,\n", name)
	incs := ex.InterfaceIncludes
	if len(incs) == 0 && archiveRel != "" {
		incs = []string{"include"}
	}
	if len(incs) > 0 {
		// The full header-ish surface, not just *.h: host-install
		// prefixes ship .inc (abseil), .hpp/.hh/.hxx/.ipp (C++), and
		// .def/.inl — and with allow_empty a too-narrow glob fails
		// SILENTLY (the wrapper builds, consumers miss textual
		// includes). Same extension family the converter's header
		// machinery recognizes.
		globs := make([]string, 0, len(incs)*len(headerGlobExts))
		for _, inc := range incs {
			for _, ext := range headerGlobExts {
				globs = append(globs, fmt.Sprintf("%q", path.Join(inc, "**", "*."+ext)))
			}
		}
		fmt.Fprintf(b, "    hdrs = glob(\n        [\n")
		for _, g := range globs {
			fmt.Fprintf(b, "            %s,\n", g)
		}
		fmt.Fprintf(b, "        ],\n        allow_empty = True,\n    ),\n")
		sorted := append([]string(nil), incs...)
		sort.Strings(sorted)
		b.WriteString("    includes = [\n")
		for _, inc := range sorted {
			fmt.Fprintf(b, "        %q,\n", inc)
		}
		b.WriteString("    ],\n")
	}
	deps := wrapperDeps(ex, name, archiveRel, oldLabelToNew, route.deps)
	if len(deps) > 0 {
		b.WriteString("    deps = [\n")
		for _, d := range deps {
			fmt.Fprintf(b, "        %q,\n", d)
		}
		b.WriteString("    ],\n")
	}
	// linkopts carry the harvested GENUINE system-lib fragments only — the
	// leaf -l<name> the prebuilt needs (Threads::Threads → -lpthread,
	// ${CMAKE_DL_LIBS} → -ldl, a bare m → -lm). Names the manifest owns (this
	// export's own archive, or a sibling/header-only export) are NOT here:
	// they became the export's cc_import or a dep edge above (routeLinkLibraries).
	if len(route.linkopts) > 0 {
		b.WriteString("    linkopts = [\n")
		for _, l := range route.linkopts {
			fmt.Fprintf(b, "        %q,\n", l)
		}
		b.WriteString("    ],\n")
	}
	b.WriteString(")\n")
}

// linkRoute is the routed form of an export's LinkLibraries: the genuine
// external/system fragments that become cc_library linkopts, and the manifest
// exports a name resolved to that must become dep edges to their wrappers
// instead.
type linkRoute struct {
	linkopts []string // -l<name> / passthrough flags, SOURCE order, deduped
	deps     []string // wrapper labels (new/verbatim), from resolved names
}

// routeLinkLibraries classifies each Export.LinkLibraries entry instead of
// blindly emitting it as -l<name> — the producer-side "verify, don't assert"
// fix. A LinkLibraries name is one of three kinds:
//
//   - the export's OWN archive-provided name (libz.a → "z", the consumer-redirect
//     name LookupLinkLibrary keys on): the cc_import already provides it, so it
//     is NOT re-emitted as -lz;
//   - another manifest export's archive-provided name, or a header-only export
//     the manifest owns: a dep edge to that export's wrapper, never a -l flag
//     (asserting a linkable lib<name> exists on the host when the manifest owns
//     the archive is the assert-don't-verify bug this removes);
//   - a genuine external/system bare name (`m`, `pthread`) or an already-formed
//     flag (`-Wl,--as-needed`): the ONLY kind that stays a linkopt.
//
// SOURCE ORDER of the surviving linkopts is preserved (only deduped): linker
// argv order is semantically significant (a positional `-Wl,--as-needed`
// applies to the libs that follow it) and the harvester builds LinkLibraries
// deterministically, so this stays byte-stable without sorting.
func routeLinkLibraries(ex *manifest.Export, archiveOwner, headerOnlyByName map[string]*manifest.Export, oldToNew map[string]string) linkRoute {
	var r linkRoute
	if len(ex.LinkLibraries) == 0 {
		return r
	}
	self := providedLibName(archivePath(ex))
	seenOpt := map[string]bool{}
	seenDep := map[string]bool{}
	for _, l := range ex.LinkLibraries {
		l = strings.TrimSpace(l)
		if l == "" {
			continue
		}
		// Normalize to the bare lib name for classification. A `-l<name>`
		// spelling (a hand-written manifest can carry one) must route the SAME
		// as a bare `<name>` — otherwise it would bypass the resolver and
		// reintroduce the self/sibling relink this change removes. Any other
		// `-...` token (`-Wl,...`, `-pthread`, `-L<dir>`) is an opaque flag,
		// never a manifest name — pass it through verbatim.
		name := l
		if strings.HasPrefix(l, "-") {
			if rest, ok := strings.CutPrefix(l, "-l"); ok && rest != "" {
				name = rest
			} else {
				if !seenOpt[l] {
					seenOpt[l] = true
					r.linkopts = append(r.linkopts, l)
				}
				continue
			}
		}
		// The export's own archive provides this name — the cc_import covers
		// it; do not re-link it as -l<name>. (The harvest flow's only real
		// conflation: an export's LinkLibraries mixes its own archive name —
		// kept for the consumer LookupLinkLibrary redirect — with its leaf
		// system libs.)
		if name == self {
			continue
		}
		// Another manifest export the name genuinely names: a sibling whose
		// archive provides it, or a header-only export by its wrapper name.
		// Wire a dep to that wrapper, never a -l flag. (Defensive: the harvest
		// flow already routes cross-export references to deps, but hand-written
		// manifests can put such a name in the -l channel.)
		if b := archiveOwner[name]; b != nil && b != ex {
			addWrapperDep(&r, seenDep, b, oldToNew)
			continue
		}
		if b := headerOnlyByName[name]; b != nil && b != ex {
			addWrapperDep(&r, seenDep, b, oldToNew)
			continue
		}
		// Genuine external / system lib → -l<name>.
		flag := "-l" + name
		if !seenOpt[flag] {
			seenOpt[flag] = true
			r.linkopts = append(r.linkopts, flag)
		}
	}
	return r
}

// addWrapperDep records a dep to the export b's wrapper label (its rewritten
// label when b is one of the exports being generated now, else its manifest
// label verbatim — the cross-element pass-through wrapperDeps also uses).
func addWrapperDep(r *linkRoute, seen map[string]bool, b *manifest.Export, oldToNew map[string]string) {
	label := b.BazelLabel
	if n, ok := oldToNew[b.BazelLabel]; ok {
		label = n
	}
	if label == "" || seen[label] {
		return
	}
	seen[label] = true
	r.deps = append(r.deps, label)
}

// providedLibName returns the -l<name> a lib<name>.<ext> archive provides
// (lib/libz.a → "z", libz.so.1.2.3 → "z"), or "" when the path isn't that
// shape. This is the standard linker naming convention (-lz links libz.*), and
// the signal wrappergen uses to tell a name the manifest OWNS (an archive)
// from a genuine system leaf.
func providedLibName(archiveRel string) string {
	if archiveRel == "" {
		return ""
	}
	base := path.Base(archiveRel)
	if !strings.HasPrefix(base, "lib") {
		return ""
	}
	rest := base[len("lib"):]
	for _, ext := range []string{".a", ".so", ".dylib"} {
		if i := strings.Index(rest, ext); i > 0 {
			return rest[:i]
		}
	}
	return ""
}

// buildLinkableIndexes maps, over the whole manifest, each archive-provided
// -l name to its owning export (archiveOwner, e.g. libz.a → "z" → the zlib
// export) and each header-only export's wrapper name to that export
// (headerOnlyByName). routeLinkLibraries consults both to tell a name the
// manifest OWNS (route to a dep) from a genuine system leaf (keep as -l).
func buildLinkableIndexes(im *manifest.Imports) (archiveOwner, headerOnlyByName map[string]*manifest.Export) {
	archiveOwner = map[string]*manifest.Export{}
	headerOnlyByName = map[string]*manifest.Export{}
	for _, el := range im.Elements {
		if el == nil {
			continue
		}
		for _, ex := range el.Exports {
			if ex == nil {
				continue
			}
			if n := providedLibName(archivePath(ex)); n != "" {
				archiveOwner[n] = ex
			} else if ex.Kind != manifest.KindExecutable {
				// No archive → header-only / INTERFACE export; index it by its
				// wrapper name so a raw -l reference to it routes to a dep.
				headerOnlyByName[WrapperName(ex.CMakeTarget)] = ex
			}
		}
	}
	return archiveOwner, headerOnlyByName
}

// checkDepCycles refuses manifests whose Deps close a cycle among the
// selected exports (after old→new label remapping, so a manifest that
// mixes spellings is still caught). Bazel rejects cyclic deps at load
// time; failing here names the cycle while the operator is still
// looking at the manifest. Edges to labels outside the selected
// exports can't cycle through the generated package and pass through.
func checkDepCycles(exports []*manifest.Export, oldToNew map[string]string, routes map[*manifest.Export]linkRoute) error {
	byNewLabel := map[string]*manifest.Export{}
	for _, ex := range exports {
		byNewLabel[oldToNew[ex.BazelLabel]] = ex
	}
	const (
		white = 0
		gray  = 1
		black = 2
	)
	state := map[*manifest.Export]int{}
	var stack []string
	var visit func(ex *manifest.Export) error
	visit = func(ex *manifest.Export) error {
		state[ex] = gray
		stack = append(stack, ex.CMakeTarget)
		// Edges are the declared closure (old labels remapped) plus the
		// link-derived deps (LinkLibraries names the manifest owns, already
		// wrapper labels), so a cycle closed through either channel is caught.
		edges := make([]string, 0, len(ex.Deps)+len(routes[ex].deps))
		for _, d := range ex.Deps {
			if n, ok := oldToNew[d]; ok {
				d = n
			}
			edges = append(edges, d)
		}
		edges = append(edges, routes[ex].deps...)
		for _, d := range edges {
			target := byNewLabel[d]
			if target == nil || target == ex {
				continue
			}
			if state[target] == gray {
				cyc := stack
				for i, n := range stack {
					if n == target.CMakeTarget {
						cyc = stack[i:]
						break
					}
				}
				return fmt.Errorf("dependency cycle among exports (%s); Bazel rejects cyclic deps — fuse or restructure the manifest",
					strings.Join(append(append([]string{}, cyc...), target.CMakeTarget), " -> "))
			}
			if state[target] == white {
				if err := visit(target); err != nil {
					return err
				}
			}
		}
		stack = stack[:len(stack)-1]
		state[ex] = black
		return nil
	}
	for _, ex := range exports {
		if state[ex] == white {
			if err := visit(ex); err != nil {
				return err
			}
		}
	}
	return nil
}

// wrapperDeps assembles the wrapper's dep list: its own archive first,
// then the declared closure with old export labels remapped onto their
// wrappers, plus the link-derived deps (LinkLibraries names the manifest
// owns, already wrapper labels) — sorted; deduped; never self-referential.
func wrapperDeps(ex *manifest.Export, name, archiveRel string, oldToNew map[string]string, linkDeps []string) []string {
	var out []string
	seen := map[string]bool{}
	if archiveRel != "" {
		out = append(out, ":"+name+"_archive")
		seen[":"+name+"_archive"] = true
	}
	self := oldToNew[ex.BazelLabel]
	var closure []string
	add := func(d string) {
		if d == self || seen[d] {
			return
		}
		seen[d] = true
		closure = append(closure, d)
	}
	for _, d := range ex.Deps {
		if n, ok := oldToNew[d]; ok {
			d = n
		}
		add(d)
	}
	for _, d := range linkDeps {
		add(d)
	}
	sort.Strings(closure)
	return append(out, closure...)
}

// archivePath returns the prefix-relative path of the export's first
// anchored link_path ("" when the export ships no artifact — the
// header-only / INTERFACE shape).
func archivePath(ex *manifest.Export) string {
	for _, lp := range ex.LinkPaths {
		if rel, ok := strings.CutPrefix(lp, manifest.PrefixAnchor); ok && rel != "" {
			return rel
		}
	}
	return ""
}

// WrapperName derives the consumer-facing target name from the cmake
// name: the segment after the last "::", with label-hostile runes
// folded to underscores. Exported so manifest PRODUCERS (the
// harvester) can synthesize labels that match the names this
// generator will emit — label-idempotent generation.
func WrapperName(cmakeTarget string) string {
	name := cmakeTarget
	if i := strings.LastIndex(name, "::"); i >= 0 {
		name = name[i+2:]
	}
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_', r == '-', r == '.':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

// rewriteManifest deep-copies the manifest with selected elements'
// export labels repointed at the wrappers and Deps cleared — the
// consume-and-clear half of the Export.Deps invariant. Unselected
// elements pass through untouched.
func rewriteManifest(im *manifest.Imports, element string, oldToNew map[string]string) *manifest.Imports {
	out := &manifest.Imports{Version: im.Version}
	for _, el := range im.Elements {
		if el == nil {
			continue
		}
		cel := *el
		if element == "" || el.Name == element {
			exports := make([]*manifest.Export, 0, len(el.Exports))
			for _, ex := range el.Exports {
				if ex == nil {
					continue
				}
				cex := *ex
				if n, ok := oldToNew[ex.BazelLabel]; ok {
					cex.BazelLabel = n
				}
				cex.Deps = nil
				exports = append(exports, &cex)
			}
			cel.Exports = exports
		}
		out.Elements = append(out.Elements, &cel)
	}
	return out
}

// WriteManifest writes the manifest as stable, indented JSON with a
// trailing newline (the exports.json convention).
func WriteManifest(path string, im *manifest.Imports) error {
	body, err := json.MarshalIndent(im, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(body, '\n'), 0o644)
}
