// BUILD.bazel.out emission for kind:pyproject native render.
// Produces py_library / py_binary rules from the lowered
// Target list. Output is deterministic: list attributes are
// sorted; targets emit in the order Lower returned them.
//
// Doesn't reuse converter/internal/emit/bazel — that package
// is cc-shaped (cc_library / cc_binary / cc_import / cc_test).
// py rules have a smaller attribute set and a different
// `imports` semantic; the duplication is small and the
// architectural alignment isn't worth pulling py rules into
// the cc-centric IR at v1 scope.
package main

import (
	"bytes"
	"fmt"
	"sort"
)

// Emit renders the BUILD.bazel.out body for a slice of
// lowered Targets. Empty slice produces a header-only output
// with no rules — legal but unusual; the Lower pass can return
// it for an element whose pyproject.toml declares no packages
// and no scripts.
func Emit(targets []Target) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by convert-element-pyproject. DO NOT EDIT.\n\n")
	if anyKind(targets, KindPyLibrary) || anyKind(targets, KindPyBinary) {
		b.WriteString(`load("@rules_python//python:defs.bzl", "py_library", "py_binary")` + "\n\n")
	}
	for i, t := range targets {
		if i > 0 {
			b.WriteString("\n")
		}
		switch t.Kind {
		case KindPyLibrary:
			emitPyLibrary(&b, t)
		case KindPyBinary:
			emitPyBinary(&b, t)
		}
	}
	return b.Bytes()
}

func anyKind(targets []Target, k Kind) bool {
	for _, t := range targets {
		if t.Kind == k {
			return true
		}
	}
	return false
}

// emitPyLibrary renders one py_library rule. `srcs` uses an
// explicit list (not a glob) — the discovery pass enumerated
// the .py files exactly, and an explicit list is safer
// (avoids picking up future test files / scratch .py the
// backend wouldn't have shipped).
func emitPyLibrary(b *bytes.Buffer, t Target) {
	fmt.Fprintf(b, "py_library(\n    name = %q,\n", t.Name)
	if len(t.Srcs) > 0 {
		writeList(b, "srcs", sortedCopy(t.Srcs))
	}
	if len(t.Imports) > 0 {
		writeList(b, "imports", sortedCopy(t.Imports))
	}
	if len(t.Deps) > 0 {
		writeList(b, "deps", sortedCopy(t.Deps))
	}
	if len(t.Visibility) > 0 {
		writeList(b, "visibility", t.Visibility)
	}
	b.WriteString(")\n")
}

// emitPyBinary renders a py_binary plus a sibling genrule
// that materialises the entry shim. The shim is a 3-line
// .py file (`import sys` / `from <module> import <func>` /
// `sys.exit(<func>() or 0)`) that imports the entry module and
// dispatches the entry function — universally compatible across
// rules_python versions (avoids depending on
// py_console_script_binary, which was added in rules_python
// 0.21+ and we don't pin rules_python's version in project B's
// MODULE.bazel).
func emitPyBinary(b *bytes.Buffer, t Target) {
	shimRule := t.Name + "_entry"
	shimFile := t.Name + "_entry.py"
	// The genrule cmd is a single shell line, not a here-doc,
	// to keep escaping straightforward inside a Starlark
	// triple-quoted string. Each printf produces one line of
	// the entry shim. We could collapse this into one printf,
	// but per-line keeps it readable in the rendered BUILD.
	fmt.Fprintf(b, "genrule(\n    name = %q,\n    outs = [%q],\n", shimRule, shimFile)
	cmd := fmt.Sprintf(`{ printf 'import sys\n' ; printf 'from %s import %s\n' ; printf 'sys.exit(%s() or 0)\n' ; } > $@`,
		t.EntryModule, t.EntryFunc, t.EntryFunc)
	fmt.Fprintf(b, "    cmd = %q,\n)\n\n", cmd)

	fmt.Fprintf(b, "py_binary(\n    name = %q,\n", t.Name)
	writeList(b, "srcs", []string{":" + shimRule})
	fmt.Fprintf(b, "    main = %q,\n", shimFile)
	if t.EntryDep != "" {
		writeList(b, "deps", []string{t.EntryDep})
	}
	if len(t.Visibility) > 0 {
		writeList(b, "visibility", t.Visibility)
	}
	b.WriteString(")\n")
}

func writeList(b *bytes.Buffer, attr string, items []string) {
	if len(items) == 0 {
		return
	}
	if len(items) == 1 {
		fmt.Fprintf(b, "    %s = [%q],\n", attr, items[0])
		return
	}
	b.WriteString("    " + attr + " = [\n")
	for _, it := range items {
		fmt.Fprintf(b, "        %q,\n", it)
	}
	b.WriteString("    ],\n")
}

func sortedCopy(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}
