// BUILD.bazel.out emission for kind:pyproject native render.
// Produces py_library / py_binary rules from the lowered
// Target list. Output is deterministic: list attributes are
// sorted; targets emit in the order Lower returned them.
//
// Doesn't reuse converter/emit/bazel — that package
// is cc-shaped (cc_library / cc_binary / cc_import / cc_test).
// py rules have a smaller attribute set and a different
// `imports` semantic; the duplication is small and the
// architectural alignment isn't worth pulling py rules into
// the cc-centric IR at v1 scope.
package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/bazelbuild/buildtools/build"
)

// Emit renders the BUILD.bazel.out body for a slice of
// lowered Targets. Empty slice produces a header-only output
// with no rules — legal but unusual; the Lower pass can return
// it for an element whose pyproject.toml declares no packages
// and no scripts.
func Emit(targets []Target) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by convert-element-pyproject. DO NOT EDIT.\n\n")
	// Compute the load-symbol set from emitted kinds, sorted
	// alphabetically per gazelle / buildifier convention. Only
	// the symbols actually rendered show up in the load line;
	// `py_test` joins only when at least one Target has
	// KindPyTest.
	var loads []string
	if anyKind(targets, KindPyBinary) {
		loads = append(loads, "py_binary")
	}
	if anyKind(targets, KindPyLibrary) {
		loads = append(loads, "py_library")
	}
	if anyKind(targets, KindPyTest) {
		loads = append(loads, "py_test")
	}
	if len(loads) > 0 {
		fmt.Fprintf(&b, `load("@rules_python//python:defs.bzl"`)
		for _, s := range loads {
			fmt.Fprintf(&b, ", %q", s)
		}
		b.WriteString(")\n\n")
	}
	for i, t := range targets {
		if i > 0 {
			b.WriteString("\n")
		}
		switch t.Kind {
		case KindPyLibrary:
			emitPyLibrary(&b, t)
		case KindPyBinary:
			emitPyBinary(&b, t)
		case KindPyTest:
			emitPyTest(&b, t)
		default:
			// Fail fast on an unknown Kind rather than silently
			// dropping the target — a partially-rendered BUILD
			// with a missing rule is harder to diagnose than a
			// panic at convert time, and Lower's Kind setter is
			// the only code path that ever populates this field.
			panic(fmt.Sprintf("convert-element-pyproject: emit: unknown Target.Kind %v for target %q (Lower must set Kind to one of KindPyLibrary / KindPyBinary / KindPyTest)", t.Kind, t.Name))
		}
	}
	// Phase 3 canonicalization: route the
	// fmt.Fprintf-assembled output through
	// buildtools-AST Parse + Format so the rendered shape
	// matches what `buildifier --mode=fix` would produce.
	// Attribute order pulls from `tables.NamePriority`; list
	// wrapping, dict wrapping, and label normalization fall
	// out of the formatter's default Rewriter pass.
	// `BUILD.bazel` filename hint dispatches the parser into
	// TypeBuild semantics. A parse failure is a
	// programming failure in this emitter — the body
	// bytes came from emitPyLibrary / emitPyBinary /
	// emitPyTest's format-string emit, so a parse error
	// means we regressed to writing syntactically invalid
	// Bazel. Panic so the test suite surfaces the
	// diagnostic rather than silently writing
	// non-canonical output (which would break the Phase 3
	// buildifier-no-op contract).
	body := b.Bytes()
	f, err := build.Parse("BUILD.bazel", body)
	if err != nil {
		panic(fmt.Sprintf("convert-element-pyproject.Emit: emit produced unparseable BUILD bytes: %v\n%s", err, body))
	}
	addKeepMarkers(f)
	return build.Format(f)
}

// addKeepMarkers tags load-bearing attribute lines with
// `# keep` comments so a downstream `gazelle fix` run won't
// rewrite values the converter extracted from pyproject.toml.
// Per Phase 7a of ROADMAP.md.
//
// Scope follows the conventions doc:
//   - py_library / py_test: imports, pyi_srcs, testonly.
//   - py_binary (strict shape): main + srcs (entry-module
//     path is load-bearing per Phase 5).
//   - package(...): whole-rule keep.
func addKeepMarkers(f *build.File) {
	for _, stmt := range f.Stmt {
		call, ok := stmt.(*build.CallExpr)
		if !ok {
			continue
		}
		kind := pyCallRuleKind(call)
		switch kind {
		case "package":
			pyMarkCallKeep(call)
		case "py_library", "py_test":
			pyMarkAttrsKeep(call, pyLibraryKeepAttrs)
		case "py_binary":
			pyMarkAttrsKeep(call, pyBinaryKeepAttrs)
		}
	}
}

var pyLibraryKeepAttrs = map[string]bool{
	"imports":  true,
	"pyi_srcs": true,
	"testonly": true,
}

var pyBinaryKeepAttrs = map[string]bool{
	"main": true,
	"srcs": true,
}

func pyCallRuleKind(call *build.CallExpr) string {
	if ident, ok := call.X.(*build.Ident); ok {
		return ident.Name
	}
	return ""
}

func pyMarkCallKeep(call *build.CallExpr) {
	if pyHasKeepSuffix(call.Comment().Suffix) {
		return
	}
	call.Comment().Suffix = append(call.Comment().Suffix, build.Comment{Token: "# keep"})
}

func pyMarkAttrsKeep(call *build.CallExpr, attrNames map[string]bool) {
	for _, arg := range call.List {
		assign, ok := arg.(*build.AssignExpr)
		if !ok {
			continue
		}
		ident, ok := assign.LHS.(*build.Ident)
		if !ok {
			continue
		}
		if !attrNames[ident.Name] {
			continue
		}
		if pyHasKeepSuffix(assign.Comment().Suffix) {
			continue
		}
		assign.Comment().Suffix = append(assign.Comment().Suffix, build.Comment{Token: "# keep"})
	}
}

func pyHasKeepSuffix(comments []build.Comment) bool {
	for _, c := range comments {
		if strings.TrimSpace(c.Token) == "# keep" {
			return true
		}
	}
	return false
}

func anyKind(targets []Target, k Kind) bool {
	for _, t := range targets {
		if t.Kind == k {
			return true
		}
	}
	return false
}

// emitPyLibrary renders one py_library rule. `srcs` uses an
// explicit list (not a glob) — the discovery pass enumerated
// the .py files exactly, and an explicit list is safer
// (avoids picking up future test files / scratch .py the
// backend wouldn't have shipped).
func emitPyLibrary(b *bytes.Buffer, t Target) {
	fmt.Fprintf(b, "py_library(\n    name = %q,\n", t.Name)
	if len(t.Srcs) > 0 {
		writeList(b, "srcs", sortedCopy(t.Srcs))
	}
	if len(t.PyiSrcs) > 0 {
		writeList(b, "pyi_srcs", sortedCopy(t.PyiSrcs))
	}
	if len(t.Imports) > 0 {
		writeList(b, "imports", sortedCopy(t.Imports))
	}
	if len(t.Deps) > 0 {
		writeList(b, "deps", sortedCopy(t.Deps))
	}
	if t.Testonly {
		b.WriteString("    testonly = True,\n")
	}
	if len(t.Visibility) > 0 {
		writeList(b, "visibility", sortedCopy(t.Visibility))
	}
	b.WriteString(")\n")
}

// emitPyTest renders one py_test rule. Shape mirrors
// emitPyLibrary's attribute set minus the entry-shim
// machinery; per rules_python gazelle convention, py_tests
// reference the package's library via deps rather than
// duplicating srcs. Conftest deps are pre-wired by Lower so
// the emit stays attribute-mapping-only.
func emitPyTest(b *bytes.Buffer, t Target) {
	fmt.Fprintf(b, "py_test(\n    name = %q,\n", t.Name)
	if len(t.Srcs) > 0 {
		writeList(b, "srcs", sortedCopy(t.Srcs))
	}
	if len(t.PyiSrcs) > 0 {
		writeList(b, "pyi_srcs", sortedCopy(t.PyiSrcs))
	}
	if len(t.Imports) > 0 {
		writeList(b, "imports", sortedCopy(t.Imports))
	}
	if len(t.Deps) > 0 {
		writeList(b, "deps", sortedCopy(t.Deps))
	}
	if len(t.Visibility) > 0 {
		writeList(b, "visibility", sortedCopy(t.Visibility))
	}
	b.WriteString(")\n")
}

// emitPyBinary renders a py_binary. Two shapes:
//
//   - **Strict shape (Phase 5 default)**: when Target.Main is
//     set (the entry module self-invokes via `if __name__ ==
//     "__main__":` or the target is a `<pkg>_bin` for a
//     package containing `__main__.py`), emit a single
//     py_binary pointing directly at the module file with
//     no shim genrule:
//     ```
//     py_binary(name=..., srcs=[<Main>], main=<Main>, deps=[<EntryDep>])
//     ```
//     Matches rules_python gazelle plugin's canonical shape.
//
//   - **Shim shape (Phase 5 fallback / pre-Phase-5 default)**:
//     when Target.Main is empty (the entry module doesn't
//     self-invoke, or operator passed `--always-emit-entry-shim`),
//     render a sibling genrule that materializes a 3-line
//     entry shim (`import sys` / `from <module> import <func>`
//     / `sys.exit(<func>() or 0)`) plus a py_binary consuming
//     the shim. Universally compatible across rules_python
//     versions and works for entry modules that don't carry
//     their own `__name__ == "__main__"` guard.
func emitPyBinary(b *bytes.Buffer, t Target) {
	if t.Main != "" {
		emitPyBinaryStrict(b, t)
		return
	}
	emitPyBinaryShim(b, t)
}

// emitPyBinaryStrict renders the Phase 5 canonical
// py_binary-with-source-file shape — no shim genrule.
func emitPyBinaryStrict(b *bytes.Buffer, t Target) {
	fmt.Fprintf(b, "py_binary(\n    name = %q,\n", t.Name)
	srcs := t.Srcs
	if len(srcs) == 0 {
		// Defensive: Lower populates both Main and Srcs in
		// lockstep, but if a future producer forgets Srcs we
		// derive a single-element list from Main rather than
		// emitting a syntactically-invalid py_binary.
		srcs = []string{t.Main}
	}
	writeList(b, "srcs", sortedCopy(srcs))
	fmt.Fprintf(b, "    main = %q,\n", t.Main)
	if t.EntryDep != "" {
		writeList(b, "deps", []string{t.EntryDep})
	}
	if len(t.Visibility) > 0 {
		writeList(b, "visibility", sortedCopy(t.Visibility))
	}
	b.WriteString(")\n")
}

// emitPyBinaryShim renders the legacy
// genrule-makes-a-shim + py_binary-imports-shim shape.
// Preserved verbatim for operator opt-in
// (`--always-emit-entry-shim`) and for entry modules that
// don't self-invoke.
func emitPyBinaryShim(b *bytes.Buffer, t Target) {
	shimRule := t.Name + "_entry"
	shimFile := t.Name + "_entry.py"
	// The genrule cmd is a single shell line, not a here-doc,
	// to keep escaping straightforward inside a Starlark
	// triple-quoted string. Each printf produces one line of
	// the entry shim. We could collapse this into one printf,
	// but per-line keeps it readable in the rendered BUILD.
	fmt.Fprintf(b, "genrule(\n    name = %q,\n    outs = [%q],\n", shimRule, shimFile)
	cmd := fmt.Sprintf(`{ printf 'import sys\n' ; printf 'from %s import %s\n' ; printf 'sys.exit(%s() or 0)\n' ; } > $@`,
		t.EntryModule, t.EntryFunc, t.EntryFunc)
	fmt.Fprintf(b, "    cmd = %q,\n)\n\n", cmd)

	fmt.Fprintf(b, "py_binary(\n    name = %q,\n", t.Name)
	writeList(b, "srcs", []string{":" + shimRule})
	fmt.Fprintf(b, "    main = %q,\n", shimFile)
	if t.EntryDep != "" {
		writeList(b, "deps", []string{t.EntryDep})
	}
	if len(t.Visibility) > 0 {
		writeList(b, "visibility", sortedCopy(t.Visibility))
	}
	b.WriteString(")\n")
}

func writeList(b *bytes.Buffer, attr string, items []string) {
	if len(items) == 0 {
		return
	}
	if len(items) == 1 {
		fmt.Fprintf(b, "    %s = [%q],\n", attr, items[0])
		return
	}
	b.WriteString("    " + attr + " = [\n")
	for _, it := range items {
		fmt.Fprintf(b, "        %q,\n", it)
	}
	b.WriteString("    ],\n")
}

func sortedCopy(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}
