package projecta

import (
	"bytes"
	"fmt"
	"sort"
)

// ElementConvertArgs is the input to the element-convert cell
// type: one cell per (element, platform) that drives a single
// convert-element invocation under the matching platform's
// exec_compatible_with constraints. The orchestrator's
// per-element fold (Stage 4) consumes the resulting per-cell
// IR JSON to produce the final unified BUILD.bazel.
//
// This is the meta-project counterpart to the orchestrator's
// REAPI-driven fan-out: same cells, same per-platform
// invariants, but driven by Bazel actions instead of REAPI
// directly. Operators who want their conversion pipeline to be
// a Bazel build (rather than a separate orchestrator run) use
// this surface.
type ElementConvertArgs struct {
	// ElementName names the element being converted. Becomes the
	// Bazel target name prefix for each per-(element, platform)
	// cell genrule.
	ElementName string

	// CmakeSourceLabel is the Bazel label of the element's
	// source-tree filegroup the genrules consume as srcs.
	CmakeSourceLabel string

	// CmakeListsLabel is the Bazel label of the element's
	// CMakeLists.txt file. Used by the genrule cmd to derive the
	// cmake source root via $(execpath ...) + dirname, the same
	// trick RenderToolchainProbe uses.
	CmakeListsLabel string

	// ConvertElementLabel is the Bazel label of the
	// convert-element binary. Typical: "//tools:convert-element".
	ConvertElementLabel string

	// ImportsManifestLabel is the optional label of the imports
	// manifest the orchestrator generates per element.
	// Empty when the element has no cross-element deps.
	ImportsManifestLabel string

	// PrefixDirLabel is the optional label of the synth-prefix
	// directory the orchestrator builds per element. Empty when
	// the element has no kind:cmake deps.
	PrefixDirLabel string

	// ToolchainCMakeFileLabel is the optional label of the
	// per-platform toolchain.cmake file the unifier emits.
	// Empty for hosts using cmake's default compiler discovery.
	ToolchainCMakeFileLabel string

	// Platforms is the set of platforms to convert for. The
	// matrix of (ElementName x Platforms) becomes one cell per
	// platform; the per-element fold composes the resulting
	// per-cell IR JSONs into one BUILD.bazel.
	Platforms []Platform
}

// RenderElementConvert renders one BUILD.bazel that drives N
// convert-element invocations (one per platform) for a single
// element. The shape mirrors RenderToolchainProbe exactly —
// per-cell genrule with exec_compatible_with for the platform's
// constraints, plus an aggregating filegroup that
// `bazel build //<element>:all_cells` resolves.
//
// Per-cell outputs:
//
//   - <element>.<platform>.BUILD.bazel — the per-platform
//     rendered BUILD.bazel (the elementfold consumer reads it
//     for diagnostics; the IR itself drives the fold).
//   - <element>.<platform>.ir.json — the IR JSON the
//     orchestrator's fold consumes. convert-element's new
//     --out-ir-json flag writes it.
//
// The orchestrator's REAPI-driven fan-out (Stage 6) doesn't go
// through this rendering; it builds REAPI Actions directly.
// This surface exists for the meta-project flow: an operator
// who wants to drive conversion through their Bazel build
// system can render this BUILD.bazel into a project-A package
// and `bazel build //elements/<name>:all_cells` to produce the
// per-platform IRs.
func RenderElementConvert(args ElementConvertArgs) ([]byte, error) {
	if args.ElementName == "" {
		return nil, fmt.Errorf("projecta: ElementName required")
	}
	if err := checkBazelTargetSafeName(args.ElementName); err != nil {
		return nil, fmt.Errorf("projecta: ElementName %q: %w", args.ElementName, err)
	}
	if args.CmakeSourceLabel == "" {
		return nil, fmt.Errorf("projecta: CmakeSourceLabel required")
	}
	if args.CmakeListsLabel == "" {
		return nil, fmt.Errorf("projecta: CmakeListsLabel required")
	}
	if args.ConvertElementLabel == "" {
		return nil, fmt.Errorf("projecta: ConvertElementLabel required")
	}
	if len(args.Platforms) == 0 {
		return nil, fmt.Errorf("projecta: Platforms must be non-empty")
	}
	seenPlat := map[string]bool{}
	for i, p := range args.Platforms {
		if p.Name == "" {
			return nil, fmt.Errorf("projecta: Platforms[%d] has empty Name", i)
		}
		if err := checkBazelTargetSafeName(p.Name); err != nil {
			return nil, fmt.Errorf("projecta: Platforms[%d].Name %q: %w", i, p.Name, err)
		}
		if seenPlat[p.Name] {
			return nil, fmt.Errorf("projecta: duplicate Platforms[].Name %q", p.Name)
		}
		seenPlat[p.Name] = true
		if len(p.Constraints) == 0 {
			return nil, fmt.Errorf("projecta: Platforms[%d] (%s) has no Constraints", i, p.Name)
		}
	}

	var b bytes.Buffer
	b.WriteString("# Generated by render-project-a (element-convert). DO NOT EDIT.\n")
	b.WriteString("# Drives per-platform convert-element invocations for one element;\n")
	b.WriteString("# the orchestrator's per-element fold composes the per-cell IRs into\n")
	b.WriteString("# the final platform-portable BUILD.bazel.\n\n")

	var allOuts []string
	for _, p := range args.Platforms {
		cell := args.ElementName + "." + p.Name
		buildOut := cell + ".BUILD.bazel"
		irOut := cell + ".ir.json"
		allOuts = append(allOuts, buildOut, irOut)
		renderElementCellGenrule(&b, args, p, cell, buildOut, irOut)
	}

	fmt.Fprintf(&b, "filegroup(\n")
	fmt.Fprintf(&b, "    name = %q,\n", "all_cells")
	fmt.Fprintf(&b, "    srcs = [\n")
	for _, o := range allOuts {
		fmt.Fprintf(&b, "        %q,\n", o)
	}
	fmt.Fprintf(&b, "    ],\n")
	fmt.Fprintf(&b, "    visibility = [\"//visibility:public\"],\n")
	fmt.Fprintf(&b, ")\n")
	return b.Bytes(), nil
}

// renderElementCellGenrule emits one (element, platform) cell.
// The cmd shape mirrors handler_cmake.go's per-element genrule
// at write-a, with the relevant convert-element flags routed
// to per-cell output paths.
func renderElementCellGenrule(b *bytes.Buffer, args ElementConvertArgs, p Platform, cell, buildOut, irOut string) {
	fmt.Fprintf(b, "genrule(\n")
	fmt.Fprintf(b, "    name = %q,\n", cell)

	// srcs include the source filegroup, the explicit
	// CMakeLists.txt label (for $(execpath ...) resolution), and
	// optional imports/prefix labels.
	srcs := []string{args.CmakeSourceLabel}
	if args.CmakeSourceLabel != args.CmakeListsLabel {
		srcs = append(srcs, args.CmakeListsLabel)
	}
	if args.ImportsManifestLabel != "" {
		srcs = append(srcs, args.ImportsManifestLabel)
	}
	if args.PrefixDirLabel != "" {
		srcs = append(srcs, args.PrefixDirLabel)
	}
	if args.ToolchainCMakeFileLabel != "" {
		srcs = append(srcs, args.ToolchainCMakeFileLabel)
	}
	fmt.Fprintf(b, "    srcs = [\n")
	for _, s := range srcs {
		fmt.Fprintf(b, "        %q,\n", s)
	}
	fmt.Fprintf(b, "    ],\n")

	fmt.Fprintf(b, "    outs = [\n")
	fmt.Fprintf(b, "        %q,\n", buildOut)
	fmt.Fprintf(b, "        %q,\n", irOut)
	fmt.Fprintf(b, "    ],\n")
	fmt.Fprintf(b, "    tools = [%q],\n", args.ConvertElementLabel)

	cs := append([]string(nil), p.Constraints...)
	sort.Strings(cs)
	fmt.Fprintf(b, "    exec_compatible_with = [\n")
	for _, c := range cs {
		fmt.Fprintf(b, "        %q,\n", c)
	}
	fmt.Fprintf(b, "    ],\n")

	fmt.Fprintf(b, "    cmd = \"\"\"\n")
	fmt.Fprintf(b, "        $(location %s) \\\n", args.ConvertElementLabel)
	fmt.Fprintf(b, "            --source-root $$(dirname $(execpath %s)) \\\n", args.CmakeListsLabel)
	fmt.Fprintf(b, "            --out-build $(location %s) \\\n", buildOut)
	fmt.Fprintf(b, "            --out-ir-json $(location %s)", irOut)
	if args.ImportsManifestLabel != "" {
		fmt.Fprintf(b, " \\\n            --imports-manifest $(execpath %s)", args.ImportsManifestLabel)
	}
	if args.PrefixDirLabel != "" {
		fmt.Fprintf(b, " \\\n            --prefix-dir $$(dirname $(execpath %s))", args.PrefixDirLabel)
	}
	if args.ToolchainCMakeFileLabel != "" {
		fmt.Fprintf(b, " \\\n            --toolchain-cmake-file $(execpath %s)", args.ToolchainCMakeFileLabel)
	}
	fmt.Fprintf(b, "\n    \"\"\",\n")
	fmt.Fprintf(b, ")\n\n")
}
