package exports_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/sstriker/buildstream-bazel/internal/manifest"
	"github.com/sstriker/buildstream-bazel/orchestrator/internal/exports"
)

// helloTargetsCMake is a verbatim copy of the shape convert-element-cmake emits
// for hello-world. Embedding here lets the unit test run without driving
// the converter end-to-end.
const helloTargetsCMake = `# Generated by convert-element-cmake. DO NOT EDIT.
# Computes _IMPORT_PREFIX as the parent of lib/cmake/<Pkg>/.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

add_library(hello::hello STATIC IMPORTED)

set_target_properties(hello::hello PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
`

const fmtTargetsCMake = `add_library(FMT::fmt STATIC IMPORTED)
add_library(FMT::fmt-header-only INTERFACE IMPORTED)
`

// mkBundle assembles a synth-prefix-shaped bundle directory rooted at
// <dir> and writes one .cmake file under <dir>/lib/cmake/<pkg>/<name>
// for each (pkg, name, body) triple. Mirrors the layout
// `convert-element-cmake --out-bundle-dir` produces (via
// `synthprefix.BuildSlice`).
func mkBundle(t *testing.T, dir string, files map[string]map[string]string) {
	t.Helper()
	for pkg, perPkg := range files {
		pkgDir := filepath.Join(dir, "lib", "cmake", pkg)
		if err := os.MkdirAll(pkgDir, 0o755); err != nil {
			t.Fatal(err)
		}
		for name, body := range perPkg {
			if err := os.WriteFile(filepath.Join(pkgDir, name), []byte(body), 0o644); err != nil {
				t.Fatal(err)
			}
		}
	}
}

func TestFromBundle_ParsesAddLibrary(t *testing.T) {
	dir := t.TempDir()
	mkBundle(t, dir, map[string]map[string]string{
		"hello": {"helloTargets.cmake": helloTargetsCMake},
	})
	exps, err := exports.FromBundle(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(exps) != 1 {
		t.Fatalf("got %d exports, want 1", len(exps))
	}
	if exps[0].CMakeTarget != "hello::hello" {
		t.Errorf("CMakeTarget = %q, want hello::hello", exps[0].CMakeTarget)
	}
}

func TestFromBundle_MultipleImports(t *testing.T) {
	dir := t.TempDir()
	mkBundle(t, dir, map[string]map[string]string{
		"FMT": {"FMTTargets.cmake": fmtTargetsCMake},
	})
	exps, err := exports.FromBundle(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(exps) != 2 {
		t.Fatalf("got %d exports, want 2", len(exps))
	}
	got := []string{exps[0].CMakeTarget, exps[1].CMakeTarget}
	want1, want2 := "FMT::fmt", "FMT::fmt-header-only"
	// Order matches file order; test non-strictly to avoid coupling.
	if !((got[0] == want1 && got[1] == want2) || (got[0] == want2 && got[1] == want1)) {
		t.Errorf("got %v, want %v + %v", got, want1, want2)
	}
}

func TestFromBundle_IgnoresPerConfigFile(t *testing.T) {
	dir := t.TempDir()
	mkBundle(t, dir, map[string]map[string]string{
		// The -release.cmake overlay has set_property/set_target_properties
		// but no new add_library calls. We only parse Targets.cmake itself.
		"foo": {"fooTargets-release.cmake": `set_property(TARGET foo::foo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(foo::foo PROPERTIES IMPORTED_LOCATION_RELEASE "/usr/lib/libfoo.a")
`},
	})
	exps, err := exports.FromBundle(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(exps) != 0 {
		t.Errorf("got %d exports from a -release.cmake-only bundle, want 0", len(exps))
	}
}

func TestFromBundle_EmptyDir(t *testing.T) {
	dir := t.TempDir()
	exps, err := exports.FromBundle(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(exps) != 0 {
		t.Errorf("got %d exports from empty dir, want 0", len(exps))
	}
}

func TestAsElement_StampsBazelLabels(t *testing.T) {
	dir := t.TempDir()
	mkBundle(t, dir, map[string]map[string]string{
		"foo": {"fooTargets.cmake": `add_library(foo::core STATIC IMPORTED)
add_library(foo::extra SHARED IMPORTED)
`},
	})
	raw, err := exports.FromBundle(dir)
	if err != nil {
		t.Fatal(err)
	}

	el := exports.AsElement("components/foo", raw, nil)
	if el.Name != "components/foo" {
		t.Errorf("Element.Name = %q, want components/foo", el.Name)
	}
	if len(el.Exports) != 2 {
		t.Fatalf("Exports = %d, want 2", len(el.Exports))
	}
	for _, e := range el.Exports {
		switch e.CMakeTarget {
		case "foo::core":
			if e.BazelLabel != "//elements/components/foo:core" {
				t.Errorf("core BazelLabel = %q", e.BazelLabel)
			}
		case "foo::extra":
			if e.BazelLabel != "//elements/components/foo:extra" {
				t.Errorf("extra BazelLabel = %q", e.BazelLabel)
			}
		default:
			t.Errorf("unexpected export %s", e.CMakeTarget)
		}
	}
}

// _ keeps manifest imported even when refactoring temporarily silences the
// only call site; in normal builds AsElement returns *manifest.Element.
var _ = manifest.Element{}
