// Package optionsettings emits the //options package BUILD content
// that backs the option fold's select() arms.
//
// Stages a+b of the option-lift ROADMAP.md item. lower's option fold
// (--lift-options) projects a lifted cmake option()'s attribute
// deltas onto //options:<name>_{on,off} select() arms
// (lower.OptionCellLabel). Those labels must resolve to real
// config_settings for the converted BUILD to load. This package
// renders a project-level //options package: one bool_flag per
// lifted option (build_setting_default = the value the primary
// configure resolved, so an unset flag reproduces the baked
// baseline view) plus the _on/_off config_setting pair, toggled at
// build time with --//options:<name>=true|false.
//
// A dedicated bool_flag per option rather than a shared
// string-valued dial keeps each cmake option() independently
// toggleable — exactly the cache-entry semantics cmake gives them.
//
// The generated BUILD is byte-stable across runs against the same
// option set and carries a leading attribution header.
package optionsettings

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// Option is one lifted cmake option(): its cache-entry name and the
// boolean value the primary configure resolved it to (the flag's
// default, so builds that don't set the flag get the baked view).
type Option struct {
	Name    string
	Default bool
}

// Emit renders the //options package BUILD content for the given
// lifted options. Names are lowercased to match lower's
// OptionCellLabel (`//options:<name-lowercased>_{on,off}`),
// de-duplicated (first occurrence's default wins), and sorted for
// byte stability. Returns nil when no options are supplied — no
// fold to back, no //options package needed.
func Emit(options []Option) []byte {
	seen := map[string]bool{}
	var opts []Option
	for _, o := range options {
		n := strings.ToLower(o.Name)
		if n == "" || seen[n] {
			continue
		}
		seen[n] = true
		opts = append(opts, Option{Name: n, Default: o.Default})
	}
	if len(opts) == 0 {
		return nil
	}
	sort.Slice(opts, func(i, j int) bool { return opts[i].Name < opts[j].Name })

	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString(loads)

	for _, o := range opts {
		def := "False"
		if o.Default {
			def = "True"
		}
		b.WriteString("\n")
		b.WriteString("bool_flag(\n")
		fmt.Fprintf(&b, "    name = %q,\n", o.Name)
		fmt.Fprintf(&b, "    build_setting_default = %s,\n", def)
		b.WriteString("    visibility = [\"//visibility:public\"],\n")
		b.WriteString(")\n")
		for _, arm := range []struct{ suffix, value string }{
			{"_on", "True"},
			{"_off", "False"},
		} {
			b.WriteString("\n")
			b.WriteString("config_setting(\n")
			fmt.Fprintf(&b, "    name = %q,\n", o.Name+arm.suffix)
			fmt.Fprintf(&b, "    flag_values = {\":%s\": %q},\n", o.Name, arm.value)
			b.WriteString("    visibility = [\"//visibility:public\"],\n")
			b.WriteString(")\n")
		}
	}
	return b.Bytes()
}

const header = `# Generated by convert-element-cmake. DO NOT EDIT.
#
# bool_flags + config_settings backing the option fold's
# //options:<name>_{on,off} select() arms — one flag per cmake
# option() lifted via --lift-options. Toggle an option at build time
# with --//options:<name>=true|false; the default reproduces the
# value the convert-time configure resolved.
`

const loads = `
load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")
`
