package main

import (
	"fmt"
	"path/filepath"
)

func init() { registerHandler(flatpakRepoHandler{}) }

// flatpakRepoHandler renders kind:flatpak_repo as an
// empty-install genrule. The plugin is from
// buildstream-plugins-community: it packages dep install trees
// into a flatpak ostree repository, the runtime artifact a
// flatpak install pulls from. Companion to kind:flatpak_image
// (the image's contents) — flatpak_repo wraps one or more
// images into a distributable repo with refs / commits /
// summary files.
//
// 1 of FDSDK's elements uses kind:flatpak_repo (0.1 % of the
// total). FDSDK's release pipeline assembles the repo for
// distribution; v1's placeholder lets render of FDSDK fixtures
// reach completion without breaking the graph.
//
// v1 caveats — same shape as collect_manifest:
//   - The emitted tarball is empty; downstream elements that
//     publish the assembled repo in real builds will get
//     nothing useful from it. Fine for write-a's render
//     success; bazel-build-time correctness for these elements
//     lands when the real plugin's logic is ported (ostree
//     repo init + per-image commit + summary regen).
//   - The element's build-depends are still honored at the
//     graph level so dep-ordering and source-fetch lookups
//     stay correct.
type flatpakRepoHandler struct{}

func (flatpakRepoHandler) Kind() string                                 { return "flatpak_repo" }
func (flatpakRepoHandler) NeedsSources() bool                           { return false }
func (flatpakRepoHandler) HasProjectABuild() bool                       { return true }
func (flatpakRepoHandler) DefaultReadPathsPatterns() *readPathsPatterns { return nil }

func (flatpakRepoHandler) RenderA(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:flatpak_repo — FDSDK flatpak-repo packager from
# buildstream-plugins-community. v1 emits an empty install tree
# as a placeholder; real packaging (ostree init + per-dep-image
# commit + summary regen, output is the distributable
# repository tree) lands when an FDSDK fixture forces it.

load("@rules_buildstream_bazel//rules:install.bzl", "pipeline_install")

package(default_visibility = ["//visibility:public"])

pipeline_install(
    name = "%[1]s_install",
    srcs = [],
    command = """
        mkdir -p "@@INSTALL_DIR@@"
    """,
)
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (flatpakRepoHandler) RenderB(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:flatpak_repo — install tree produced by project A's
# genrule (see //elements/%[1]s in project A). Placeholder
# until the typed-filegroup wrapper lands.
filegroup(name = "BUILD_NOT_YET_STAGED", srcs = [])
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}
