package main

import (
	"fmt"
	"path/filepath"
)

func init() { registerHandler(collectIntegrationHandler{}) }

// collectIntegrationHandler renders kind:collect_integration as
// an empty-install genrule. The plugin is from
// buildstream-plugins-community; real behaviour walks dep
// install trees for integration-command metadata (the
// `integration-commands` field on each dep's public domain
// info) and assembles a runtime integration script into
// %{install-root}/usr/share/integration/integrate.sh. v1
// produces a placeholder install_tree.tar so downstream
// consumers can reference it without breaking the graph.
//
// 2 of FDSDK's elements use kind:collect_integration (0.2 % of
// the total). Tiny, but the kind shows up in FDSDK image
// assembly so the placeholder unblocks render of those
// fixtures.
//
// v1 caveats — same shape as collect_manifest:
//   - The emitted tarball is empty; downstream elements that
//     execute the assembled integration script in real builds
//     will get nothing useful from it. Fine for write-a's
//     render success; bazel-build-time correctness for these
//     elements lands when the real plugin's logic is ported.
//   - The element's build-depends are still honored at the
//     graph level (loadGraph wires them onto element.Deps), so
//     dep-ordering and source-fetch lookups stay correct.
type collectIntegrationHandler struct{}

func (collectIntegrationHandler) Kind() string                                 { return "collect_integration" }
func (collectIntegrationHandler) NeedsSources() bool                           { return false }
func (collectIntegrationHandler) HasProjectABuild() bool                       { return true }
func (collectIntegrationHandler) DefaultReadPathsPatterns() *readPathsPatterns { return nil }

func (collectIntegrationHandler) RenderA(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:collect_integration — FDSDK integration-script collector
# from buildstream-plugins-community. v1 emits an empty install
# tree as a placeholder; real assembly (walks dep public-domain
# 'integration-commands' metadata into
# %%{install-root}/usr/share/integration/integrate.sh) lands when
# an FDSDK fixture forces it.

load("@rules_buildstream_bazel//rules:install.bzl", "pipeline_install")

package(default_visibility = ["//visibility:public"])

pipeline_install(
    name = "%[1]s_install",
    srcs = [],
    command = """
        mkdir -p "@@INSTALL_DIR@@"
    """,
)
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (collectIntegrationHandler) RenderB(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:collect_integration — install tree produced by project A's
# genrule (see //elements/%[1]s in project A). Placeholder until
# the typed-filegroup wrapper lands.
filegroup(name = "BUILD_NOT_YET_STAGED", srcs = [])
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}
