package main

import (
	"fmt"
	"path/filepath"
)

func init() { registerHandler(checkForbiddenHandler{}) }

// checkForbiddenHandler renders kind:check_forbidden as an
// empty-install rule. The plugin is a CI-style assertion
// from buildstream-plugins-community: it walks dep install
// trees and fails if any path matches an operator-declared
// forbidden glob (e.g. asserting no element under
// `components/sdk/` accidentally exposes
// `/usr/lib/debug/`). The assertion runs at build time and
// produces no install bytes by design — even the real plugin's
// install-root TreeArtifact is conceptually empty.
//
// 2 of FDSDK's elements use kind:check_forbidden (0.2 % of the
// total). Both are CI-only assertion gates.
//
// v1 caveats:
//   - The forbidden-path assertion DOESN'T run; v1 succeeds
//     unconditionally. A real port runs the dep-tree walk +
//     glob match against the operator-declared config-block
//     pattern set, failing the bazel build with a clear
//     diagnostic when a match fires.
//   - For the bazel build to surface a CI violation, the
//     bazel-build-time correctness path needs the dep install
//     trees and the assertion config. v1's stub matches today's
//     placeholder-handler convention (collect_manifest, etc.);
//     porting the real check lands when an FDSDK fixture forces
//     it.
//   - The element's build-depends are still honored at the
//     graph level so dep-ordering and source-fetch lookups stay
//     correct.
type checkForbiddenHandler struct{}

func (checkForbiddenHandler) Kind() string                                 { return "check_forbidden" }
func (checkForbiddenHandler) NeedsSources() bool                           { return false }
func (checkForbiddenHandler) HasProjectABuild() bool                       { return true }
func (checkForbiddenHandler) DefaultReadPathsPatterns() *readPathsPatterns { return nil }

func (checkForbiddenHandler) RenderA(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:check_forbidden — FDSDK forbidden-path CI assertion from
# buildstream-plugins-community. v1 succeeds unconditionally;
# real assertion (dep-tree walk + glob match against operator-
# declared forbidden patterns, fail-with-diagnostic on match)
# lands when an FDSDK fixture forces it.

load("@rules_buildstream_bazel//rules:install.bzl", "pipeline_install")

package(default_visibility = ["//visibility:public"])

pipeline_install(
    name = "%[1]s_install",
    srcs = [],
    command = """
        mkdir -p "@@INSTALL_DIR@@"
    """,
)
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (checkForbiddenHandler) RenderB(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:check_forbidden — install tree produced by project A's
# genrule (see //elements/%[1]s in project A). Placeholder until
# the assertion-running wrapper lands.
filegroup(name = "BUILD_NOT_YET_STAGED", srcs = [])
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}
