package main

import (
	"fmt"
	"os"
	"path/filepath"
)

func init() { registerHandler(bazelHandler{}) }

// bazelHandler renders a kind:bazel element. Sources already
// contain Bazel BUILD files; the element is a passthrough
// from BuildStream's perspective — no per-kind translator
// runs, no introspection happens, the existing BUILD files
// are the conversion result. write-a stages the source tree
// verbatim into project B's elements/<name>/ and lets
// downstream consumers reference whatever rules the source
// tree's BUILD declares.
//
// Use case: an element whose upstream is already Bazel-native
// (rules_cc / rules_python / a hand-authored BUILD over a
// curated source set) and the conversion just needs to slot
// it into the project A / project B layout. Also useful for
// hand-overriding kind:cmake / kind:autotools converter
// output — fork the converted BUILD, edit it, declare the
// element as kind:bazel pointing at the edited tree.
//
// Project A side: a no-target marker package. Same shape as
// kind:import / kind:stack / kind:filter — bazel has no
// translator action to schedule.
//
// Project B side: stage the source tree verbatim. The source
// tree is expected to contain a top-level BUILD.bazel (or
// BUILD); we don't generate one. The cross-element label is
// whatever the source's BUILD declares — the convention is
// that the element exposes a target with the element's name
// (so //elements/<name>:<name> resolves), but bazelHandler
// doesn't enforce that.
//
// Operator override path (--build-files-dir): when
// applyBuildFileOverrides has re-stamped a non-bazel element
// to kind:bazel and recorded an elem.OverrideBuildDir,
// RenderB stages sources as usual, then copies the override
// subtree on top — the operator's BUILD.bazel (and any
// subpackage BUILDs, .bzl helpers, etc.) shadow whatever
// the source tree carried. This is the "I have a hand-
// authored BUILD for this element but don't want to fork the
// .bst" knob.
type bazelHandler struct{}

func (bazelHandler) Kind() string                                 { return "bazel" }
func (bazelHandler) NeedsSources() bool                           { return true }
func (bazelHandler) HasProjectABuild() bool                       { return false }
func (bazelHandler) DefaultReadPathsPatterns() *readPathsPatterns { return nil }

func (bazelHandler) RenderA(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:bazel — no project-A action. The element's source tree
# already contains BUILD files; project B uses them verbatim.
# See //elements/%s/... in project B's tree for the targets the
# source defines.
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (bazelHandler) RenderB(elem *element, elemPkg string) error {
	if err := stageAllSources(elem, elemPkg); err != nil {
		return err
	}
	// Operator-supplied override subtree (--build-files-dir):
	// copy on top of the staged sources. copyTree's per-file
	// O_TRUNC means the override's BUILD.bazel / .bzl files
	// naturally shadow any colliding source files (relevant
	// when the source tree itself was a kind:bazel passthrough
	// shipping its own BUILD). Bazel rejects packages
	// declaring both BUILD and BUILD.bazel, so for every
	// package the override tree touches, strip the OTHER name
	// at the mirrored elemPkg location before the copy lands.
	// This runs over the whole override subtree, not just the
	// top level, because operator-authored subpackage BUILDs
	// can collide with source-shipped sibling files at the
	// same depth.
	if elem.OverrideBuildDir != "" {
		if err := stripCollidingBuildNames(elem.OverrideBuildDir, elemPkg); err != nil {
			return fmt.Errorf("strip colliding BUILD names for %q: %w", elem.Name, err)
		}
		return copyTree(elem.OverrideBuildDir, elemPkg)
	}
	// kind:bazel's contract: source tree contains its own
	// BUILD.bazel (or BUILD). Detect; warn if missing — the
	// element is then effectively a filegroup with no rule
	// surface, which is almost certainly a misconfiguration.
	for _, name := range []string{"BUILD.bazel", "BUILD"} {
		if _, err := os.Stat(filepath.Join(elemPkg, name)); err == nil {
			return nil
		}
	}
	// No BUILD found — synthesize a placeholder that Bazel
	// will accept (so `bazel build //...` doesn't fail with
	// "no such package") but loudly flags the gap.
	placeholder := `# Generated by cmd/write-a. Do not edit by hand.
# kind:bazel — element's source tree had no BUILD.bazel / BUILD.
# This is almost certainly a misconfiguration: kind:bazel expects
# the source to be Bazel-native. Either:
#   - Add a BUILD.bazel to the source tree, or
#   - Change the element's kind to kind:import (filegroup-only)
#     or one of the trace-driven kinds (cmake / autotools / make).
package(default_visibility = ["//visibility:public"])
`
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), placeholder)
}

// stripCollidingBuildNames walks overrideDir for every
// BUILD-family file and removes the OTHER name (BUILD ↔
// BUILD.bazel) from the mirrored location in elemPkg. Bazel
// rejects packages declaring both names; without this strip,
// a source-shipped `sub/BUILD` next to an override-shipped
// `sub/BUILD.bazel` would survive copyTree and fail at load
// time.
func stripCollidingBuildNames(overrideDir, elemPkg string) error {
	return filepath.Walk(overrideDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		var other string
		switch filepath.Base(path) {
		case "BUILD.bazel":
			other = "BUILD"
		case "BUILD":
			other = "BUILD.bazel"
		default:
			return nil
		}
		rel, err := filepath.Rel(overrideDir, filepath.Dir(path))
		if err != nil {
			return err
		}
		// os.Remove returning IsNotExist is the expected
		// no-collision case — discard.
		if err := os.Remove(filepath.Join(elemPkg, rel, other)); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	})
}
