package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Round-2 trace-driven rendering for any pipeline-shape kind.
//
// Background. Round 1 of kind:autotools (the historical shape)
// runs the converter inline in project B's coarse install
// genrule: configure / make / make-install under build-tracer,
// then convert-element-autotools reads the trace and emits
// BUILD.bazel.out as an additional output of the SAME genrule
// action. Project A's per-element BUILD is just a marker
// filegroup pointing at B.
//
// Round 2 (gated on autotoolsConfig.round2Enabled) splits the
// work:
//
//   - PROJECT A hosts a per-element converter genrule. Its srcs
//     include @trace_<elem>//:trace — a Bazel external repo
//     declared by rules/traces.bzl, whose load-time _trace_repo
//     impl shells out to cmd/trace-lookup. AC hit ⇒ the fileset
//     resolves to trace.log + make-db.txt via the cas-fuse mount
//     and the converter emits cc_library / cc_binary into
//     BUILD.bazel.out. AC miss ⇒ the fileset is empty and the
//     converter writes a placeholder BUILD.bazel.out.
//   - PROJECT B hosts the coarse install genrule (build pipeline
//     wrapped in build-tracer) PLUS an inline cmd/trace-publish
//     call: once make-install has produced trace.log and the
//     post-process step has produced make-db.txt, trace-publish
//     packs both as a REAPI Directory, uploads to CAS, and writes
//     an ActionResult under SyntheticActionDigest(srckey).
//
// The 3' → 2' feedback loop in docs/three-pass-flow.md is realized
// by the AC: the round-1 pass-3 publish lands at the same key the
// round-2 pass-2 lookup queries. Once published — globally, once
// per srckey — every subsequent render of project A on any node
// sees the AC hit and the converter emits fine-grained cc rules
// without re-running the build.
//
// kind-agnostic. The code in this file does not know what kind it
// renders for. cmd/write-a/handler_autotools_native.go calls
// these helpers passing autotoolsSrckeyPatterns() + the autotools
// dep-kind list; pipelineHandler-shaped kinds (make, etc.) opt in
// by setting traceDrivenSrckeyPatterns + going through the
// pipelineHandler dispatch in handler_pipeline.go. New kinds
// joining the trace-driven path are a one-line opt-in once their
// srckey-pattern set is decided.

// renderTraceDrivenRound2A emits project A's per-element BUILD
// for the round-2 path:
//
//	srckey.txt + srckey-breakdown.txt   (debug + AC-key seed)
//	BUILD.bazel containing the converter genrule:
//	  srcs    = [@src_<key>//:tree, @trace_<elem>//:trace,
//	             imports.json (optional), srckey.txt]
//	  outs    = ["BUILD.bazel.out"]
//	  tools   = ["//tools:convert-element-autotools"]
//	  cmd     = stage @trace_<elem>//:trace into a tmpdir,
//	            invoke convert-element-autotools --trace-dir.
//
// The kindName parameter only feeds the comment header of the
// rendered BUILD; it does not affect the genrule's behavior
// (convert-element-autotools is kind-agnostic at runtime).
func renderTraceDrivenRound2A(elem *element, elemPkg, kindName string, srckeyPatterns *readPathsPatterns) error {
	if err := renderSrckey(elem, elemPkg, srckeyPatterns); err != nil {
		return err
	}
	hasImports, err := writeAutotoolsImportsManifest(elem, elemPkg)
	if err != nil {
		return err
	}

	srcLabels := []string{}
	for _, rs := range elem.Sources {
		key := sourceKey(rs)
		if key == "" {
			continue
		}
		srcLabels = append(srcLabels, fmt.Sprintf(`"@src_%s//:tree"`, key))
	}
	srcLabels = append(srcLabels, fmt.Sprintf(`"@trace_%s//:trace"`, elem.Name))
	srcLabels = append(srcLabels, `"srckey.txt"`)
	if hasImports {
		srcLabels = append(srcLabels, `"imports.json"`)
	}

	importsFlag := ""
	if hasImports {
		importsFlag = ` \
            --imports-manifest="$(location imports.json)"`
	}

	build := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:%[4]s round-2 — pass-2 converter genrule.
#
# Reads @trace_%[1]s//:trace (a load-time _trace_repo lookup
# against the REAPI ActionCache; see rules/traces.bzl). When the
# trace fileset is non-empty (AC hit), convert-element-autotools
# emits cc_library / cc_binary into BUILD.bazel.out. When empty
# (AC miss / round-2 boot phase), the converter writes a
# placeholder BUILD.bazel.out and project B's coarse install
# genrule remains the buildable target until pass-3 publishes.

package(default_visibility = ["//visibility:public"])

genrule(
    name = "%[1]s_build",
    srcs = [%[2]s],
    outs = ["BUILD.bazel.out"],
    tools = ["//tools:convert-element-autotools"],
    cmd = """
        # Stage trace.log + make-db.txt (when present) into a
        # known dir. The @trace_%[1]s//:trace filegroup may resolve
        # to two files (AC hit) or zero (AC miss); the converter's
        # --trace-dir mode handles both shapes.
        TRACE_DIR="$$(mktemp -d)"
        for src in $(SRCS); do
            case "$$src" in
                */trace_dir/trace.log) cp -L "$$src" "$$TRACE_DIR/trace.log" ;;
                */trace_dir/make-db.txt) cp -L "$$src" "$$TRACE_DIR/make-db.txt" ;;
            esac
        done
        $(location //tools:convert-element-autotools) \
            --trace-dir="$$TRACE_DIR" \
            --out-build="$(location BUILD.bazel.out)"%[3]s
    """,
)
`, elem.Name, strings.Join(srcLabels, ", "), importsFlag, kindName)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), build)
}

// pipelineTraceExtensionRound2 is the pipelineExtension for
// project B's coarse install genrule under round-2: build-tracer
// wraps configure/build/install, the genrule's AppendCmd
// post-processes make-db and runs trace-publish. Outputs:
// install_tree.tar + trace.log + make-db.txt + the per-element
// generated-headers.txt the autotools handler already emits
// (kept under round-2 too — generated-headers feeds future
// converter improvements without re-running the action).
//
// imports.json is intentionally NOT in ExtraSrcs here: the
// round-2 B-side install genrule doesn't run the converter
// (the converter moved to project A's per-element converter
// genrule, which references imports.json via its own srcs).
// Adding the file to this action's inputs would invalidate the
// install action's cache key on every imports.json change with
// no corresponding behavioral effect on the build.
//
// depKindAllow is the set of dep `Bst.Kind` strings whose
// install_tree.tar tarballs should be staged + extracted under
// $DEP_PREFIX so the build pipeline's compile commands can find
// dep headers / libraries. autotools passes []string{"autotools"};
// kind:make passes []string{"make"}; cross-kind dep wiring is a
// follow-up once the fixtures land.
func pipelineTraceExtensionRound2(elem *element, depKindAllow []string) *pipelineExtension {
	ext := &pipelineExtension{
		WrapPipelineCmds: wrapAutotoolsPipelineCmds,
		AppendCmd:        pipelineTracePublishStep(elem.Name),
		ExtraOuts: []string{
			"trace.log",
			"make-db.txt",
			"generated-headers.txt",
		},
		ExtraTools: []string{
			"//tools:build-tracer",
			"//tools:trace-publish",
		},
		// srckey.txt is the only ExtraSrcs entry under round-2:
		// trace-publish reads it to derive the synthetic Action
		// digest. The caller (pipelineHandler.RenderB or
		// autotoolsHandler.RenderB) calls renderSrckey before
		// the genrule fires so the file exists at action time.
		ExtraSrcs: []string{"srckey.txt"},
	}

	allow := map[string]bool{}
	for _, k := range depKindAllow {
		allow[k] = true
	}
	var depLabels []string
	for _, dep := range elem.Deps {
		if dep == nil || !allow[dep.Bst.Kind] {
			continue
		}
		depLabels = append(depLabels, fmt.Sprintf("//elements/%s:install_tree.tar", dep.Name))
	}
	if len(depLabels) > 0 {
		ext.DepLabels = depLabels
		ext.DepExtractCmd = autotoolsDepExtractCmd()
	}
	return ext
}

// pipelineTracePublishStep is the AppendCmd snippet that runs
// after the build pipeline. Three sub-steps:
//
//  1. Capture the post-build make database to make-db.txt
//     (mirrors the inline sed filter so byte-stable across runs).
//  2. Copy the canonical trace.log out of $$AUTOTOOLS_TRACE
//     so it lands at the genrule's declared trace.log output.
//  3. Invoke trace-publish, IFF the action environment supplies
//     CAS_GRPC_ADDR (devs running locally without a remote cache
//     leave the variable unset; the build still succeeds, no AC
//     entry is published).
//
// The step is kind-agnostic at runtime: any pipeline kind's
// build that produces a Makefile-compatible artifact can run
// `make -np` (defaults to a no-op when no Makefile is present;
// `|| true` keeps the genrule action alive). For kinds whose
// build never produces a Makefile (kind:script edge cases),
// make-db.txt ends up empty — the converter tolerates that.
func pipelineTracePublishStep(elemName string) string {
	_ = elemName // reserved for future per-element diagnostics
	return `        # === make-db post-process (round 2) ===
        # Same sed filter the autotools install genrule applies
        # inline (drop variant lines whose bytes drift across
        # runs of an otherwise-identical build: mtimes,
        # file-count summaries, db print timestamps). The
        # publisher path's tracenorm.FilterMakeDB re-applies the
        # same drop list defensively in-process.
        ( make -np 2>/dev/null || true ) \
            | sed -E '/^#[[:space:]]+Last modified /d; /\(device [0-9]+, inode [0-9]+\): [0-9]+ files,/d; /^# [0-9]+ files,.*impossibilities in /d; /^# Make data base, printed on /d; /^# Finished Make data base on /d' \
            | sed -e "s|$$INSTALL_ROOT|/INSTALL_ROOT|g" \
                  -e "s|$$BUILD_ROOT|/BUILD_ROOT|g" \
                  -e "s|$${DEP_PREFIX:-/__unset_dep_prefix__}|/DEP_PREFIX|g" \
            > "$$EXEC_ROOT/$(location make-db.txt)"

        # Surface the canonical trace.log as a declared output of
        # this genrule. trace-publish reads it from here.
        cp -L "$$AUTOTOOLS_TRACE" "$$EXEC_ROOT/$(location trace.log)"

        # Publish to the AC iff a remote is configured. Empty
        # CAS_GRPC_ADDR ⇒ skip (e.g. local dev without buildbarn);
        # the build succeeds, no AC entry is written, and the
        # next render of project A sees a miss → coarse fallback.
        # The trace-publish binary itself ALSO short-circuits on
        # empty --cas; checking here keeps the genrule output
        # readable when a developer is debugging.
        cd "$$EXEC_ROOT"
        if [ -n "$${CAS_GRPC_ADDR:-}" ]; then
            $(location //tools:trace-publish) \
                --cas="$${CAS_GRPC_ADDR}" \
                --srckey="$$(cat $(location srckey.txt) | tr -d '[:space:]')" \
                --trace="$(location trace.log)" \
                --make-db="$(location make-db.txt)" >/dev/null
        fi`
}
