package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Round-2 trace-driven kind:autotools rendering.
//
// Round 1 (default today) runs the converter inline in project
// B's coarse install genrule: configure / make / make-install
// under build-tracer, then convert-element-autotools reads the
// trace and emits BUILD.bazel.out as an additional output of the
// SAME genrule action. Project A's per-element BUILD is just a
// marker filegroup pointing at B.
//
// Round 2 (gated on autotoolsConfig.round2Enabled, off by default
// while the architectural change is rolled out) splits the work:
//
//   - PROJECT A hosts a per-element converter genrule. Its srcs
//     include @trace_<elem>//:trace — a Bazel external repo
//     declared by rules/traces.bzl, whose load-time _trace_repo
//     impl shells out to cmd/trace-lookup. AC hit ⇒ the fileset
//     resolves to trace.log + make-db.txt via the cas-fuse mount
//     and the converter emits cc_library / cc_binary into
//     BUILD.bazel.out. AC miss ⇒ the fileset is empty and the
//     converter writes a placeholder BUILD.bazel.out.
//   - PROJECT B hosts the coarse install genrule (same shape as
//     round 1's pipeline) PLUS an inline cmd/trace-publish call:
//     once configure / make / make-install + build-tracer have
//     produced trace.log + the make-db post-process step has
//     produced make-db.txt, trace-publish packs both as a REAPI
//     Directory, uploads to CAS, and writes an ActionResult under
//     SyntheticActionDigest(srckey). The converter no longer runs
//     here.
//
// The 3' → 2' feedback in docs/three-pass-flow.md is realized by
// the AC: the round-1 pass-3 publish lands at the same key the
// round-2 pass-2 lookup queries. Once published — globally, once
// per srckey — every subsequent render of project A on any node
// sees the AC hit and the converter emits fine-grained cc rules
// without re-running the autotools build.

// renderAutotoolsRound2A emits project A's per-element BUILD for
// the round-2 path:
//
//	srckey.txt + srckey-breakdown.txt   (debug + AC-key seed)
//	BUILD.bazel containing the converter genrule:
//	  srcs    = [@src_<key>//:tree, @trace_<elem>//:trace,
//	             imports.json (optional), srckey.txt]
//	  outs    = ["BUILD.bazel.out"]
//	  tools   = ["//tools:convert-element-autotools"]
//	  cmd     = stage @trace_<elem>//:trace into a tmpdir,
//	            invoke convert-element-autotools --trace-dir.
func renderAutotoolsRound2A(elem *element, elemPkg string) error {
	if err := renderSrckey(elem, elemPkg, autotoolsSrckeyPatterns()); err != nil {
		return err
	}
	hasImports, err := writeAutotoolsImportsManifest(elem, elemPkg)
	if err != nil {
		return err
	}

	// Source label: the @src_<key>//:tree filegroup when the
	// element has a non-kind:local source resolved via the
	// sources extension; otherwise the round-2 path requires
	// the FUSE-mounted source tree (kind:local-only autotools
	// elements aren't a round-2 target — they have no AC-keyed
	// srckey identity that crosses machines). The render still
	// emits a converter genrule for completeness; the genrule's
	// srcs will be empty for kind:local elements until they're
	// staged via the sources extension.
	srcLabels := []string{}
	for _, rs := range elem.Sources {
		key := sourceKey(rs)
		if key == "" {
			continue
		}
		srcLabels = append(srcLabels, fmt.Sprintf(`"@src_%s//:tree"`, key))
	}
	srcLabels = append(srcLabels, fmt.Sprintf(`"@trace_%s//:trace"`, elem.Name))
	srcLabels = append(srcLabels, `"srckey.txt"`)
	if hasImports {
		srcLabels = append(srcLabels, `"imports.json"`)
	}

	importsFlag := ""
	if hasImports {
		importsFlag = ` \
            --imports-manifest="$(location imports.json)"`
	}

	build := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:autotools round-2 — pass-2 converter genrule.
#
# Reads @trace_%[1]s//:trace (a load-time _trace_repo lookup
# against the REAPI ActionCache; see rules/traces.bzl). When the
# trace fileset is non-empty (AC hit), convert-element-autotools
# emits cc_library / cc_binary into BUILD.bazel.out. When empty
# (AC miss / round-2 boot phase), the converter writes a
# placeholder BUILD.bazel.out and project B's coarse install
# genrule remains the buildable target until pass-3 publishes.

package(default_visibility = ["//visibility:public"])

genrule(
    name = "%[1]s_build",
    srcs = [%[2]s],
    outs = ["BUILD.bazel.out"],
    tools = ["//tools:convert-element-autotools"],
    cmd = """
        # Stage trace.log + make-db.txt (when present) into a
        # known dir. The @trace_%[1]s//:trace filegroup may resolve
        # to two files (AC hit) or zero (AC miss); the converter's
        # --trace-dir mode handles both shapes.
        TRACE_DIR="$$(mktemp -d)"
        for src in $(SRCS); do
            case "$$src" in
                */trace_dir/trace.log) cp -L "$$src" "$$TRACE_DIR/trace.log" ;;
                */trace_dir/make-db.txt) cp -L "$$src" "$$TRACE_DIR/make-db.txt" ;;
            esac
        done
        $(location //tools:convert-element-autotools) \
            --trace-dir="$$TRACE_DIR" \
            --out-build="$(location BUILD.bazel.out)"%[3]s
    """,
)
`, elem.Name, strings.Join(srcLabels, ", "), importsFlag)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), build)
}

// autotoolsTraceExtensionRound2 is the project-B pipelineExtension
// for round-2: the coarse install genrule wraps configure/build/
// install in build-tracer, post-processes make-db, and ends with
// an inline trace-publish call (NO converter). Outputs shrink to
// install_tree.tar + trace.log + make-db.txt — the 1:1 inputs
// trace-publish needs.
//
// Round 1's autotoolsTraceExtension keeps running the converter
// inline; this is a parallel implementation gated on
// autotoolsConfig.round2Enabled. The two paths share
// wrapAutotoolsPipelineCmds (build-tracer wrapping is identical)
// and autotoolsDepExtractCmd (dep tar extraction is identical).
func autotoolsTraceExtensionRound2(elem *element, hasImports bool) *pipelineExtension {
	ext := &pipelineExtension{
		WrapPipelineCmds: wrapAutotoolsPipelineCmds,
		AppendCmd:        autotoolsTracePublishStep(elem.Name),
		ExtraOuts: []string{
			"trace.log",
			"make-db.txt",
			"generated-headers.txt",
		},
		ExtraTools: []string{
			"//tools:build-tracer",
			"//tools:trace-publish",
		},
	}
	if hasImports {
		ext.ExtraSrcs = []string{"imports.json"}
	}
	// srckey.txt is also a genrule input — trace-publish reads
	// it to derive the synthetic Action digest. It's emitted by
	// renderAutotoolsRound2A in project A; project B's RenderB
	// also calls renderSrckey so the file exists in B's elemPkg.
	ext.ExtraSrcs = append(ext.ExtraSrcs, "srckey.txt")
	var depLabels []string
	for _, dep := range elem.Deps {
		if dep == nil || dep.Bst.Kind != "autotools" {
			continue
		}
		depLabels = append(depLabels, fmt.Sprintf("//elements/%s:install_tree.tar", dep.Name))
	}
	if len(depLabels) > 0 {
		ext.DepLabels = depLabels
		ext.DepExtractCmd = autotoolsDepExtractCmd()
	}
	return ext
}

// autotoolsTracePublishStep is the AppendCmd snippet that runs
// after the build pipeline. Three sub-steps:
//
//  1. Capture the post-build make database to make-db.txt
//     (mirrors round 1's same-named step verbatim, with the
//     same sed filter for run-to-run determinism).
//  2. Copy the canonical trace.log out of $$AUTOTOOLS_TRACE
//     so it lands at the genrule's declared trace.log output.
//  3. Invoke trace-publish, IFF the action environment
//     supplies CAS_GRPC_ADDR (devs running locally without
//     a remote cache leave the variable unset; the build
//     still succeeds, just no AC entry is published).
//
// elemName threads through so the publish call can read the
// per-element srckey.txt via $(location). srckey.txt is added
// to the genrule's srcs by autotoolsTraceExtensionRound2.
func autotoolsTracePublishStep(elemName string) string {
	_ = elemName // reserved for future per-element diagnostics
	return `        # === make-db post-process (round 2) ===
        # Same sed filter as round 1: drop the variant lines
        # whose bytes drift across runs of an otherwise-identical
        # build (mtimes, file-count summaries, db print
        # timestamps). The publisher path's tracenorm.FilterMakeDB
        # re-applies the same drop list defensively in-process.
        ( make -np 2>/dev/null || true ) \
            | sed -E '/^#[[:space:]]+Last modified /d; /\(device [0-9]+, inode [0-9]+\): [0-9]+ files,/d; /^# [0-9]+ files,.*impossibilities in /d; /^# Make data base, printed on /d; /^# Finished Make data base on /d' \
            | sed -e "s|$$INSTALL_ROOT|/INSTALL_ROOT|g" \
                  -e "s|$$BUILD_ROOT|/BUILD_ROOT|g" \
                  -e "s|$${DEP_PREFIX:-/__unset_dep_prefix__}|/DEP_PREFIX|g" \
            > "$$EXEC_ROOT/$(location make-db.txt)"

        # Surface the canonical trace.log as a declared output of
        # this genrule. trace-publish reads it from here.
        cp -L "$$AUTOTOOLS_TRACE" "$$EXEC_ROOT/$(location trace.log)"

        # Publish to the AC iff a remote is configured. Empty
        # CAS_GRPC_ADDR ⇒ skip (e.g. local dev without buildbarn);
        # the build succeeds, no AC entry is written, and the
        # next render of project A sees a miss → coarse fallback.
        # The trace-publish binary itself ALSO short-circuits on
        # empty --cas; checking here keeps the genrule output
        # readable when a developer is debugging.
        cd "$$EXEC_ROOT"
        if [ -n "$${CAS_GRPC_ADDR:-}" ]; then
            $(location //tools:trace-publish) \
                --cas="$${CAS_GRPC_ADDR}" \
                --srckey="$$(cat $(location srckey.txt) | tr -d '[:space:]')" \
                --trace="$(location trace.log)" \
                --make-db="$(location make-db.txt)" >/dev/null
        fi`
}
