package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Round-2 trace-driven rendering for any pipeline-shape kind.
//
// Background. Round 1 of kind:autotools (the historical shape)
// runs the converter inline in project B's coarse install
// genrule: configure / make / make-install under build-tracer,
// then convert-element-trace reads the trace and emits
// BUILD.bazel.out as an additional output of the SAME genrule
// action. Project A's per-element BUILD is just a marker
// filegroup pointing at B.
//
// Round 2 (gated on traceConfig.round2Enabled) splits the
// work:
//
//   - PROJECT A hosts a per-element converter genrule. Its srcs
//     include :<elem>_trace_load — an action-time trace_load
//     target declared in the same per-element package, whose
//     action shells to cmd/trace-lookup. AC hit ⇒ trace.log +
//     make-db.txt materialize into the rule's declared outputs
//     via gRPC fetch and the converter emits cc_library /
//     cc_binary into BUILD.bazel.out. AC miss ⇒ zero-byte trace
//     files + a "miss" marker; the converter writes a
//     placeholder BUILD.bazel.out.
//   - PROJECT B hosts the coarse install genrule (build pipeline
//     wrapped in build-tracer) PLUS an inline cmd/trace-publish
//     call: once make-install has produced trace.log and the
//     post-process step has produced make-db.txt, trace-publish
//     packs both as a REAPI Directory, uploads to CAS, and writes
//     an ActionResult under SyntheticActionDigest(srckey).
//
// The 3' → 2' feedback loop in docs/three-pass-flow.md is realized
// by the AC: the round-1 pass-3 publish lands at the same key the
// round-2 pass-2 lookup queries. Once published — globally, once
// per srckey — every subsequent render of project A on any node
// sees the AC hit and the converter emits fine-grained cc rules
// without re-running the build.
//
// kind-agnostic. The code in this file does not know what kind it
// renders for. cmd/write-a/handler_autotools_native.go calls
// these helpers passing autotoolsSrckeyPatterns() + the autotools
// dep-kind list; pipelineHandler-shaped kinds (make, etc.) opt in
// by setting traceDrivenSrckeyPatterns + going through the
// pipelineHandler dispatch in handler_pipeline.go. New kinds
// joining the trace-driven path are a one-line opt-in once their
// srckey-pattern set is decided.

// renderTraceDrivenRound2A emits project A's per-element BUILD
// for the round-2 path:
//
//	srckey.txt + srckey-breakdown.txt   (debug + AC-key seed)
//	BUILD.bazel containing the converter genrule:
//	  srcs    = [@src_<key>//:tree, @trace_<elem>//:trace,
//	             imports.json (optional), srckey.txt]
//	  outs    = ["BUILD.bazel.out"]
//	  tools   = ["//tools:convert-element-trace"]
//	  cmd     = stage @trace_<elem>//:trace into a tmpdir,
//	            invoke convert-element-trace --trace-dir.
//
// The kindName parameter only feeds the comment header of the
// rendered BUILD; it does not affect the genrule's behavior
// (convert-element-trace is kind-agnostic at runtime).
func renderTraceDrivenRound2A(elem *element, elemPkg, kindName string, srckeyPatterns *readPathsPatterns) error {
	hash, err := renderSrckeyReturnHash(elem, elemPkg, srckeyPatterns)
	if err != nil {
		return err
	}
	hasImports, err := writeAutotoolsImportsManifest(elem, elemPkg)
	if err != nil {
		return err
	}
	if len(traceConfig.platforms) == 0 {
		return renderTraceDrivenRound2ASinglePlatform(elem, elemPkg, kindName, hasImports, hash)
	}
	return renderTraceDrivenRound2AMultiPlatform(elem, elemPkg, kindName, hasImports, hash)
}

// renderTraceDrivenRound2ASinglePlatform is the byte-stable
// legacy render: one converter genrule per element consuming
// @trace_<elem>//:trace. Output: BUILD.bazel.out at the
// element's package root. This is the path taken when
// --platforms-json is unset (or empty); the rendered bytes
// match the pre-multi-platform shape exactly so existing
// goldens stay valid.
func renderTraceDrivenRound2ASinglePlatform(elem *element, elemPkg, kindName string, hasImports bool, srckeyHash string) error {
	srcLabels := []string{}
	for _, rs := range elem.Sources {
		key := sourceKey(rs)
		if key == "" {
			continue
		}
		srcLabels = append(srcLabels, fmt.Sprintf(`"@src_%s//:tree"`, key))
	}
	srcLabels = append(srcLabels, fmt.Sprintf(`":%s_trace_load"`, elem.Name))
	srcLabels = append(srcLabels, `"srckey.txt"`)
	if hasImports {
		srcLabels = append(srcLabels, `"imports.json"`)
	}

	importsFlag := ""
	if hasImports {
		importsFlag = ` \
            --imports-manifest="$(location imports.json)"`
	}

	build := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:%[4]s round-2 — pass-2 converter genrule.
#
# Reads :%[1]s_trace_load — an action-time trace_load target (see
# rules/traces.bzl) that shells to trace-lookup at action time.
# When the AC has the trace published (hit), the rule materializes
# trace.log + make-db.txt into its declared outputs and the
# marker reports "hit"; convert-element-trace emits cc_library /
# cc_binary into BUILD.bazel.out. When the AC misses (round-2
# boot phase / source change), the rule writes zero-byte trace
# files + a "miss" marker and the converter writes a placeholder
# BUILD.bazel.out; project B's coarse install genrule remains
# the buildable target until pass-3 publishes.

load("//rules:traces.bzl", "trace_load")

package(default_visibility = ["//visibility:public"])

trace_load(
    name = "%[1]s_trace_load",
    srckey = "%[5]s",
)

genrule(
    name = "%[1]s_build",
    srcs = [%[2]s],
    outs = ["BUILD.bazel.out"],
    tools = ["//tools:convert-element-trace"],
    cmd = """
        # Stage trace.log + make-db.txt (when present) into a
        # known dir. The :%[1]s_trace_load filegroup carries
        # trace.log, make-db.txt, and a hit/miss marker; the
        # converter's --trace-dir mode handles empty trace.log
        # as the "no trace yet" signal.
        TRACE_DIR="$$(mktemp -d)"
        for src in $(SRCS); do
            case "$$src" in
                */trace.log) cp -L "$$src" "$$TRACE_DIR/trace.log" ;;
                */make-db.txt) cp -L "$$src" "$$TRACE_DIR/make-db.txt" ;;
            esac
        done
        $(location //tools:convert-element-trace) \
            --trace-dir="$$TRACE_DIR" \
            --out-build="$(location BUILD.bazel.out)"%[3]s
    """,
)
`, elem.Name, strings.Join(srcLabels, ", "), importsFlag, kindName, srckeyHash)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), build)
}

// renderTraceDrivenRound2AMultiPlatform is the per-platform
// fan-out render activated by --platforms-json. For each
// (element, platform) cell, emits one converter genrule that
// reads @trace_<elem>__<platform>//:trace and writes
// <platform>/ir.json + <platform>/BUILD.bazel.out. A trailing
// fold genrule named "<elem>_build" composes the N ir.json
// files into the unified BUILD.bazel.out via fold-element +
// elementfold + emit/bazel.
//
// The fold genrule keeps the "<elem>_build" name so downstream
// references (project B's install genrule data deps, external
// queries) don't need to learn a new label shape — the
// multi-platform mode is transparent to consumers.
//
// The per-platform converter genrule's outputs land under
// <platform>/ subdirectories of the element's package so two
// platforms can't collide on a Bazel output path.
func renderTraceDrivenRound2AMultiPlatform(elem *element, elemPkg, kindName string, hasImports bool, srckeyHash string) error {
	importsFlag := ""
	if hasImports {
		importsFlag = ` \
            --imports-manifest="$(location imports.json)"`
	}

	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by cmd/write-a. Do not edit by hand.
# kind:%[2]s round-2 — multi-platform pass-2 converter + fold.
#
# Each per-platform converter genrule reads its platform-tagged
# trace_load target (:%[1]s_trace_load_<platform>) and emits one
# ir.Package JSON. The trailing fold-element genrule composes
# the N ir.json files into the unified BUILD.bazel.out via
# converter/elementfold — items shared across every
# platform stay flat; per-platform deltas land under select()
# arms keyed by each platform's constraint axis (or operator-
# supplied select_label for matrices the auto-detect can't
# disambiguate).

load("//rules:traces.bzl", "trace_load")

package(default_visibility = ["//visibility:public"])

`, elem.Name, kindName)

	// One trace_load target per platform, pinned to the platform
	// tag so the AC lookup partitions correctly. The srckey is the
	// same hex for every platform — the platform attr is what
	// distinguishes the per-cell AC keys.
	for _, p := range traceConfig.platforms {
		fmt.Fprintf(&b, `trace_load(
    name = "%[1]s_trace_load_%[2]s",
    srckey = "%[3]s",
    platform = "%[2]s",
)

`, elem.Name, p.Name, srckeyHash)
	}

	srcLabelsBase := []string{}
	for _, rs := range elem.Sources {
		key := sourceKey(rs)
		if key == "" {
			continue
		}
		srcLabelsBase = append(srcLabelsBase, fmt.Sprintf(`"@src_%s//:tree"`, key))
	}
	srcLabelsBase = append(srcLabelsBase, `"srckey.txt"`)
	if hasImports {
		srcLabelsBase = append(srcLabelsBase, `"imports.json"`)
	}

	// Per-platform converter genrules.
	cellArgs := make([]string, 0, len(traceConfig.platforms))
	platOutputs := make([]string, 0, len(traceConfig.platforms))
	for _, p := range traceConfig.platforms {
		platSrcs := append([]string(nil), srcLabelsBase...)
		platSrcs = append(platSrcs, fmt.Sprintf(`":%s_trace_load_%s"`, elem.Name, p.Name))
		irPath := fmt.Sprintf("%s/ir.json", p.Name)
		buildPath := fmt.Sprintf("%s/BUILD.bazel.out", p.Name)
		platOutputs = append(platOutputs, irPath)
		fmt.Fprintf(&b, `genrule(
    name = "%[1]s__%[2]s_ir",
    srcs = [%[3]s],
    outs = ["%[4]s", "%[5]s"],
    tools = ["//tools:convert-element-trace"],
    cmd = """
        TRACE_DIR="$$(mktemp -d)"
        for src in $(SRCS); do
            case "$$src" in
                */trace.log) cp -L "$$src" "$$TRACE_DIR/trace.log" ;;
                */make-db.txt) cp -L "$$src" "$$TRACE_DIR/make-db.txt" ;;
            esac
        done
        $(location //tools:convert-element-trace) \
            --trace-dir="$$TRACE_DIR" \
            --out-build="$(location %[5]s)" \
            --out-ir-json="$(location %[4]s)"%[6]s
    """,
)

`, elem.Name, p.Name, strings.Join(platSrcs, ", "), irPath, buildPath, importsFlag)
		cellArgs = append(cellArgs, foldCellArg(p, irPath))
	}

	// Fold genrule: composes the N ir.json files into the
	// unified BUILD.bazel.out via fold-element. Cell args are
	// pipe-separated <name>|<constraints>|<path>[|<select_label>];
	// fold-element's --cell flag parser handles both 3- and 4-
	// field shapes.
	foldSrcs := make([]string, len(platOutputs))
	for i, o := range platOutputs {
		foldSrcs[i] = fmt.Sprintf("%q", o)
	}
	cellArgvLines := make([]string, len(cellArgs))
	for i, a := range cellArgs {
		// Single-quote the cell arg so embedded special chars
		// (Bazel constraint labels carry colons) pass through
		// the shell intact. The fold-element binary parses
		// pipe-separated fields, so colons are content not
		// argument syntax.
		cellArgvLines[i] = fmt.Sprintf("            --cell '%s'", a)
	}

	fmt.Fprintf(&b, `genrule(
    name = "%[1]s_build",
    srcs = [%[2]s],
    outs = ["BUILD.bazel.out"],
    tools = ["//tools:fold-element"],
    cmd = """
        $(location //tools:fold-element) \
            --out-build="$(location BUILD.bazel.out)" \
%[3]s
    """,
)
`, elem.Name, strings.Join(foldSrcs, ", "), strings.Join(cellArgvLines, " \\\n"))

	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), b.String())
}

// foldCellArg renders one --cell argv value for fold-element:
// "<name>|<c1>,<c2>|<path>[|<select_label>]". The path is the
// converter genrule's declared ir.json output, referenced as a
// package-relative path that fold-element's $(location)
// resolution turns into an action-time absolute path.
//
// The optional 4th select_label field is included when the
// platform's SelectLabel is non-empty (the operator-declared
// config_setting label for ambiguous matrices). Empty
// SelectLabel triggers fold-element's auto-detection from the
// constraints axis.
func foldCellArg(p tracePlatform, irPath string) string {
	constraints := strings.Join(p.Constraints, ",")
	parts := []string{p.Name, constraints, "$(location " + irPath + ")"}
	if p.SelectLabel != "" {
		parts = append(parts, p.SelectLabel)
	}
	return strings.Join(parts, "|")
}

// pipelineTraceExtensionRound2 is the pipelineExtension for
// project B's coarse install genrule under round-2: build-tracer
// wraps configure/build/install, the genrule's AppendCmd
// post-processes make-db and runs trace-publish. Outputs:
// install_tree.tar + trace.log + make-db.txt + the per-element
// generated-headers.txt the autotools handler already emits
// (kept under round-2 too — generated-headers feeds future
// converter improvements without re-running the action).
//
// imports.json is intentionally NOT in ExtraSrcs here: the
// round-2 B-side install genrule doesn't run the converter
// (the converter moved to project A's per-element converter
// genrule, which references imports.json via its own srcs).
// Adding the file to this action's inputs would invalidate the
// install action's cache key on every imports.json change with
// no corresponding behavioral effect on the build.
//
// depKindAllow is the set of dep `Bst.Kind` strings whose
// install_tree.tar tarballs should be staged + extracted under
// $DEP_PREFIX so the build pipeline's compile commands can find
// dep headers / libraries. autotools passes []string{"autotools"};
// kind:make passes []string{"make"}; cross-kind dep wiring is a
// follow-up once the fixtures land.
//
// platform / outputPrefix / nameSuffix / execCompatibleWith are
// the per-platform fan-out knobs the project-B caller populates
// when emitting N install genrules per element. All four are
// empty in the single-platform legacy path; the rendered shape
// matches the pre-fan-out goldens byte-for-byte.
func pipelineTraceExtensionRound2(elem *element, depKindAllow []string, plat tracePlatform) *pipelineExtension {
	ext := &pipelineExtension{
		// IsTraceBuild flips the install genrule's name +
		// tagging into the trace_build shape (see
		// handler_pipeline.go's renderInstallGenruleBody): name
		// becomes "<elem>_trace_build" and tags includes
		// "trace_build" for the convergence-driver query.
		IsTraceBuild: true,
		// Pass the per-platform output prefix into the
		// wrapper so the generated-headers.txt diff lands at
		// the genrule's actual declared output path
		// (<plat>/generated-headers.txt under multi-platform
		// fan-out, bare generated-headers.txt under the
		// single-platform legacy shape).
		WrapPipelineCmds: func(cmds string) string { return wrapAutotoolsPipelineCmds(cmds, plat.Name) },
		AppendCmd:        pipelineTracePublishStep(elem.Name, plat.Name, plat.Name),
		ExtraOuts: []string{
			"trace.log",
			"make-db.txt",
			"generated-headers.txt",
		},
		ExtraTools: []string{
			"//tools:build-tracer",
			"//tools:trace-publish",
		},
		// srckey.txt is the only ExtraSrcs entry under round-2:
		// trace-publish reads it to derive the synthetic Action
		// digest. The caller (pipelineHandler.RenderB or
		// autotoolsHandler.RenderB) calls renderSrckey before
		// the genrule fires so the file exists at action time.
		ExtraSrcs: []string{"srckey.txt"},
	}
	if plat.Name != "" {
		ext.OutputPrefix = plat.Name
		ext.NameSuffix = "_" + plat.Name
		ext.ExecCompatibleWith = append([]string(nil), plat.Constraints...)
	}

	allow := map[string]bool{}
	for _, k := range depKindAllow {
		allow[k] = true
	}
	var depLabels []string
	for _, dep := range elem.Deps {
		if dep == nil || !allow[dep.Bst.Kind] {
			continue
		}
		// Multi-platform mode: depend on the dep's per-platform
		// install_tree.tar output directly rather than the
		// top-level select()-filegroup. Bazel's select()
		// resolves on the build's TARGET platform, not the
		// dependent action's exec_compatible_with, so when N
		// per-platform install actions run in one Bazel
		// invocation they would all see the same select-
		// resolved tar (the target platform's) rather than
		// each platform's matching tar. Pointing at
		// `//elements/<dep>:<plat>/install_tree.tar` directly
		// — the per-platform output file the dep's
		// `<dep>_install_<plat>` genrule declared — bypasses
		// the select and routes each action to the matching
		// per-platform dep. The top-level
		// :install_tree.tar filegroup stays valid for
		// downstream consumers that don't have their own
		// per-platform fan-out.
		//
		// Single-platform legacy mode (plat.Name == ""):
		// the dep's per-element render also emitted a single
		// :install_tree.tar genrule output without any
		// platform prefix, so the legacy label form points at
		// the right thing as before.
		if plat.Name != "" {
			depLabels = append(depLabels, fmt.Sprintf("//elements/%s:%s/install_tree.tar", dep.Name, plat.Name))
		} else {
			depLabels = append(depLabels, fmt.Sprintf("//elements/%s:install_tree.tar", dep.Name))
		}
	}
	if len(depLabels) > 0 {
		ext.DepLabels = depLabels
		ext.DepExtractCmd = autotoolsDepExtractCmd()
	}
	return ext
}

// pipelineTracePublishStep is the AppendCmd snippet that runs
// after the build pipeline. Three sub-steps:
//
//  1. Capture the post-build make database to make-db.txt
//     (mirrors the inline sed filter so byte-stable across runs).
//  2. Copy the canonical trace.log out of $$AUTOTOOLS_TRACE
//     so it lands at the genrule's declared trace.log output.
//  3. Invoke trace-publish, IFF the action environment supplies
//     CAS_GRPC_ADDR (devs running locally without a remote cache
//     leave the variable unset; the build still succeeds, no AC
//     entry is published).
//
// The step is kind-agnostic at runtime: any pipeline kind's
// build that produces a Makefile-compatible artifact can run
// `make -np` (defaults to a no-op when no Makefile is present;
// `|| true` keeps the genrule action alive). For kinds whose
// build never produces a Makefile (kind:script edge cases),
// make-db.txt ends up empty — the converter tolerates that.
//
// platform is the CMAKE_TO_BAZEL_PLATFORM tag pinned at render
// time when the project B side is fanning out per-platform.
// Empty falls back to the env-driven shape (single-platform
// legacy operators set the env via --action_env). outputPrefix
// is the per-platform OutputPrefix that prefixes the trace.log
// and make-db.txt $(location) references — must agree with the
// extension's ExtraOuts so the cmd writes to the right declared
// output paths.
func pipelineTracePublishStep(elemName, platform, outputPrefix string) string {
	_ = elemName // reserved for future per-element diagnostics
	trace := "trace.log"
	makeDB := "make-db.txt"
	if outputPrefix != "" {
		trace = outputPrefix + "/trace.log"
		makeDB = outputPrefix + "/make-db.txt"
	}
	// publishPlatform is the literal value the trace-publish
	// invocation sends as --platform=. When the caller supplied
	// a platform tag (multi-platform fan-out), bake it in so the
	// AC entry lands under the matching partition. Otherwise
	// preserve the env-driven shape — single-platform operators
	// still set CMAKE_TO_BAZEL_PLATFORM via --action_env.
	publishPlatform := `$${CMAKE_TO_BAZEL_PLATFORM:-}`
	if platform != "" {
		publishPlatform = platform
	}
	return fmt.Sprintf(`        # === make-db post-process (round 2) ===
        # Same sed filter the autotools install genrule applies
        # inline (drop variant lines whose bytes drift across
        # runs of an otherwise-identical build: mtimes,
        # file-count summaries, db print timestamps). The
        # publisher path's tracenorm.FilterMakeDB re-applies the
        # same drop list defensively in-process.
        ( make -np 2>/dev/null || true ) \
            | sed -E '/^#[[:space:]]+Last modified /d; /\(device [0-9]+, inode [0-9]+\): [0-9]+ files,/d; /^# [0-9]+ files,.*impossibilities in /d; /^# Make data base, printed on /d; /^# Finished Make data base on /d' \
            | sed -e "s|$$INSTALL_ROOT|/INSTALL_ROOT|g" \
                  -e "s|$$BUILD_ROOT|/BUILD_ROOT|g" \
                  -e "s|$${DEP_PREFIX:-/__unset_dep_prefix__}|/DEP_PREFIX|g" \
            > "$$EXEC_ROOT/$(location %[2]s)"

        # Surface the canonical trace.log as a declared output of
        # this genrule. trace-publish reads it from here.
        cp -L "$$AUTOTOOLS_TRACE" "$$EXEC_ROOT/$(location %[1]s)"

        # Publish to the AC iff a remote is configured. Empty
        # CAS_GRPC_ADDR ⇒ skip (e.g. local dev without buildbarn);
        # the build succeeds, no AC entry is written, and the
        # next render of project A sees a miss → coarse fallback.
        # The trace-publish binary itself ALSO short-circuits on
        # empty --cas; checking here keeps the genrule output
        # readable when a developer is debugging.
        cd "$$EXEC_ROOT"
        if [ -n "$${CAS_GRPC_ADDR:-}" ]; then
            # --platform= partitions the synthetic AC keyspace
            # per target platform. Multi-platform fan-out bakes
            # the platform tag literally into this argv so each
            # of N per-platform genrules publishes under its own
            # tag. Single-platform legacy operators leave platform
            # empty here; the env-var fallback
            # (--action_env=CMAKE_TO_BAZEL_PLATFORM=...) keeps
            # working.
            $(location //tools:trace-publish) \
                --cas="$${CAS_GRPC_ADDR}" \
                --srckey="$$(cat $(location srckey.txt) | tr -d '[:space:]')" \
                --platform="%[3]s" \
                --trace="$(location %[1]s)" \
                --make-db="$(location %[2]s)" >/dev/null
        fi`, trace, makeDB, publishPlatform)
}
