package main

import (
	"fmt"
	"path/filepath"
)

func init() { registerHandler(collectInitialScriptsHandler{}) }

// collectInitialScriptsHandler renders kind:collect_initial_scripts
// as an empty-install genrule. The plugin is FDSDK-local (lives
// under FreeDesktop SDK's own plugins/, not buildstream-plugins-
// community); real behaviour walks dep install trees for
// `%{install-root}/usr/lib/initial-scripts/*` and assembles a
// runtime init-script set. v1 produces a placeholder install-root
// TreeArtifact so downstream consumers (kind:flatpak_image, etc.)
// can reference it without breaking the graph.
//
// 15 of FDSDK's elements use kind:collect_initial_scripts
// (1.4 % of the total). All live under elements/initial-scripts/
// in the FreeDesktop SDK tree.
//
// v1 caveats — same shape as collect_manifest:
//   - The emitted tarball is empty; downstream elements that
//     consume the assembled scripts in real builds will get
//     nothing useful from it. Fine for write-a's render success;
//     bazel-build-time correctness for these elements lands
//     when the real plugin's logic is ported.
//   - The element's build-depends are still honored at the graph
//     level (loadGraph wires them onto element.Deps), so dep-
//     ordering and source-fetch lookups stay correct.
type collectInitialScriptsHandler struct{}

func (collectInitialScriptsHandler) Kind() string                                 { return "collect_initial_scripts" }
func (collectInitialScriptsHandler) NeedsSources() bool                           { return false }
func (collectInitialScriptsHandler) HasProjectABuild() bool                       { return true }
func (collectInitialScriptsHandler) DefaultReadPathsPatterns() *readPathsPatterns { return nil }

func (collectInitialScriptsHandler) RenderA(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:collect_initial_scripts — FDSDK-local initial-scripts
# collector. v1 emits an empty install tree as a placeholder;
# real assembly (walks dep install trees for
# %%{install-root}/usr/lib/initial-scripts/) lands when an
# FDSDK fixture forces it.

load("@rules_buildstream_bazel//rules:install.bzl", "pipeline_install")

package(default_visibility = ["//visibility:public"])

pipeline_install(
    name = "%[1]s_install",
    srcs = [],
    command = """
        mkdir -p "@@INSTALL_DIR@@"
    """,
)
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (collectInitialScriptsHandler) RenderB(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:collect_initial_scripts — install tree produced by project
# A's genrule (see //elements/%[1]s in project A). Placeholder
# until the typed-filegroup wrapper lands.
filegroup(name = "BUILD_NOT_YET_STAGED", srcs = [])
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}
