package main

// rules/traces.bzl renderer.
//
// The traces rule is project A's consumer side of the round-2
// AC rendezvous. Every kind that publishes a trace (autotools /
// make / makemaker / modulebuild / manual / script — and
// kind:cmake / kind:meson under their round-2 fallback shapes)
// gets one trace_load target per element. The target runs the
// trace-lookup tool as a Bazel action:
//
//   - AC hit  ⇒ trace.log (+ make-db.txt for trace-driven kinds)
//               are materialized into the action's declared
//               outputs; the marker carries "hit\n".
//   - AC miss ⇒ trace.log (+ make-db.txt when declared) are
//               zero-byte files; the marker carries "miss\n".
//
// The converter genrule for the element consumes
// :<elem>_trace_load via srcs (filegroup-style); seeing empty
// bytes routes the converter through the same coarse-fallback
// path the legacy `_trace_repo` empty-fileset triggered.
//
// Why an action, not a repository rule:
//
// The previous shape (`_trace_repo`) did its GetActionResult at
// Bazel LOAD time via `rctx.execute`. That meant every `bazel
// build` over project A re-ran the lookup before analysis could
// start, and the analysis cache was invalidated whenever the AC
// view shifted (between driver passes, between dev sessions,
// between developer hosts). Moving the lookup into an action
// fixes both: the action's inputs are hermetic (the srckey file
// + the tool), so Bazel's ActionCache works normally; AC
// re-querying happens only when the operator explicitly bumps
// the convergence-generation environment (which the driver loop
// does between rounds — see `docs/three-pass-flow.md`).
//
// Inputs:
//   - srckey: a Label pointing at the element's srckey.txt
//     (rendered by write-a alongside the per-element BUILD).
//   - platform: optional platform tag pinning the AC keyspace
//     partition; matches the publishing side's --platform.
//   - expect_make_db: declares whether the trace producer for
//     this kind emits make-db.txt alongside trace.log.
//     Trace-driven kinds set True; cmake / meson round-2
//     fallback (whose converters derive IR from trace + cmake
//     File API / meson introspection, not from a make-db) set
//     False.
//
// Action env (the operator passes via --action_env):
//   - CAS_GRPC_ADDR — the REAPI gRPC endpoint trace-lookup
//                     queries. Empty/unset ⇒ permanent miss.
//   - CONVERGE_GENERATION — opaque token the driver bumps
//                     between rounds to force action re-runs
//                     when the AC view may have changed.
//                     Without the bump, Bazel's ActionCache
//                     would re-use the previous round's
//                     (probably-miss) output even after the
//                     trace lands. Declared in the rule's
//                     env_attribute list so changes invalidate
//                     the action.
//
// Outputs:
//   - <name>/trace.log
//   - <name>/make-db.txt  (when expect_make_db is True)
//   - <name>/marker
//
// The action always succeeds (miss is not an error); the marker
// is the hit/miss signal for downstream rules / the convergence
// driver.

func renderTracesBzl() string {
	return `# Generated by cmd/write-a. Do not edit.

"""trace_load — action-time consumer side of the round-2 AC
rendezvous.

One trace_load target per round-2-using element. The action
shells to trace-lookup; outputs are trace.log (+ make-db.txt
for trace-driven kinds) and a hit/miss marker. AC miss produces
zero-byte trace files, so converters route through their
coarse-fallback path the same way the legacy load-time
_trace_repo empty fileset did.

The lookup needs CAS_GRPC_ADDR via --action_env. The driver
loop bumps CONVERGE_GENERATION between rounds (also via
--action_env) to force action re-runs when the AC view shifts.

Replaces the legacy load-time _trace_repo + traces module
extension; the AC lookup is now Bazel-action-cached, ending
the analysis-cache churn between driver passes.
"""

def _trace_load_impl(ctx):
    out_trace = ctx.actions.declare_file(ctx.label.name + "/trace.log")
    out_marker = ctx.actions.declare_file(ctx.label.name + "/marker")
    outputs = [out_trace, out_marker]

    args = ctx.actions.args()
    args.add("--srckey", ctx.attr.srckey)
    args.add("--out-trace", out_trace)
    args.add("--out-empty-marker", out_marker)

    if ctx.attr.expect_make_db:
        out_make_db = ctx.actions.declare_file(ctx.label.name + "/make-db.txt")
        outputs.append(out_make_db)
        args.add("--out-make-db", out_make_db)

    if ctx.attr.platform:
        args.add("--platform", ctx.attr.platform)

    # trace-lookup reads CAS_GRPC_ADDR from the action env when
    # --cas is unset; the operator passes it via
    # --action_env=CAS_GRPC_ADDR. CONVERGE_GENERATION is the lever
    # the driver loop pulls between rounds — Bazel's ActionCache
    # tracks --action_env values, so a bump forces a re-run.
    # use_default_shell_env opts the action into seeing the build's
    # --action_env values without us having to enumerate them
    # explicitly (the alternative — env = {"CAS_GRPC_ADDR": ...}
    # populated from ctx.var — doesn't work for --action_env, which
    # is a Bazel-flag-level concern not a Starlark-visible one).
    ctx.actions.run(
        outputs = outputs,
        executable = ctx.executable._trace_lookup,
        arguments = [args],
        use_default_shell_env = True,
        mnemonic = "TraceLoad",
        progress_message = "trace-load %{label}",
    )
    return [DefaultInfo(files = depset(outputs))]

trace_load = rule(
    implementation = _trace_load_impl,
    attrs = {
        "srckey": attr.string(
            mandatory = True,
            doc = "Hex-encoded srckey seed for the synthetic AC key. write-a renders this attr from the same value it writes to project B's srckey.txt; passing as a string avoids needing to render srckey.txt into project A and keeps the rule's input set minimal (the tool + the build's --action_env).",
        ),
        "platform": attr.string(
            default = "",
            doc = "Platform tag partitioning the synthetic AC keyspace. Matches the publishing side's --platform.",
        ),
        "expect_make_db": attr.bool(
            default = True,
            doc = "Declares whether the publishing kind emits make-db.txt alongside trace.log. Trace-driven kinds (autotools / make / makemaker / modulebuild / manual / script) set True; cmake / meson round-2 fallback set False.",
        ),
        "_trace_lookup": attr.label(
            default = "//tools:trace-lookup",
            executable = True,
            cfg = "exec",
            allow_single_file = True,
            doc = "The trace-lookup binary. Staged into //tools by write-a.",
        ),
    },
    doc = "Action-time consumer side of the round-2 rendezvous. Materializes the trace's Directory into the action's declared outputs on AC hit; writes zero-byte trace files plus a miss-marker on AC miss.",
)
`
}
