package main

// rules/traces.bzl renderer.
//
// The traces module extension declares one external repo per
// kind:autotools element in the graph (one per entry in
// tools/traces.json). At Bazel load time each repo's _trace_repo
// rule shells out to the trace-lookup CLI:
//
//   - AC hit  ⇒ rule symlinks
//                 <CAS_FUSE_MOUNT>/blobs/directory/<digest>
//               under "trace_dir/" and emits a filegroup over the
//               two files (trace.log + make-db.txt) that the
//               kind:autotools converter genrule consumes via
//               srcs = [..., "@trace_<key>//:trace"].
//   - AC miss ⇒ rule emits an empty :trace filegroup. The
//               converter sees an empty trace fileset and falls
//               back to emitting the coarse pass-3 genrule into
//               project B (configure / make / make-install +
//               build-tracer + the inline trace-publish step).
//               Round-2 boots from this miss: pass-3 runs the
//               coarse build, trace-publish lands the AC entry,
//               and the next render of A on any node sees a hit.
//
// Mirror of cmd/write-a/sources_bzl.go's structure: same
// module-extension shape, same repo-name convention (`trace_<key>`
// vs `src_<key>`), same env-driven mount path.
//
// Three env vars feed the rule (passed via --repo_env=… on
// project-A bazel invocations):
//
//   - CAS_GRPC_ADDR   — the REAPI gRPC endpoint trace-lookup
//                       queries. Empty / unset ⇒ permanent miss
//                       (no remote configured, e.g. an offline
//                       dev render).
//   - CAS_FUSE_MOUNT  — the cas-fuse / bb_clientd mount root, same
//                       value the sources extension reads. The
//                       symlink target is
//                       `<CAS_FUSE_MOUNT>/<CAS_DIRECTORY_PREFIX>/directory/<digest>`.
//   - CAS_DIRECTORY_PREFIX — path layout under the mount;
//                       defaults to "blobs" (cmd/cas-fuse). For
//                       bb_clientd, set to
//                       `cas/<instance>/blobs/<digest_function>`.
//                       Same env var rules/sources.bzl reads, so a
//                       single --repo_env covers both extensions.
//   - TRACE_LOOKUP_BIN — absolute path to the cmd/trace-lookup
//                       binary. Required when CAS_GRPC_ADDR is
//                       set; without it the rule can't actually
//                       perform the lookup and falls back to miss.
//
// Optional:
//   - TRACE_REPO_NONCE — opaque env var the rule declares in
//                        `environ`. Bumping its value forces
//                        Bazel to re-run the repo rule even when
//                        the static inputs haven't changed; used
//                        to defeat repo-rule caching when the
//                        operator wants a fresh AC query.

func renderTracesBzl() string {
	return `# Generated by cmd/write-a. Do not edit.

"""Module extension that declares one external repo per
kind:autotools element's srckey. The repo's ":trace" filegroup
resolves to either a 2-file fileset (trace.log + make-db.txt
from the cas-fuse / bb_clientd mount, when the AC has the trace
published) or to an empty filegroup (when the lookup misses;
downstream converter falls back to coarse).

Configuration (pass via --repo_env=KEY=VALUE on project-A bazel
invocations):

  --repo_env=CAS_GRPC_ADDR=127.0.0.1:8980
  --repo_env=CAS_FUSE_MOUNT=/var/cache/cmake-to-bazel/cas
  --repo_env=CAS_DIRECTORY_PREFIX=blobs   # default; cmd/cas-fuse layout
  --repo_env=TRACE_LOOKUP_BIN=/abs/path/to/trace-lookup

The symlink target is
<CAS_FUSE_MOUNT>/<CAS_DIRECTORY_PREFIX>/directory/<digest>.
Default prefix "blobs" matches the flat layout cmd/cas-fuse
serves. bb_clientd users set the prefix to
cas/<instance>/blobs/<digest_function> to land on the canonical
bb_clientd layout (see docs/design/bazel9-cas-fs.md). The same
env var rules/sources.bzl reads, so a single --repo_env covers
both extensions.

Optional:
  --repo_env=TRACE_REPO_NONCE=<any>  # bump to force re-evaluation
"""

def _trace_repo_impl(rctx):
    srckey = rctx.attr.srckey
    addr = rctx.os.environ.get("CAS_GRPC_ADDR", "")
    mount = rctx.os.environ.get("CAS_FUSE_MOUNT", "")
    prefix = rctx.os.environ.get("CAS_DIRECTORY_PREFIX", "blobs")
    lookup_bin = rctx.os.environ.get("TRACE_LOOKUP_BIN", "")
    rctx.file("WORKSPACE", "")

    # Empty fallback: any of the three env requirements absent
    # ⇒ render an empty :trace filegroup. The kind:autotools
    # converter treats that as the "no trace yet" signal and
    # emits the coarse pass-3 genrule.
    empty_build = '''filegroup(
    name = "trace",
    srcs = [],
    visibility = ["//visibility:public"],
)
'''
    if addr == "" or mount == "" or lookup_bin == "" or srckey == "":
        rctx.file("BUILD.bazel", empty_build)
        return

    # Lookup the synthetic AC key for this srckey. trace-lookup
    # exits 0 with empty stdout on miss, exits 0 with "<hash>/<size>"
    # on hit, and exits non-zero on hard error (gRPC dial fail
    # etc.). We treat any non-zero result as miss too — repo-rule
    # eval shouldn't fail the build just because the cache is
    # unreachable; the converter's coarse fallback is the
    # available-mode path.
    res = rctx.execute([lookup_bin, "--cas=" + addr, "--srckey=" + srckey])
    if res.return_code != 0:
        rctx.file("BUILD.bazel", empty_build)
        return
    line = res.stdout.strip()
    if line == "":
        rctx.file("BUILD.bazel", empty_build)
        return

    # trace-lookup prints "<hash>/<size>". The FUSE mount serves
    # any Directory blob in CAS at
    # <mount>/<prefix>/directory/<hash>; default prefix "blobs"
    # matches cmd/cas-fuse, bb_clientd users set it to
    # cas/<instance>/blobs/<digest_function> for the daemon's
    # canonical layout. Symlinking under trace_dir/ then globbing
    # produces the 2-file filegroup the converter consumes.
    parts = line.split("/")
    if len(parts) != 2:
        rctx.file("BUILD.bazel", empty_build)
        return
    hash = parts[0]
    target = mount + "/" + prefix + "/directory/" + hash
    rctx.symlink(target, "trace_dir")
    rctx.file("BUILD.bazel", '''# Generated by rules/traces.bzl.
exports_files(
    glob(["trace_dir/**"], allow_empty = True),
)

filegroup(
    name = "trace",
    srcs = glob(["trace_dir/**"], allow_empty = True),
    visibility = ["//visibility:public"],
)
''')

_trace_repo = repository_rule(
    implementation = _trace_repo_impl,
    attrs = {
        "srckey": attr.string(mandatory = True),
    },
    environ = [
        "CAS_GRPC_ADDR",
        "CAS_FUSE_MOUNT",
        "CAS_DIRECTORY_PREFIX",
        "TRACE_LOOKUP_BIN",
        "TRACE_REPO_NONCE",
    ],
)

def _traces_impl(module_ctx):
    json_label = None
    for mod in module_ctx.modules:
        for tag in mod.tags.from_json:
            json_label = tag.path
    if json_label == None:
        fail("traces extension: at least one .from_json(path = ...) tag required")
    raw = module_ctx.read(json_label)
    data = json.decode(raw)
    for entry in data.get("traces", []):
        _trace_repo(
            name = "trace_" + entry["key"],
            srckey = entry.get("srckey", ""),
        )

traces = module_extension(
    implementation = _traces_impl,
    tag_classes = {
        "from_json": tag_class(attrs = {"path": attr.label(mandatory = True)}),
    },
)
`
}
