/* gen_value() comes from the source generated by the out-of-tree module's
 * in-tree tool — extracted to a regenerating genrule under best-effort. */
extern int gen_value(void);

int main(void) {
	return gen_value() == 7 ? 0 : 1;
}
